### ISSUE TITLE
Nothing showing up.

### ISSUE THREAD

**Issue by west1778** [ironmonk88/monks-tokenbar#1]
Nothing showing up for me and I'm getting an error. Any suggestions? No other modules running.

![image](https://user-images.githubusercontent.com/73608023/105657226-e6c6f700-5e91-11eb-92af-475320a42db8.png)

**Comment by ironmonk88** [comment]
Looks like there were tokens, with actors, that had no skills.
Updated the code to default the passive perception if there are no skills available.
