### ISSUE TITLE
Suggestion: Config to use portrait instead of token image

### ISSUE THREAD

**Issue by Ikabodo** [ironmonk88/monks-tokenbar#10]
It would be useful if you could add a config to use portait images instead of token images on the bar. Sometimes this makes it easier to locate the character (depending on what token is used). 

This will also work well with: #9

**Comment by ironmonk88** [comment]
Added the setting.  Will be available in the next version.

**Comment by ironmonk88** [comment]
Should now be available in settings.  Thanks for the good suggestions.  :-)
