### ISSUE TITLE
Tokenbar roll button blocked by Hide Roll Details in Midi-Qol

### ISSUE THREAD

**Issue by trdischat** [ironmonk88/monks-tokenbar#101]
I am trying to use Monk's Toolbar in conjunction with Midi-Qol to request saving throws from players, but I am running into a problem.  I try to limit the amount of information that my players have about their opponent's attack and damage rolls.  So my preference in Midi-Qol is the set the GM / Hide Roll Details option to "Entire Roll", the most restrictive setting.  But when I do this, Monk's Toolbar loses its d20 roll button in the chat box that pops up in the player's Chat Log.  This is all that is left:
![chrome_yj68IsAlXo](https://user-images.githubusercontent.com/52774325/121158002-e0ad3380-c7fe-11eb-908f-57f1a636ec18.png)
If I set the GM / Hide Roll Details option to any other choice, this is what I get:
![chrome_n0dqmfePk8](https://user-images.githubusercontent.com/52774325/121158697-69c46a80-c7ff-11eb-84b0-3af6754be5c3.png)
So to use Monk's Toolbar here I need to reveal at least the d20 attack roles of monsters to the players when using Midi-Qol.

**Comment by ironmonk88** [comment]
Closing this only because it's more of a Midi-Qol issue than TokenBar.
There's not much I can do because Midi-Qol literally removes all the controls from the chat message, so it's not a matter of showing them again, it's more a matter of Midi-Qol not removing them.

**Comment by trdischat** [comment]
No problem. Thanks for the explanation.
