### ISSUE TITLE
Natural Weapons and Passive Features are lootable

### ISSUE THREAD

**Issue by vanderleitelesjr** [ironmonk88/monks-tokenbar#103]
After converting a creature to lootable, the GM will see on its sheet only the actual items it was carrying, however when any player opens the sheet to grab the loot they are able too see everything, including the creature's natural weapons and passives.

GM View:
![image](https://user-images.githubusercontent.com/40318093/121726744-57795380-cac1-11eb-9c14-9c2b9ceda537.png)

Player View:
![image](https://user-images.githubusercontent.com/40318093/121726872-8263a780-cac1-11eb-9e8a-334db60ee30b.png)

**Comment by ironmonk88** [comment]
0.8.x does things differently.  Looks like I have to delete items individually rather than as a group.
Should be fixed in the next release.

**Comment by ironmonk88** [comment]
Should be fixed int he latest version.
