### ISSUE TITLE
Dice So Nice displaying the rolled dice for requested rolls. 

### ISSUE THREAD

**Issue by RobTheDM** [ironmonk88/monks-tokenbar#104]
This appears to only be happening in the PF1 system as I tested it in a 5e world with the same setup. Whenever the GM requests a blind roll from a player, the player will still see the DSN 3D die roll on their screen (although they won't see the result in chat). So they still see what they rolled on the die. 

Also in PF1, during this type of roll, the GM will see two copies of the dice roll across their screen. Players don't seem to see it, but it generates an identical copy of the die being rolled (both results are always the same). Doesn't appear to have any impact on the result in the chat card though.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
