### ISSUE TITLE
enhancement: allow players to request movement access out of turn

### ISSUE THREAD

**Issue by SR5060** [ironmonk88/monks-tokenbar#108]
Often times (at least in my games) players have "clean up" movement right after their turn has finished. it would be great to be able to prompt the DM to allow this movement when a player tries to move out of turn and let the DM decide if it's allowable. 

This feature is currently supported in the "Not your turn" module and is the primary reason why I keep that module around, but module consolidation would be great given the tokenbar is so close to function parity.

**Comment by ironmonk88** [comment]
I've added two settings.  
Allow the player to move their token if they were the previous turn.  This will allow the previous token to "clean up".
And second, I've added a movement toggle to the combat tracker so you can easily toggle the movement for a token while in combat.

I kind of want to avoid having things that take the GM's attention to deal with in the middle of combat.  The first option doesn't require any attention from the GM and good if you trust your players.  The second makes it easy to allow the movement if they ask for it verbally.  I know it's not exactly what the other modules provide, but I wanted to stay away from having dialogs pop up that you have to clear to continue with the game.

**Comment by SR5060** [comment]
Makes sense, I think the first setting addresses my main issue perfectly. I probably wouldn't allow people to clean up more than one turn anyway

**Comment by ironmonk88** [comment]
Available in the latest release.
