### ISSUE TITLE
converting to lootable not working

### ISSUE THREAD

**Issue by jwrpalmer99** [ironmonk88/monks-tokenbar#109]
it seems converting to lootable on combat end isn't working, there is a bug on line 205 of lootables.js

await token.token.document.update({

should read

await token.token.update({

**Comment by ironmonk88** [comment]
Fixed.  Will be available in the next release.

**Comment by ironmonk88** [comment]
Should be fixed now.

**Comment by sPOiDar** [comment]
@ironmonk88 looks like this fix was never committed/released:
https://github.com/ironmonk88/monks-tokenbar/blob/main/apps/lootables.js#L206
