### ISSUE TITLE
Suggestion: Expand the roll-function

### ISSUE THREAD

**Issue by Ikabodo** [ironmonk88/monks-tokenbar#11]
This function really is the hidden 💎 of this module, and could easily be of use on it's own. It's one of the better implementations of roll requests I've seen. It clearly gives the player the feeling they are rolling themselves as well as clearly showing the gm the results.

I suggest you expand this function to work as an overall "request roll" function. Here are some suggestion you could use:

1. Add toolkits to the roll-function (get them from the sheets of the tokens in the list)
2. Rename it from "saving throws" to "request roll".
3. Add API/macro. This way you can add links in for example a journal, or save useful macros like "request perception check for all actors". You can also prepare rooms with traps or other saves and give them a one click function.
4. Add the ability to add actors without marking the tokens (ie, if no token is selected when you click add, you get a menu of all possible actors and you can add them anyway). This way you don't have to find all actors if you want them all to roll.

**Comment by ironmonk88** [comment]
I think most of these have been covered in various versions.
The API documentation is horrible at the moment, but working on it.
