### ISSUE TITLE
[Pathfinder1e] Divide XP

### ISSUE THREAD

**Issue by overdox** [ironmonk88/monks-tokenbar#110]
Diving XP by "larget share to lower level" is not working as intended, I believe.
As seen here:
![Larger_share](https://user-images.githubusercontent.com/6378329/124360454-315f5300-dc2a-11eb-9e99-661c5123e7dc.png)

The Level 1 character has 876 xp
The Level 5 character has 22000 xp
The Level 9 character has 90000 xp
The Level 10 character has 105000 xp

Foundry 0.8.8 and Pathfinder 1e 0.78.14

**Comment by ironmonk88** [comment]
Looks like PF1 was recording levels slightly differently.  I believe it's been fixed now.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
