### ISSUE TITLE
Add specific Tokens only on the Tokenbar

### ISSUE THREAD

**Issue by thatlonelybugbear** [ironmonk88/monks-tokenbar#112]
Just wondering if you would consider giving the GM the option to add/remove specific tokens to the Tokenbar, or maybe implementing a lock feature/mechanism that would stop the auto adding of new tokens. 

If I am not mistaken, now all creatures that are "Friendly" and owned by a player are added by default. This is a bit tricky when you create other NPCs  and set them to friendly.

For example, a player casts Animate Object and creates 10 friendly tiny creatures that they get added to the Tokenbar by default. 

Setting other creatures to Neutral to avoid this behaviour is not always a valid workaround, as there are macros involved as well as other modules that take into consideration the token's disposition (eg. for flanking).

**Comment by ironmonk88** [comment]
Next release you should be able to specifically set if a token will show on the token bar.  It'll do its best to automate it, but you can remove (or add ones) you'd like not to see.

**Comment by ironmonk88** [comment]
This should be available in the latest release.
Adding or removing the token is editable from the token config dialog on the character tab.
