### ISSUE TITLE
Error on roll ability checks [Pathfinder 2e]

### ISSUE THREAD

**Issue by viniciusaraujo093** [ironmonk88/monks-tokenbar#113]
Request  roll and Contested Roll have a error when request ability checks.

![image](https://user-images.githubusercontent.com/57771177/125070452-591d4380-e08e-11eb-9e0b-796488ed01f6.png)

Foundry Version: 0.8.8
Pathfinder 2e Version : 2.8.1.6593
Browser: Google Chrome
No extra modules active

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
