### ISSUE TITLE
ability rolls 

### ISSUE THREAD

**Issue by montver** [ironmonk88/monks-tokenbar#115]
In swade it would be interesting to be able to request skill rolls such as athletics, notice ....

**Comment by JaySK015** [comment]
I would also like a way to add skill rolls to the requested rolls!  Thanks for your great work ironmonk88!

**Comment by ironmonk88** [comment]
Okay, this is a bit of a hack.  The way SWADE does things with skills is they each have their own id and are all custom.  So the only way to link them is through their name.  TokenBar will do it's best, but it's a little unpredictable.

**Comment by ironmonk88** [comment]
Skills have been added in the latest release.
