### ISSUE TITLE
New token add/remove functionality is not extended to requested rolls.

### ISSUE THREAD

**Issue by spamtek** [ironmonk88/monks-tokenbar#116]
When adding new tokens to the bar through config, they do not appear by default in requested rolls unless they are explicitly selected, as requested rolls does a separate check for player characters.

![brave_nwNAnqhoCa](https://user-images.githubusercontent.com/40933065/125220033-001efc80-e294-11eb-9284-a8c0db42d0bd.png)

**Comment by ironmonk88** [comment]
Updated Tokenbar to us the currently selected tokens rather than player controlled.
