### ISSUE TITLE
Tokens No longer appear on token bar in 1.0.44

### ISSUE THREAD

**Issue by foxreinhold** [ironmonk88/monks-tokenbar#117]
Downgrading to 1.0.43 solved the problem, but in 1.0.44 on Foundry 0.8.8 DnD 1.3.6 tokens no longer appear in the bar.

**Comment by ironmonk88** [comment]
Can you confirm that they are player owned, and not NPC?
And are there any errors in the console?

I'm having a hard time replicating the issue, all the worlds I've tried testing in are showing the tokens.

**Comment by foxreinhold** [comment]
No errors in console.  Disabling everything but libwrapper and Token bar doesn't help.  They are player owned (by Trusted Players) and appear just fine in 1.0.43 when I manually downgrade.  They still appear in the request roll section as seen here but no tokens to be found: 
![image](https://user-images.githubusercontent.com/77173822/125371601-163dc300-e34f-11eb-83d6-cb790fc0ee62.png)

**Comment by foxreinhold** [comment]
It seems that the upgrade took then off the token bar and reset the "Show on Token Bar" property.  Rechecking it fixes the problem, however, the next time the prototype token is opened back up, it unchecks itself and thus needs to be rechecked every single time the prototype is opened so future spawns on the same token on new scenes show up.

**Comment by foxreinhold** [comment]
![mtbuncheck](https://user-images.githubusercontent.com/77173822/125372480-34a4be00-e351-11eb-8966-968b28860e4d.gif)

**Comment by ironmonk88** [comment]
I think I might have figured out what's going on.
1.0.45 is released.  I'm hoping that either solves it or highlights what's going on.
I've changed the checkbox to a drop down, so you can choose Default, Include, and Exclude.
If the tokens are still not showing up... then they're being rejected from the default for some reason.

**Comment by foxreinhold** [comment]
Just tested.   All tokens show up, but opening the prototype token sheet again after closing it always resets to "Default", including if the sheet was successfully saved as an Include or Exclude previously.  I tested with everything disabled except libwrapper and token bar.

**Comment by Raileth** [comment]
I have the same problem for some reason only one of my tokens shows when set to default, if i set them manually to 'include' then they appear.  - Using SWADE ruleset here. let me know if you want anything else / to see  the issue as i can show the 2 characters side by side

Thanks

**Comment by ironmonk88** [comment]
Sorry... I completely missed another requirement for some reason.  Are they friendly disposition?

**Comment by Raileth** [comment]
that sorts it - if its friendly it appears

**Comment by ironmonk88** [comment]
Yayy!  Hoping that's the same issue for foxreinhold.  Can't believe I forgot about that.  It's so that monsters can be converted to lootable.  The players have access to them, but they shouldn't show up on the bar.

**Comment by foxreinhold** [comment]
The tokens are showing on the token bar now, so technically that's not the problem anymore.  The problem is prototype tokens revert to "default" no matter what the previous "Show on Tokenbar" setting was.  While this doesn't affect me (since I want all my player tokens to show up) I think it still qualifies as a bug.  (Yes they are all set to friendly).

Steps to reproduce:

1. Open Character sheet from actors sidebar.
2. Click prototype token.
3. Change "Show on Tokenbar" to something other than "Default" (Most obvious when you choose Exclude).
4. Press Update Token to close the Prototype Token menu
5. Drag actor to canvas to make sure it worked (this is why Exclude is the most obvious)
6. Reopen Prototype Token menu
7. It did not save the exclude setting (or include) and reverts to "Default".  The previous setting is not saved.
8. If you pressed "Update Token" and did not re-choose exclude after opening (assuming that's what you chose in the first place) and left it on default, redragging the actor to canvas will spawn the actor with whatever the "default" setting is.

![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/77173822/125509642-9ed3f3dc-32f8-4111-9254-b6f65f955b95.gif)

**Comment by ironmonk88** [comment]
Prototype token should now save information.  
Technically it was saving it... but it wasn't able to show it properly.

**Comment by ironmonk88** [comment]
Also... shout out to Candlekeep Mysteries!  I've been meaning to check that out.
