### ISSUE TITLE
Suggestion: XP should respect the default setting

### ISSUE THREAD

**Issue by Ikabodo** [ironmonk88/monks-tokenbar#12]
If xp is hidden in the normal foundry settings, the button should hide on the tokenbar.

**Comment by ironmonk88** [comment]
It definitely should respect the setting.  Totally forgot that was there.  Updated the code so the button is no longer visible and the dialog won't display at the end of a combat encounter.
Will be available next patch.

**Comment by ironmonk88** [comment]
New Version is available.
Disabling XP will remove the option from the token bar as expected.
