### ISSUE TITLE
Module conflict with Chat Portraits

### ISSUE THREAD

**Issue by grankless** [ironmonk88/monks-tokenbar#120]
https://i.imgur.com/TGvzpdX.png

System: PF2e 2.9.1
Foundry: .8.8

Using the XP awarding function, it presents those big horrible shapes. This happens when the Chat Portraits function is set to either any display setting that includes the "self" option. https://i.imgur.com/XkGUMMF.png

**Comment by ironmonk88** [comment]
Closing this as it looks like a Chat Portraits issue and has been fixed.
