### ISSUE TITLE
[BUG] SWADE Error

### ISSUE THREAD

**Issue by brunocalado** [ironmonk88/monks-tokenbar#122]
win10
foundry 8.8
swade v20
chrome

This error is displayed after end a combat.
![image](https://user-images.githubusercontent.com/4999783/125857918-b834d472-edb2-4df6-8971-e0c334faeb32.png)

**Comment by ironmonk88** [comment]
The AssignXP dialog shouldn't be showing, as SWADE doesn't track XP.
Or at least I can't figure out where it's stored.
Cleaned up the code to check for showing XP properly.

**Comment by ironmonk88** [comment]
Assign XP should be removed from SWADE now.
