### ISSUE TITLE
Libwrapper: Conflict with DF-QOL

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#124]
Not sure if that's an issue. But I just notice this. 

![image](https://user-images.githubusercontent.com/44159008/126036079-ca4ab2f9-3a1c-44bc-a365-a84ed65cb22b.png)

Link to DF-QOL: https://foundryvtt.com/packages/df-qol

**Comment by ironmonk88** [comment]
Should be cleared with the latest release.
