### ISSUE TITLE
Assign XP not working in 0.8.8

### ISSUE THREAD

**Issue by whelan** [ironmonk88/monks-tokenbar#127]
I have tried to end a combat and the assign XP from the NPC's to characters is just 0 in earned XP. 

I can see in the console that something is NaN, maybe that is the problem. Also the NPC is part of the party the xP should be shared with.

**Comment by ironmonk88** [comment]
What system were you using?

**Comment by whelan** [comment]
Sorry forgot to mention that. It is dnd5e. I have not changed the configurations at all. Is there a need to do that?

**Comment by whelan** [comment]
Found out that if the token was friendly, it did not count as NPC XP. 👍
