### ISSUE TITLE
SWADE: Doubling dice rolls when requesting rolls via Tokenbar.

### ISSUE THREAD

**Issue by JasonSK22** [ironmonk88/monks-tokenbar#129]
It seems like Tokenbar and the "System" are both rolling dice for the same roll when it is requested by Tokenbar.  This will show two sets of dice when using dice so nice on the table top (scene).

**Comment by architech99** [comment]
I observed the same behavior.

System: Savage Worlds 0.20.4
Enabled Modules: Clocks, Compendium Folders, Dice So Nice, Keybind lib, libWrapper, Monk's Little Details, Monk's TokenBar, Permission Viewer, PopOut, Quick Insert - Search Widget, Savage Worlds Adventure Edition Core Rules, SWADE NPC Importer, SWADE Tools, Universal Battlemap Importer

**Comment by toddmoonbounce** [comment]
Adding a bump to this issue, seeing it in my use as well: Group Chat card and individual chat rolls as well. Double sets of 3D dice.

With that fixed, this module within SWADE is gold!

**Comment by ironmonk88** [comment]
I believe this was fixed awhile ago.  Feel free to re-open the ticket if it has not been.
