### ISSUE TITLE
[Feature Suggestion?] API access or macro support?

### ISSUE THREAD

**Issue by OpticalShadows** [ironmonk88/monks-tokenbar#13]
Is it possible to access this module via macros. For example if players are exploring an area separately and one player gets to a certain spot that triggers a trap that restricts their movement or something of the like, could there be a macro that can access the movement restriction part of the module to support this scenario? This would be like the Hey Wait! Module but only 'pauses' for that one player.

**Comment by ironmonk88** [comment]
Should be easy enough to get to.  
I'll clean up the code a bit to make it easier to understand and provide a code example when I release the next version.

**Comment by ironmonk88** [comment]
Well... that was a lot harder than I expected.  API access should be available in 1.0.16.  No documentation yet, but the functions can be accessed using game.MonksTokenBar...
In specific game.MonksTokenBar.changeMovement(movement, tokens);  Movement can be either 'free', 'none', or 'combat'.
I'll work on the documentation, but let me know if that's what you're looking for API-wise.

**Comment by ironmonk88** [comment]
Closing this as the API has been around for awhile.
