### ISSUE TITLE
Feature Request: auto resize roll window to needed size

### ISSUE THREAD

**Issue by Tupsi** [ironmonk88/monks-tokenbar#131]
It seems my bard has more skills then you had anticipated. While there is a slider to move the inner window options around, it would be nice to always see everything at once (without the need to "scroll down").

![image](https://user-images.githubusercontent.com/3730499/126949523-5ea72d1e-0e3c-4005-872f-6d04f8808b75.png)

**Comment by ironmonk88** [comment]
This should be available in the latest release.
