### ISSUE TITLE
No tokenbar appears on Old-School Essentials

### ISSUE THREAD

**Issue by Tycedi** [ironmonk88/monks-tokenbar#135]
It seems that no token-bar appears on the Old-School Essentials game system. I've tried a couple of other game systems (Burning wheel, One Ring, 5e, etc) and the bar appears no problem. I'm wondering if support to Old-School Essentials could possibly be added or if there is something specific to that system that breaks this module. 

This module is exactly what I need for token management and to restrict the movement of some key players ;)

**Comment by ironmonk88** [comment]
That is an error.
Fixed and new release is available that should fix that.

**Comment by Tycedi** [comment]
Yup! works great now! thanks!
