### ISSUE TITLE
Feature Request: Relocate Bar

### ISSUE THREAD

**Issue by DivertedCircle** [ironmonk88/monks-tokenbar#14]
Love the bar but I'd love it even more if I could relocate it, either by dragging it or through the module settings.

**Comment by ironmonk88** [comment]
I was considering that when developing.  For those with small monitors or large parties it could pose an issue.
Added a small handle on the left side so that it can be re positioned.
Expect it in the next release.

**Comment by ironmonk88** [comment]
Version 1.0.9 released, this should be available now.
