### ISSUE TITLE
Allow overriding "Save DC ..." button behavior from chat message

### ISSUE THREAD

**Issue by happy-cujo** [ironmonk88/monks-tokenbar#145]
Default core behavior is to roll the saving throw for each selected token which results in:
![obraz](https://user-images.githubusercontent.com/15898113/129634238-c11b2828-ee9c-41f7-92a7-be39a995b45d.png)

That's a quite a spam in chat if more that one tokens are selected (targeted).

The idea is to plug-in and add an option to override default behavior so that after selecting tokens and pressing "Save DC ..." you end up with:
![obraz](https://user-images.githubusercontent.com/15898113/129634489-642fc9bc-1eb1-495b-be6a-71eb9ad5d60c.png)

This could fit nicely with #143.

Edit. Example of the same behavior, but embedded into chat card that had the "Save DC" button. 
![obraz](https://user-images.githubusercontent.com/15898113/134787103-9e9af722-c9fb-4222-8972-b6e44f35aee1.png)

**Comment by ironmonk88** [comment]
Should be available in the latest version.
You'll have to turn it on in the settings though.
