### ISSUE TITLE
Token Bar Actor Selection

### ISSUE THREAD

**Issue by QuestionQuest117** [ironmonk88/monks-tokenbar#147]
Currently having an issue where my player's characters are not appearing on the token bar, so I don't have easy access to their AC and such. It works on the first map I used with Foundry, but not any of the others. I tried deleting the characters from that first map and replacing the PCs on the second map, but that did not fix it. What do I do to get the icons to appear for maps and such? Can a feature be added so that the menu can have PCs manually added in case of a glitch?
![Capture](https://user-images.githubusercontent.com/54755301/130339373-749fda8c-80d9-4250-9ee6-d6895bac1a00.PNG)
As you can see, there are player characters on the map, but no tokens on the token bar.

**Comment by ironmonk88** [comment]
Make sure the token has a friendly disposition.
And then if that doesn't work, change them to be on the tokenbar.

![image](https://user-images.githubusercontent.com/75920956/130339693-0faa3a53-b418-4e6a-83b0-1393c4c9b52a.png)

**Comment by QuestionQuest117** [comment]
> Make sure the token has a friendly disposition.
> And then if that doesn't work, change them to be on the tokenbar.
> 
> ![image](https://user-images.githubusercontent.com/75920956/130339693-0faa3a53-b418-4e6a-83b0-1393c4c9b52a.png)

Thank you! That fixed it. I didn't realize that mattered
