### ISSUE TITLE
Add options for scaling the portrait/token image size and allow to view party members

### ISSUE THREAD

**Issue by LorduFreeman** [ironmonk88/monks-tokenbar#148]
Would be great if you could view the tokens/portraits of other party members (based on permission level, maybe observer?) and to be able to scale the image size up or down.

**Comment by ironmonk88** [comment]
Added option to view other tokens if you have observer permissions.
For various reasons changing the size of the image is problematic.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
