### ISSUE TITLE
Hook debug left enabled

### ISSUE THREAD

**Issue by BlitzKraig** [ironmonk88/monks-tokenbar#15]
https://github.com/ironmonk88/monks-tokenbar/blob/070da3235b9c1fcea35059d125c4643b2c68b2b0/monks-tokenbar.js#L26

`CONFIG.debug.hooks = true` left in release

**Comment by ironmonk88** [comment]
Well, that's embarrassing.  Just released a new version with updates.  Made sure that was commented out properly.

**Comment by BlitzKraig** [comment]
It happens! Thanks, and good work on the modules
