### ISSUE TITLE
[Bug] Uncaught TypeError

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#153]
Versions:
Everything is up to date (stable)
I disabled the modules shown in the error one after the other. But the error was still present.

When I activate a scene from the top quick access I get this error. Sometimes it appears (around 95%) and sometimes it does not.
The only effect it seems to have, that in about 60-70% of the cases the player tokens (and only player tokens not NPC tokens) are not visible anymore. Reloading the page solves the issue for that scene once. When switching back and forth - it happens again. 

![image](https://user-images.githubusercontent.com/44159008/135479909-b292eb6a-527f-4cc3-afe3-83472b0c1101.png)

Here I am switching a couple of times from scene to scene.

https://user-images.githubusercontent.com/44159008/135481827-d1eee250-74b8-40ba-9a03-98c9e099880f.mp4

I put it here because "find the culprit" said it's because of this module. And it seems to be gone after disabling the module.

**Comment by ironmonk88** [comment]
That took awhile to track down.  And I think it's a strange issue with Foundry.  Essentially, I was saving a token flag on canvas refresh, and I think the timing must have thrown Foundry off, in that it didn't complete the save before a new set of tokens replaced the current ones.  So when the save completed and it went to refresh the token in question (that no longer existed) it got very confused and something got messed up.  That's my best guess.
I've removed the offending line and I'll see how much of an impact it has.

**Comment by tagnullde** [comment]
Wow. I appreciate your effort on tracking that one down.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
