### ISSUE TITLE
[Suggestion] Allow changing direction tokens appear in.

### ISSUE THREAD

**Issue by Brimcon** [ironmonk88/monks-tokenbar#154]
I think it would be cool to have the tokens to be going 'downwards' instead of to the right. You could also have an option for going 'upwards'
![image](https://user-images.githubusercontent.com/7198283/135536435-d09ba185-4c4c-4716-942c-b76189e13365.png)
A good use for this would be here, putting all tokens flush against the left controls, similar to how Solasta has their player UI set up or various other games that do similar things.

**Comment by ironmonk88** [comment]
The option for vertical alignment has been added.
