### ISSUE TITLE
Feature Request - Customise the 'Auto Gold by CR' loot value

### ISSUE THREAD

**Issue by nirurin** [ironmonk88/monks-tokenbar#156]
I like that you can auto-populate the loot field for gold by an automatically calculated amount based on the enemy CR rating...however I think the amounts of gold being given are too high (for my campaign at least!)

I'd love it if you could customise it somehow, even if it was a percentage. I'd proably drop it to 25% or 10% of what it is now. 

Edit: Is there a way for me to do this? Otherwise I can do it manually, but I much prefer the automated solution.

**Comment by ironmonk88** [comment]
So I've moved the loot formula into the settings.  This should let anyone determine how they want gold to be calculated.
It uses handlebar formatting, so you can get access to the Character's data by wrapping it in {{ }}.

**Comment by CaosFR** [comment]
Hi,

May it's possible to give other currency than gold ? Gold it's very to mush for a low CR.

Thanks

**Comment by ironmonk88** [comment]
Current lootables will let you set individual currency so if gold is too much, you can use that interface to set those values.
