### ISSUE TITLE
Issues with tokens not being deleted

### ISSUE THREAD

**Issue by amcvfx** [ironmonk88/monks-tokenbar#16]
I've had some issues with player tokens not deleting from scenes with the Token Bar module on. I think this may be a clash with The Furnace module, in particular when a folder of tokens is dragged into a map. I use this function to bring PC tokens onto a map but when Tokenbar is also active 2-3 of the 5 tokens dragged on seem to not delete. They also don't move correctly on the map, popping back into their default position when moved.

**Comment by ironmonk88** [comment]
That is odd.  Think it has to do with the number of tokens all being added or deleted at once.  TokenBar expects one at a time, and tries to refresh each time.  I'll look to modify the code so that it only refreshes once per batch.

**Comment by ironmonk88** [comment]
Looks like that fixed the issue.  Expect the update in the next release.

**Comment by ironmonk88** [comment]
Version 1.0.9 released, this should be fixed now.
