### ISSUE TITLE
Request roll not working for player

### ISSUE THREAD

**Issue by JJBocanegra** [ironmonk88/monks-tokenbar#17]
With just this module installed, I request a player to make a roll from this module and when he clicks the chat roll dice, it do nothing and and error appears in console.

Here is a video:
![monk-token](https://user-images.githubusercontent.com/5797636/106457022-a289b700-648e-11eb-8afc-66e93cc3290f.gif)

**Comment by ironmonk88** [comment]
Thank you for catching that.  Upgraded some code, but it ended up breaking the players part.  Version 1.0.8 is out.  Directly fixes that issue.
