### ISSUE TITLE
Feature suggestion: Manipulate rolls

### ISSUE THREAD

**Issue by Ikabodo** [ironmonk88/monks-tokenbar#170]
It would be cool if it was possible to inject more info into a chat-card when it is being sent. 

The idea being that you could add an option to something like this: {"text":"<b>Thing:</b>This is a roll that defines something that is happening."}

Then inject it somewhere, depending on what message it is. In this case the contested roll.
![image](https://user-images.githubusercontent.com/7766890/142482052-fcb1f592-f794-4611-8716-d00d17b830d9.png)

**Comment by thatlonelybugbear** [comment]
Maybe this <https://github.com/ironmonk88/monks-tokenbar/pull/171> will do what you want.

You could then insert a text in the request options as flavor for the Message Card.

For instance: `game.MonksTokenBar.requestRoll(tokens,{request:'skill:prc', silent: true, fastForward: true, dc: 15, rollmode: "",flavor: "Let's see what I see"})`

will create this message

![image](https://user-images.githubusercontent.com/7237090/143051632-fd58f127-4a91-4f91-992a-41346367a48e.png)

**Comment by ironmonk88** [comment]
Closing this as flavor text is what you're looking for and has been added to the module.
