### ISSUE TITLE
Tokenbar disappear when i click on a scene in the navigation scene bar

### ISSUE THREAD

**Issue by Ivonilsonx** [ironmonk88/monks-tokenbar#174]
Disabled all modules but Tokenbar to test and it really isnt a compatibility issue, when i click on a scene in the navigation scene bar the tokenbar disappears and only appears again if i reload the application

**Comment by ironmonk88** [comment]
Are you using the browser or stand alone? 
What system are you using? 
Are there any errors in the console log?

**Comment by Ivonilsonx** [comment]
> Are you using the browser or stand alone? What system are you using? Are there any errors in the console log?

- I'm using the windows app
- Windows 10 64bits
- I don't know how to check that

**Comment by ironmonk88** [comment]
Closing this as it's really old, and the code has changed significantly since it was added.
If it's still an issue, feel free to re-open the ticket.
