### ISSUE TITLE
 Feature suggestion: button to hide the bar

### ISSUE THREAD

**Issue by altair984** [ironmonk88/monks-tokenbar#176]
I think it would be a very good option to be able to hide and show the bar when needed. That way you can have the bar in some scenes in sight and in other scenes that you don't need it you can hide it in an easy and comfortable way. It occurs to me that you can add a control button in the system sidebar to add this option and even (this is something else) options of your other modules if you have them installed. I think it would be a wonderful addition. I look forward to your reply, best regards and thank you very much for your work. Your modules are a marvel to be able to enjoy FoundryVTT much better.

**Comment by ironmonk88** [comment]
Closing this as the option to minimize the tokenbar was added awhile ago.
