### ISSUE TITLE
Grabing a roll only works if player is present in scene

### ISSUE THREAD

**Issue by Tupsi** [ironmonk88/monks-tokenbar#179]
If the player who is manully rolling the save and you is on a different scene then from where the GM requested it, the GM is unable to grab the roll. Works fine if the player moves over to the same scene and rerolls his save and GM grabs the 2nd roll now.

Not sure if you intended this and it is a feature or not and that it is actually a bug, so I thought I report it.

**Comment by ironmonk88** [comment]
Closing this as Better Roles 5e is no longer being updated
