### ISSUE TITLE
i18n enhancements on templates

### ISSUE THREAD

**Issue by hmqgg** [ironmonk88/monks-tokenbar#18]
There are some non-i18n strings on HTML templates e.g.:
https://github.com/ironmonk88/monks-tokenbar/blob/7bfc5e75df77a4ae0e823c795e99dbfdf4390a7b/templates/assignxpchatmsg.html#L16
https://github.com/ironmonk88/monks-tokenbar/blob/7bfc5e75df77a4ae0e823c795e99dbfdf4390a7b/templates/assignxpchatmsg.html#L33

I18n those strings will improve the module localization.

**Comment by ironmonk88** [comment]
There are 5 other strings needed.

"MonksTokenBar.RollResult": "Roll Result",
	"MonksTokenBar.RollPassed": "Roll Passed",
	"MonksTokenBar.RollFailed": "Roll Failed",
	"MonksTokenBar.Passed": "Passed",
	"MonksTokenBar.Failed": "Failed"

Otherwise I've made the updates and will post in the next few days.

**Comment by hmqgg** [comment]
> There are 5 other strings needed.
> 
> "MonksTokenBar.RollResult": "Roll Result",
> "MonksTokenBar.RollPassed": "Roll Passed",
> "MonksTokenBar.RollFailed": "Roll Failed",
> "MonksTokenBar.Passed": "Passed",
> "MonksTokenBar.Failed": "Failed"
> 
> Otherwise I've made the updates and will post in the next few days.

Added.
