### ISSUE TITLE
Foundry v9: Cannot select a custom icon when editing stats

### ISSUE THREAD

**Issue by caewok** [ironmonk88/monks-tokenbar#181]
Foundry v9.235, dnd 1.5.5, Monk's tokenbar 1.0.55. In the Edit Stats dialog, if I try to add a stat and then change the custom icon, I am unable to select the icon and I see this error in the console:

```js
editstats.js:79 Uncaught TypeError: Cannot set properties of undefined (setting 'icon')
[Detected 1 package: monks-tokenbar]
    at EditStats.selectIcon (editstats.js:79:19)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at HTMLDivElement.v.handle (jquery.min.js:2:41048)
```

Good news is that most of the rest appears to be working! Thanks!

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
