### ISSUE TITLE
Foundry v8: Error in log for savingthrow.js

### ISSUE THREAD

**Issue by Tupsi** [ironmonk88/monks-tokenbar#184]
Loading the world throws this in the console.

```
savingthrow.js:742 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'actor')
[Detected 1 package: monks-tokenbar]
    at savingthrow.js:742

```
![image](https://user-images.githubusercontent.com/3730499/145709571-377f4cab-7dd2-4bd8-9697-a7e63fa73b66.png)

**Comment by tposney** [comment]
It looks like your chat log holds a reference to a token that has been removed from the game. This can be confirmed by clearing the chatlog and seeing if the error goes away.

**Comment by Tupsi** [comment]
couldnt replicate the issue this week, so I am closing this.
