### ISSUE TITLE
Sound of dice cannot be turned off

### ISSUE THREAD

**Issue by MN88** [ironmonk88/monks-tokenbar#186]
even with modules otherwise able to  turn of dice roll sounds such as Squeaker and Dice so Nice, roll sounds is still present using the tokenbar. Im using it with MIDI QOL, and tposney confirmed the tokenbar to be the issue.

**Comment by ironmonk88** [comment]
I believe this was fixed awhile ago.
Feel free to open the ticket again if this is still an issue.
