### ISSUE TITLE
Bug convert lootable (lootsheetNPC5e >=v3.3.81)

### ISSUE THREAD

**Issue by DanielBoettner** [ironmonk88/monks-tokenbar#187]
https://github.com/jopeek/fvtt-loot-sheet-npc-5e/issues/219

> **Describe the bug** When using monk's token bar to convert to lootables, conversion seems to fail.
> 
> **To Reproduce** When using monk's token bar to convert to lootables, conversion seems to fail.
> 
> 1. Highlight token and click "convert lootables" on the left side of the screen (from monk's token bar)
> 2. Notice that the sheet still look the same as a standard npc sheet even though the token looks like a lootable token.
> 3. Press 'revert lootable' from the top of the sheet.  All looks well.
> 4. Change the sheet manually to the lootsheet.
> 5. You cannot open the sheet any longer.
> 
> ```
> 
> > TypeError: Cannot read properties of null (reading 'value')
> > [Detected 1 package: lootsheetnpc5e]
> >     at LootSheetNPC5eHelper.js:51
> >     at Array.map (<anonymous>)
> >     at Function.convertCurrencyFromObject (LootSheetNPC5eHelper.js:50)
> >     at LootSheetNPC5e._prepareGMSettings (LootsheetNPC5e.js:789)
> >     at LootSheetNPC5e.getData (LootsheetNPC5e.js:68)
> >     at async LootSheetNPC5e._render (foundry.js:2049)
> >     at async LootSheetNPC5e._render (foundry.js:2736)
> > (anonymous) @ foundry.js:2013
> > Promise.catch (async)
> > render @ foundry.js:2011
> > render @ foundry.js:3231
> > EntitySheetConfig._updateObject @ monks-enhanced-journal.js:495
> > await in EntitySheetConfig._updateObject (async)
> > _onSubmit @ foundry.js:2825
> ```

**Comment by DanielBoettner** [comment]
My first answer to that issue.

> On first glance. I think this will be a won't fix.
> 
> The module now offers a direct [API ](https://github.com/DanielBoettner/fvtt-loot-sheet-npc-5e/wiki/Permissions)to convert a token to a lootableSheet.
> 
> With the module you can find a compendium with macros. One macro for converting a single token. A second macro to convert a selection of tokens.
> 
> The macros bascially do what the example in the wiki does.
> 
> I have to check if I already included a way to set the permissions to a specific type. Default is "Observer" so players can loot.

Please let me know if you think if you agree. Or if you think that could be a bug that needs to be fixed in the lootsheet.

I see `monks-enhanced-journal.js` in the error.
So maybe you do even more stuff on conversions? Or is this unrelated?
If so maybe an update for the API method would be the best way to get support for your your data and conversion back.

**Comment by ironmonk88** [comment]
Closing this as it's a really old bug and the issue it refers to has been closed.
There's been a fair amount of work done to fix the lootables code, so it's probably been fixed.
