### ISSUE TITLE
V9 issue, PCs do not appear on TokenBar

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-tokenbar#189]
PCs do not appear on TokenBar but they are available to Request Roll if they are selected.

**Comment by Hyrkanus** [comment]
When I had the problem of PC's not appearing (in DnD 3.5E) I could solve it by setting the player's tokens from "hostile" to "friendly". (For whatever reason they were set to hostile)

**Comment by supernovajm** [comment]
I am having the same problem (in SFRPG). tokens are marked as friendly, but I can only bring them into Request Roll if they are selected.

**Comment by ironmonk88** [comment]
I believe this should be fixed.
But if it's not, please check that the token is friendly and owned by a player.
And if that doesn't work then you can set them manually to be included.
