### ISSUE TITLE
[Bug] [v9] "Convert to Lootable" does not switch sheet to LootSheetNPC5e

### ISSUE THREAD

**Issue by NateHawk85** [ironmonk88/monks-tokenbar#191]
Foundry version: v9 238
DnD5e version: 1.5.6
Modules enabled: Monk's Tokenbar v1.0.57 | Loot Sheet NPC 5e v3.4.1
Monk's Tokenbar settings: defaults, "Convert enemies to lootable" --> Loot Sheet NPC 5e

Expected behavior: After combat and/or after clicking the menu item to convert NPCs to lootables, I expect the NPC sheet to swap to LootSheetNPC5e instead of remaining on their "default" sheet option.
Actual behavior: Sheet remains as "Default Sheet"

Steps to reproduce:
1) Add NPC to canvas
2) Navigate to the "Convert to Lootable" menu, either by the menu option on the left or by starting combat, reducing the enemy to 0hp/applying the death status, then finishing combat. Clicking the "Assign gold by CR" checkbox does not appear to make a difference in this (though it does update the gold accordingly)
![image](https://user-images.githubusercontent.com/7596412/147770271-7f137f52-d59f-4995-b736-61c57c093f59.png)
3) The "lootable" overlay appears on the token, as expected.
![image](https://user-images.githubusercontent.com/7596412/147770299-a51f3395-5105-4b4d-a090-c0d901f5e01c.png)
However, the NPC token's sheet still remains as the "Default Sheet" instead of switching over to the "LootSheetNPC5e" sheet. That being said, the "Revert Lootable" button appears as if the sheet were converted to "LootSheetNPC5e"
![image](https://user-images.githubusercontent.com/7596412/147770407-ca80059b-6c8d-48f1-a9da-68d169d1972f.png)
Clicking on this sheet from a PC's point of view opens the sheet as if the entire sheet was observable
![image](https://user-images.githubusercontent.com/7596412/147770457-7ac97238-2f58-4ae4-8252-f17b96727c60.png)
What I would expect to see from a PC perspective is something like the following:
![image](https://user-images.githubusercontent.com/7596412/147770784-0846a1fc-4a55-46fd-8b2a-56b09a4bba95.png)

Apologies if this is an issue on LootSheetNPC5e's end instead of yours! But also, thank you very much for all the work you've done on your modules. I use quite a few in my Foundry games, and they all provide such amazing quality-of-life fixes that I can't imagine my games without them :)

**Comment by ironmonk88** [comment]
I believe this was an issue that LootSheet changed the sheet name.
Should be fixed in the latest version.
