### ISSUE TITLE
Error when trying to remove the "vs" Actor during contested roll

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#196]
As per topic.

Foundry Virtual Tabletop: Version 9, 9.242
Game System: dnd5e, 1.5.6

OS: Ubuntu 21.10
Client: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
GPU: ANGLE (Intel, Mesa Intel(R) HD Graphics 530 (SKL GT2), OpenGL 4.6 (Core Profile) Mesa 21.2.2)
Max Texture Size: 16384

![image](https://user-images.githubusercontent.com/44159008/148839973-4f09f393-09c2-48e8-a534-8cc4fdda695a.png)

![Peek 2022-01-10 22-12](https://user-images.githubusercontent.com/44159008/148840170-b9e81573-42f6-4295-9963-3b89f31009d1.gif)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
