### ISSUE TITLE
Can't make a saving Throw. Allways prompt error message "Could not find function to roll"

### ISSUE THREAD

**Issue by Larend** [ironmonk88/monks-tokenbar#198]
`monks-tokenbar.js:25 monks-tokenbar |  create chat request
foundry.js:5104 game.data.version is deprecated since V9 in favor of game.version
get @ foundry.js:5104
getFoundryVersion @ utils.js:84
isAfterFoundry8 @ utils.js:93
(anonymous) @ chat-images.js:19
_call @ foundry.js:294
call @ foundry.js:279
_preCreateDocumentArray @ foundry.js:9958
backend.mjs:306 Foundry VTT | Created ChatMessage with id [GQyi5EaZtalwIUnt]
monks-tokenbar.js:25 monks-tokenbar |  Rendering chat message ChatMessage
foundry.js:63049 Foundry VTT | Loading audio element - modules/monks-tokenbar/sounds/RollRequestAlert.ogg
monks-tokenbar.js:25 monks-tokenbar |  roll all finished Array(6)
monks-tokenbar.js:25 monks-tokenbar |  updating actor Object undefined
monks-tokenbar.js:25 monks-tokenbar |  updating actor Object undefined
monks-tokenbar.js:25 monks-tokenbar |  updating actor Object undefined
monks-tokenbar.js:25 monks-tokenbar |  updating actor Object undefined
monks-tokenbar.js:25 monks-tokenbar |  updating actor Object undefined
monks-tokenbar.js:25 monks-tokenbar |  updating actor Object undefined
monks-tokenbar.js:25 monks-tokenbar |  Rendering chat message ChatMessage
foundry.js:63023 Foundry VTT | Loading audio buffer - modules/monks-tokenbar/sounds/RollRequestAlert.ogg
foundry.js:63006 Foundry VTT | Constructing audio buffer source node - modules/monks-tokenbar/sounds/RollRequestAlert.ogg
foundry.js:3050 Foundry VTT | Rendering SavingThrowApp
monks-tokenbar.js:25 monks-tokenbar |  create chat request
foundry.js:5104 game.data.version is deprecated since V9 in favor of game.version
get @ foundry.js:5104
getFoundryVersion @ utils.js:84
isAfterFoundry8 @ utils.js:93
(anonymous) @ chat-images.js:19
_call @ foundry.js:294
call @ foundry.js:279
_preCreateDocumentArray @ foundry.js:9958
await in _preCreateDocumentArray (async)
_createDocuments @ foundry.js:9875
create @ backend.mjs:96
await in create (async)
createDocuments @ document.mjs:338
create @ document.mjs:439
requestRoll @ savingthrow.js:224
await in requestRoll (async)
i @ jquery.min.js:2
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
backend.mjs:306 Foundry VTT | Created ChatMessage with id [yqO22M374uvOJOYB]
monks-tokenbar.js:25 monks-tokenbar |  Rendering chat message ChatMessage {apps: {…}, _sheet: null, _roll: null, _rollExpanded: false, parent: null, …}apps: {}mtb_callback: undefined_roll: null_rollExpanded: false_sheet: nulldata: ChatMessageData {_id: 'yqO22M374uvOJOYB', type: 0, user: 'eJa073QcW0yfXYiS', timestamp: 1642760550720, flavor: undefined, …}pack: nullparent: nullalias: "Jose2"collection: Messages(10)collectionName: "messages"compendium: undefineddocumentName: "ChatMessage"folder: nullhasPlayerOwner: falseid: "yqO22M374uvOJOYB"isAuthor: trueisContentVisible: trueisEmbedded: falseisOwner: trueisRoll: (...)limited: (...)link: (...)name: (...)permission: (...)roll: (...)sheet: (...)user: (...)uuid: (...)visible: (...)[[Prototype]]: BaseChatMessagealias: (...)applyRollMode: ƒ applyRollMode(rollMode)constructor: class ChatMessageexport: export() {     let content = [];      // Handle Roll content     if ( this.isRoll ) {       let r = this.roll;       if ( this.data.content && (this.data.content !== "undefined")) {         content.push($(`<div>${this.data.content}</div>`).text().trim());       }       let flavor = this.data.flavor;       if ( flavor && flavor !== r.formula ) content.push(flavor);       content.push(`${r.formula} = ${r.result} = ${r.total}`);     }      // Handle HTML content     else {       const html = $("<article>").html(this.data["content"].replace(/<\/div>/g, "</div>|n"));       const text = html.length ? html.text() : this.data["content"];       const lines = text.replace(/\n/g, "").split("  ").filter(p => {…}getHTML: async getHTML() {      // Determine some metadata     const data = this.toObject(false);     const isWhisper = this.data.whisper.length;      // Construct message data     const messageData = {       message: data,       user: game.user,       author: this.user,       alias: this.alias,       cssClass: [         this.data.type === CONST.CHAT_MESSAGE_TYPES.IC ? "ic" : null,         this.data.type === CONST.CHAT_MESSAGE_TYPES.EMOTE ? "emote" : null,         isWhisper ? "whisper" : null,         this.data.blind ? "blind": null       ].filterJoin(" "),       isWhisper: this.data.whisper.some(id => {…}getRollData: ƒ getRollData()isAuthor: (...)isContentVisible: (...)isRoll: (...)prepareData: ƒ prepareData()roll: (...)user: (...)visible: (...)_onCreate: ƒ _onCreate(data, options, userId)_onDelete: ƒ _onDelete(options, userId)length: 2name: "_onDelete"arguments: (...)caller: (...)[[FunctionLocation]]: foundry.js:15260[[Prototype]]: ƒ ()[[Scopes]]: Scopes[3]_onUpdate: ƒ _onUpdate(data, options, userId)_preCreate: ƒ async _preCreate(data, options, user)_renderRollContent: ƒ async _renderRollContent(messageData)collection: (...)collectionName: (...)compendium: (...)documentName: (...)folder: (...)hasPlayerOwner: (...)id: (...)isEmbedded: (...)isOwner: (...)limited: (...)link: (...)name: (...)permission: (...)sheet: (...)uuid: (...)get alias: ƒ alias()get isAuthor: ƒ isAuthor()get isContentVisible: ƒ isContentVisible()get isRoll: ƒ isRoll()get roll: ƒ roll()get user: ƒ user()get visible: ƒ visible()[[Prototype]]: BaseChatMessage
monks-tokenbar.js:25 monks-tokenbar |  roll all finished [{…}]0: error: trueid: "lxV1AWNiUPBqfxV5"msg: ": Could not find function to roll"[[Prototype]]: Objectlength: 1[[Prototype]]: Array(0)
monks-tokenbar.js:25 monks-tokenbar |  updating actor {id: 'lxV1AWNiUPBqfxV5', uuid: 'Scene.Eao3vWcMOsXogojJ.Token.lxV1AWNiUPBqfxV5', actorid: 'HIHITg0k17PPIw5L', icon: '00079.token.png?1642692743206', name: 'Pepe'} undefined
monks-tokenbar.js:25 monks-tokenbar |  Rendering chat message ChatMessage {apps: {…}, _sheet: null, _roll: null, _rollExpanded: false, mtb_callback: undefined, …}`

**Comment by thejoester** [comment]
I am also getting this error in the PF2E system when asking for a perception roll. 

`monks-tokenbar |  Rendering chat message 
Object { type: 0, timestamp: 1690196305669, flavor: "", content: `<div class="monks-tokenbar savingthrow chat-card">\n    <header class="card-header flexrow">\n        <h3 class="item-name noborder">Perception Check</h3>\n    </header>\n    <div class="message-content" style="margin:5px 0px">\n        <div class="card-content"></div>\n\t    <div class="form-group sheet actor">\n            <ol class="items-list inventory-list">\n                <li class="items-header flexrow">\n                    <h3 class="item-name noborder flexrow">Actors</h3>\n\n                    <div class="item-controls flexrow">\n                        <a class="item-control roll-all gm-only" title="Roll All" data-control="all">\n                            <i class="fas fa-users"></i>\n                        </a>\n                        <a class="item-control roll-npc gm-only" title="Roll NPCs" data-control="npc">\n                            <i class="fas fa-users-cog"></i>\n                        </a>\n                    </div>\n                </li>\n\n                <ol class="item-list">\n                    <li class="item flexcol" data-item-id="kC90vTcM6aolTVHN" style="display:none">\n                        <div class="flexrow token-roll-container">\n                            <div class="dice-roll flexcol">\n                                <div class="item-row flexrow">\n                                    <div class="item-name flexrow">\n                                        <div class="item-image" style="background-image:url('assets/tokens/Meridith-Hollyleaf-token.webp')"></div>\n                                        <h4 class="noselect">\n                                            Meredith Hollyleaf\n                                        </h4>\n                                    </div>\n\n                                    <div class="roll-controls flexrow">\n                                        \n                                    <div class="dice-total flexrow noselect" style="display:none"><div class="dice-result">Error!</div></div></div>\n                                </div>\n                            </div>\n                        </div>\n                        <div class="token-properties"></div>\n                    </li>\n                </ol>\n            </ol>\n        </div>\n    </div>\n    <footer class="card-footer gm-only flexcol">\n        <div class="flexrow" style="justify-content:flex-end">\n            <button type="button" class="select-all footer-button" title="Select All Actors"><i class="fas fa-users"></i></button>\n            <button type="button" class="select-saved footer-button" title="Select Saved Actors"><i class="fas fa-user-check"></i></button>\n            <button type="button" class="select-failed footer-button" title="Select Failed Actors"><i class="fas fa-user-times"></i></button>\n            \n        </div>\n        <div style="overflow:hidden;white-space:nowrap">\n            <span class="message-mode">Private Roll, Results Hidden</span><span> Group DC: <span class="group-dc"></span></span>\n        </div>\n    </footer>\n</div>`, speaker: {…}, whisper: (2) […], blind: false, rolls: [], sound: undefined, emote: false, … }
[monks-tokenbar.js:27:39](http://thejoester.ddns.net:30000/modules/monks-tokenbar/monks-tokenbar.js)
monks-tokenbar |  roll all finished 
Array [ {…} ]
[monks-tokenbar.js:27:39](http://thejoester.ddns.net:30000/modules/monks-tokenbar/monks-tokenbar.js)
monks-tokenbar |  updating actor 
Object { id: "kC90vTcM6aolTVHN", uuid: "Scene.a2OXxRpLXbLU0IAF.Token.kC90vTcM6aolTVHN", actorid: "2p89MUYOIcvlGhBQ", icon: "assets/tokens/Meridith-Hollyleaf-token.webp", name: "Meredith Hollyleaf", keys: {}, reveal: true, error: true }
 undefined [monks-tokenbar.js:27:39](http://thejoester.ddns.net:30000/modules/monks-tokenbar/monks-tokenbar.js)
Meredith Hollyleaf: Meredith Hollyleaf: Could not find function to roll`

**Comment by ironmonk88** [comment]
Closing this ticket as it's really old, I can no longer replicate it, and I'm sure the code has changed significantly since then.
