### ISSUE TITLE
Add support for Item Piles lootables

### ISSUE THREAD

**Issue by thre-z** [ironmonk88/monks-tokenbar#199]
I'd like to request support for the Lootables function to include the Item Piles module in addition to the Lootsheet module. 

The module has a convenient API for converting and reverting item piles:

```js
ItemPiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled, { pileSettings: { displayOne: false })
```

```js
ItemPiles.API.revertTokensFromItemPiles(canvas.tokens.controlled)
```

API reference: https://github.com/fantasycalendar/FoundryVTT-ItemPiles/wiki

**Comment by ironmonk88** [comment]
Item Piles should be integrated in the latest version.
