### ISSUE TITLE
Lock Move not lock

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-tokenbar#2]
even setting "No movment" the players continue to move (in and out of combat)

**Comment by ironmonk88** [comment]
What version of the TokenBar are you using?  This was an issue with the 1.0.2 but was corrected with 1.0.3

**Comment by rinnocenti** [comment]
in 1.0.5

**Comment by ironmonk88** [comment]
Keys moving the tokens were an issue fixed in 1.0.6.  Just released.
