### ISSUE TITLE
[Bug] Blood splatters only add/remove inside combat - outside of combat they glitch. 

### ISSUE THREAD

**Issue by nirurin** [ironmonk88/monks-tokenbar#200]
Blood splatters seem to be added/removed inside of a combat as expected. 

However if an enemy dies in combat, and then I give them health back outside of combat for some reason, the actor remains invisible and the blood splatter stays there, even though the creature now has health and so should be alive again. 

Not a major bug, as bringing creatures back to life is fairly niche, but thought I'd mention it as I doubt its intentional!

**Comment by ironmonk88** [comment]
Closing this as it's not really a Tokenbar issue.
Bloodsplats displays based on if the token has the defeated or dead status.  So you can heal something to full health... but if it still has the Dead status, then it will show as a blood splat.
So if the bloodpslat is still showing, then there's a status on the token that needs to be cleared first.
