### ISSUE TITLE
[FEATURE] Save to Macros (reference Actor instead of Token)

### ISSUE THREAD

**Issue by pereiraoc** [ironmonk88/monks-tokenbar#202]
Hello!

It would be nice if the macro for the roll request could reference the Actor instead of a token.
That way, the macro wouldn't be useless whenever a new token of the same actor is generated.

If possible, please allow the creation of macros that can "Request"/"Request with Roll" without poping the "Request Roll" window.

GREAT WORK MAN, THANKS A LOT!!!!!

**Comment by ironmonk88** [comment]
Unfortunately referencing the Actor is tricky, since the Tokenbar works off of tokens.
But I've changed it to working off the token name, which should be a little more consistent.

If you want the macro to not pop up the Request Roll window, just change the silent, and fastForward flags.
