### ISSUE TITLE
Issue with Monk's TokenBar and Compact Roll Card DnD5e

### ISSUE THREAD

**Issue by nulmas** [ironmonk88/monks-tokenbar#205]
There's a compatibility issue between Monk's TokenBar and Compact Roll Card DnD5e. When clicking on the roll result to check what came up on the dice, the window showing the dice result will almost fill the entire screen.

Here are some screenshots showing what happens.

1. Before clicking on the result.
![1](https://user-images.githubusercontent.com/79886727/153021335-c484d198-3b1a-4498-a8e9-b27f04dcbb01.jpg)

2. The intended behavior (only Monk's TokenBar active)
![2](https://user-images.githubusercontent.com/79886727/153021364-ea7cc2fe-17a2-43b6-8b5d-6d9e80b82646.jpg)

3. The issue when both modules are active.
![3](https://user-images.githubusercontent.com/79886727/153021393-908fb23f-77cd-41cb-93c4-4d4b69cce2c5.jpg)

I'm also posting this on [Compact Roll Card DnD5e's issue list](https://github.com/ElfFriend-DnD/foundryvtt-compact-roll-card-5e/issues/2)

**Comment by ironmonk88** [comment]
Closing this, as it's old and an experimental unreleased module.
