### ISSUE TITLE
Private Message to User with "whitespace"

### ISSUE THREAD

**Issue by eccobold** [ironmonk88/monks-tokenbar#207]
If there is a user with a whitespace in his username, the name has to be in [ ... ] in the /w command. 

![image](https://user-images.githubusercontent.com/71939920/153768171-856de4aa-6873-48bc-8e8b-3c875bfd5209.png)

/w [Than Thungrim] Greeting my old friend

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
Thank you for finding this.
