### ISSUE TITLE
Stats on the token bar re-ordering

### ISSUE THREAD

**Issue by maxobremer** [ironmonk88/monks-tokenbar#209]
Would it be possible to allow the stats to be easily reordered in any matter? I have some stats that I want to have at the bottom of the list so that all health and ac stats for my players are on the same line, but for someone with a weird outlying stat I might want that to be at the top like a resource linked to meta magic, which a sorcerer has but a rogue doesnt really use a resource. when I add a new stat its added to the bottom and i have to remove and re-add the existing stats to get them at the bottom of the list.

also would it be possible to have a search bar in the icon selection field as its quite hard to find the right icon among the dozens of them.
also good work on this module so far!

kind regards,

Max

**Comment by ironmonk88** [comment]
Closing this as those features were added awhile ago.
Cleaning up tickets.
