### ISSUE TITLE
Lootsheetnpc integration: ReferenceError: newcurr is not defined

### ISSUE THREAD

**Issue by koganei** [ironmonk88/monks-tokenbar#214]
Hi, I'm trying to get Lootsheetnpc to play nice, but I'm getting this error:
"ReferenceError: newcurr is not defined"

It seems like newcurr is not referring to anything here. Should it be `currency` instead?
https://github.com/ironmonk88/monks-tokenbar/blob/main/apps/lootables.js#L445

**Comment by ironmonk88** [comment]
Latest patch changed how lootables are handled.
This should be fixed now.
