### ISSUE TITLE
Option for Blind rolls to not send a message to the player (PF2E)

### ISSUE THREAD

**Issue by MarkPearce** [ironmonk88/monks-tokenbar#215]
![image](https://user-images.githubusercontent.com/6976378/156258867-db361fb4-8da0-4c0d-a81b-5938e84970eb.png)
![image](https://user-images.githubusercontent.com/6976378/156259250-444acbab-6bf7-4c32-959b-4dd317177abc.png)

When making a "blind" GM roll the player still is sent a /whisper of the roll dialog even if the result is hidden.

It would be preferable to have the option not to send that /whisper as it gives away any "secret" perception check.

**Comment by ironmonk88** [comment]
That's exactly what it's supposed to do.

Guide to Roll Mode: 
Public Roll will show everyone who's involved and their roll.
Private GM Roll will show the player everyone else involved but will only reveal their own roll/success.
Blind Roll will only show the player that they're involved and will not show the result of the roll.
Blind mode won't show the players at all. The GM will have to roll the dice themselves.

**Comment by MarkPearce** [comment]
in PF2E there is an option not to create that message.


async function rollPerceptionCheck() {
  let result = await game.pf2e.Check.roll(
    new game.pf2e.CheckModifier(
      "Perception Check",
      token.actor.data.data.attributes.perception
    ),
    {
      actor: token.actor,
      type: "perception-check",
      createMessage: false,
      skipDialog: true,
    }
  );
  return result;
}

**Comment by ironmonk88** [comment]
Closing this as it's not an issue, so much as a misunderstanding of what the drop down options mean,
