### ISSUE TITLE
[Feature Request] Apply the currently selected default roll mode

### ISSUE THREAD

**Issue by jonathanmclaus** [ironmonk88/monks-tokenbar#217]
The chat has an option to select the default roll mode. It would be great if this is automatically selected as the roll mode for dialogue boxes for Request Roll, Contested Roll, etc.

In the screenshot below, you can see that I've selected "Private GM Roll", but the dialogue box still defaults to Public Roll.

![image](https://user-images.githubusercontent.com/5731591/157582758-a284274b-a0dc-40f2-bd7f-819eb879396b.png)

**Comment by ironmonk88** [comment]
Closing this... since the dropdown on the dialog box doesn't really correspond to what Tokenbar is asking for, and never actually gets used, once it's set by the tokenbar.
