### ISSUE TITLE
Request Roll for multiple instances of the same actor have the same result

### ISSUE THREAD

**Issue by CasparHansen** [ironmonk88/monks-tokenbar#22]
When I have multiple monster tokens representing the same actor included in a Request Roll, only a single die is rolled and the same result is used for all of them, rather than one die per token.

**Comment by ironmonk88** [comment]
Oh... dear.  I recorded the items as actors instead of tokens.
I'll work on switching it over to using tokens instead.

**Comment by ironmonk88** [comment]
Version 1.0.9 released.  Should be fixed now.

**Comment by CasparHansen** [comment]
Thanks so much for the quick fix!
