### ISSUE TITLE
[Feature Request] Add button to refresh stats for actors

### ISSUE THREAD

**Issue by TheSirLancelot** [ironmonk88/monks-tokenbar#220]
If the AC of an actor changes (shields, buffs, etc.), the stats don't update on the bar. Add a button to refresh the stats so the updated AC shows properly.

**Comment by Sravdar** [comment]
This seems to be big issue for pf2e. I'm having same problm. Unless token moves, stats don't change. Maybe refresh the stats everytime a effect is applied to actors?

**Comment by ironmonk88** [comment]
Fixed the issue in PF2e with updating effects.
Did not add a button to refresh, 'cause Tokenbar should update automatically.  If it does not, please report that and I'll track down the automation that needs to be included.
