### ISSUE TITLE
[PF2e] editstats.js can get into an infinite loop

### ISSUE THREAD

**Issue by pat-son** [ironmonk88/monks-tokenbar#222]
editstats.js makes a call to `TokenDocument.getTrackedAttributes`, which can enter an infinite loop when used with some Pathfinder characters (for example, the Amiri iconic). [According to the PF2e system developers](https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/2214#note_903231315), this is a misuse of the API.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
