### ISSUE TITLE
BUG: Failed Check marked as passed

### ISSUE THREAD

**Issue by pesky-wobbit** [ironmonk88/monks-tokenbar#224]
![image](https://user-images.githubusercontent.com/477446/162493443-dba15f19-31eb-40ee-bb01-58abeb2b340a.png)
The second player - Zachari - failed his Survival Check but it is marked as a pass!

He rolled an 11 and his Survival Skill (-1) was correctly applied. The resulting 10 should have been a fail vs the DC 15.

Looking closely at the picture the X on Zachari's line has a pinkish halo and his green check does not. Compare with Sunraela, two lines lower. Maybe the logic indicated a fail but there was a formatting mistake?

I am using the latest version: 1.0.65.

**Comment by ironmonk88** [comment]
Closing this as it's really old code and has probably changed since then.
If this is still an issue, feel free to re-open the ticket.
