### ISSUE TITLE
Option to Hide Movement Mode buttons in the TokenBar

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-tokenbar#227]
Option to remove the buttons related to movement limitation modes, for games where these buttons are rarely needed but eat screen space and can be misclicked. 

While at it, option to hide Award XP would be greatly appreciated as well. 

![image](https://user-images.githubusercontent.com/4083812/163019648-854f3251-fb53-4aac-91c0-a2330edfc19d.png)

**Comment by ironmonk88** [comment]
Added to the latest release.
