### ISSUE TITLE
Resolution of images is too low

### ISSUE THREAD

**Issue by Dorako** [ironmonk88/monks-tokenbar#228]
Other modules are able to grab images in a way that renders them at an appropriate resolution when used with high pixel density displays.
<img width="345" alt="Screenshot 2022-04-13 at 00 43 57" src="https://user-images.githubusercontent.com/1561190/163066760-2a0790f5-af7a-4980-8e46-a153e1eeb72f.png">
Pictured center: Monk's tokenbar with some css changes, and other modules grabbing image info.

Great modules btw

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
