### ISSUE TITLE
Feature Request: allow macro to pass a 'name' in requestRoll options

### ISSUE THREAD

**Issue by the-real-orson** [ironmonk88/monks-tokenbar#229]
Would be great if there were a way to pass a chat card title to the roll message, something like this: 
`game.MonksTokenBar.requestRoll([{"token":"TestPlayer"}],{request:'dice:2d4', silent:true, fastForward:false, flavor:'Please roll your damage...', rollMode:'roll', name: 'Spike Growth Damage'})`  so we get a nice bold title on the chat message for what the roll is for

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
