### ISSUE TITLE
Incompatibility with Card Support

### ISSUE THREAD

**Issue by NutritiousCookie** [ironmonk88/monks-tokenbar#23]
This module causes hands in [Card Support](https://github.com/spacemandev-git/fvtt-card-support) to display vertically rather than horizontally, causing it to fall off screen.
![Screenshot 2021-02-03 041742](https://user-images.githubusercontent.com/30578022/106732971-f1daff00-65d6-11eb-8e8e-60d2c2754c62.png)
![image](https://user-images.githubusercontent.com/30578022/106732929-e7206a00-65d6-11eb-8f5d-8802a6de202a.png)

**Comment by ironmonk88** [comment]
Technically this was an issue with Monk's Hotbar Expansion.
Card Support was using extending the HotBar class and I needed to check a little more specifically on the instance of the class I was looking at.  Version 1.0.6 of Hotbar Expansion has been release and should fix the issue.
