### ISSUE TITLE
[BUG] Loot Table not correctly populating currency calculated from CR. 

### ISSUE THREAD

**Issue by coboba123** [ironmonk88/monks-tokenbar#230]
When turning actors into a loot table, selecting "Assign gold by CR" will correctly calculate gold based on CR as seen below. 

![image](https://user-images.githubusercontent.com/12433299/164878168-ccb187c2-687b-4e24-bf49-97139df45e6e.png)

However, when converting it to a lootable, it will not add this gold to the lootable. Looking at apps/lootables.js
 you can see on line 452 is the following: 

`let entryCurr = entry.actor.data.data.currency;`

However, entry.actor.data.data.currency is all 0 for all currencies for all entities. seen here: 

![image](https://user-images.githubusercontent.com/12433299/164878240-bb11c7f4-610a-4511-acaa-843e8bdd692c.png)

The currency that was calculated previously is not populated here. Instead, it is populated at entry.currency, as seen here:

![image](https://user-images.githubusercontent.com/12433299/164878269-fd5f1ce2-b31b-417a-a50d-ab859748ac8c.png)

So in order for it to properly carry over the currency into the loot table entry, the CR calculated gold needs to either populate to entry.actor.data.data.currency OR line 452 of apps/lootables.js needs to be `let entryCurr = entry.currency;`

For now i have adjusted my personal js file to the latter solution, though i don't have the knowledge of this project to know if it breaks other things. For now it is working for my uses. 

I hope this was helpful, thank you for making this module.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
