### ISSUE TITLE
[PF2e] Multiple skill roll requests

### ISSUE THREAD

**Issue by MrVauxs** [ironmonk88/monks-tokenbar#235]
As the title suggest, especially in the Pathfinder 2e and D&D5e system, it would be nice to allow the GM to pick a set of skills (most likely by shift clicking in the normal menu). Then in the chat upon rolling a player can choose which skill to use.

**Comment by ironmonk88** [comment]
Closing this as it was added awhile ago.  Just cleaning up tickets.
