### ISSUE TITLE
Item Pile Integration not adding all items.

### ISSUE THREAD

**Issue by Brimcon** [ironmonk88/monks-tokenbar#236]
**Foundry Version 9.269**
**DnD5e 1.6.1**
**Monk's Token Bar 1.0.66**
**Item Piles 1.4.8**

When converting multiple NPCs to lootables with Item Piles configured, it only adds one of each item.
For example, if there are three Goblins and you convert them to an item pile, it only adds 1 leather armor, 1 shield, 1 scimitar, and 1 short bow.
Expected behavior is to have 3 of each item.

To Reproduce: 
1. Activate Monk's Token Bar and Item Piles
2. Enable Item Piles in Monk's Token Bar's configuration for loot conversion
3. Place 3 Goblins from DnD5e's Monster Compendium
4. Convert the Goblins into Lootables via the `Distribute Lootables` button
5. Open up the newly created Loot Pile and observe number of items.

As an aside, there is no option to use a preconfigured item pile actor. You can only create new actors which does flood the Actor list if not trimmed frequently.

**Comment by ironmonk88** [comment]
Just reviewing older tickets, and a lot has changed since this was added.
I believe it should be fixed now.

**Comment by ironmonk88** [comment]
Closing this as it's old, there's been no communication, and I believe it's been fixed.
