### ISSUE TITLE
No request and contested roll icon

### ISSUE THREAD

**Issue by yfery** [ironmonk88/monks-tokenbar#241]
Hi, 

I don't know why, but request roll and contested roll are not enable :

![image](https://user-images.githubusercontent.com/22793377/170839716-caeac5ba-4a4c-435b-b840-f4dd006f010f.png)

I'm using foundry 9, monks-tokenbar 1.0.67 on warhammer 5.3.0. I tried on cyberpunk 0.80.1 with the same result. 

Is-it a DnD exclusive feature ?

**Comment by ironmonk88** [comment]
Nope.  But it does require the system to be added to the ones Tokenbar knows how to interact with.
I thought Warhammer was on the list, but I'm guessing not.

**Comment by ironmonk88** [comment]
Closing this as it's not really an issue.  If the buttons are missing, then it means the system isn't supported yet and needs to be handled on a case by case basis, to request the system to be added to tokenbar.
