### ISSUE TITLE
[Feature Request] Deduct currenty from your players

### ISSUE THREAD

**Issue by turboraton** [ironmonk88/monks-tokenbar#242]
Hello there Mr. Monk, MANY thanks for your amazing modules. I have the following suggestion: sometimes your players need to pay a fee, a bribe, pay for some services, etc. It would be amazing if the DM could do that and output to chat so everyone knows things are being transparant, perhaps even highlight if someone can't pay the price.

**Comment by ironmonk88** [comment]
Not really a Tokenbar thing.
But I did add it to Enhanced Journals.  Fits a little better over there.
