### ISSUE TITLE
Show on Tokenbar option no longer available?

### ISSUE THREAD

**Issue by daishimatt** [ironmonk88/monks-tokenbar#247]
I've been trying to figure out if there is a way to just ask a question to see if I am missing something.  Sadly not

On PF2e it no longer seems to be possible to set "Show on Tokenbar" individually for a creature.
This is ever so awkward when dealing with things like animal companions or NPCs which you might not want on the token bar, but require a full character sheet.
How do I specify if I want a specific creature to not appear on the token bar?

**Comment by daishimatt** [comment]
As a note, there is an option for this on the default settings (as in, within the Configuration settings) just not on the prototype token screen anymore.

**Comment by ironmonk88** [comment]
Closing this as it's really old and I can't replicate.
I'm assuming the issue was resolved.  If it hasn't feel free to re-open the ticket.
