### ISSUE TITLE
Assign XP if not divided equally does not work.

### ISSUE THREAD

**Issue by Akallabeth13666** [ironmonk88/monks-tokenbar#248]
So assigning XP works fine if everyone gets the same amount.
But if I decide to assign specific value to each character it does not work.
Some screenshots attached
![xp1](https://user-images.githubusercontent.com/95130435/173589436-cfeec506-0219-43c8-a5f7-6cd1e271f0e0.JPG)
![xp2](https://user-images.githubusercontent.com/95130435/173589439-384f6e92-9625-441b-a2fc-c310e093e72e.JPG)
.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
