### ISSUE TITLE
Request roll in pathfinder 2e seems to break

### ISSUE THREAD

**Issue by noldofinwe** [ironmonk88/monks-tokenbar#25]
Hey, first of all, really cool module! 

I'm having an issue when I as game master do request roll and players press the Roll button in the chat it gives the following error:

savingthrow.js:180 Uncaught (in promise) ReferenceError: requestroll is not defined
    at Function._rollAbility (savingthrow.js:180)
    at HTMLAnchorElement.onRollAbility (savingthrow.js:256)
    at HTMLAnchorElement.i (jquery.min.js:2)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
_rollAbility @ savingthrow.js:180
onRollAbility @ savingthrow.js:256
i @ jquery.min.js:2
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

When I look in the code I do see:

    else if (game.system.id == 'pf2e') {
                    var _a, _b;
                    if (null === (_a = actor.data.data.skills[requestroll]) || void 0 === _a ? void 0 : _a.roll) {
                        //const opts = actor.getRollOptions(["all", "skill-check", null !== (_b = actor_1.SKILL_DICTIONARY[requestroll]) && void 0 !== _b ? _b : requestroll]);
                        rollfn = actor.data.data.skills[requestroll].roll;//(ev, opts)
                        rollParams = [null, null, { fastForward: fastForward, chatMessage: false }];
                    } else {
                        rollfn = actor.rollSkill; //(ev, requestroll);
                        rollParams = [null, request, { fastForward: fastForward, chatMessage: false }];
                    }
                }
 where requestroll  is not defined before  actor.data.data.skills[requestroll] as far as I can see.

**Comment by ironmonk88** [comment]
Uhhh... technically that wasn't supposed to be available to PF2E yet.  :-( I was debugging and I guess I left it open with the last release.
Finished up the work for pathfinder and it should be available in the latest release.
