### ISSUE TITLE
[BUG] Assign XP calculation for PF2E groups

### ISSUE THREAD

**Issue by Donixs** [ironmonk88/monks-tokenbar#251]
Howdy! There is currently an issue where, when using PF2E system,  Assign XP does not calculate XP correctly in instances of groups equal to or smaller than 3.

An example, if you have two level 5 PCs against two level 4 creatures, it should calculate to 60 XP as both level 4 creatures are -1 party level, so they'd be worth 30 each. The module instead calculates it to 80 XP, as if each creature were equal to the party level.

If you bring it to three level 5 PCs, the module calculates to 80. If you bring in four PCs, it drops down to 60 XP, which is the correct amount.

There was a discord post about a year ago that potentially highlighted this issue and offered a potential solution, linked [here ](https://discord.com/channels/862414864692281386/862421107687817288/877481278822289428) I don't believe it was implemented as I compared the previous branches to the current one and found no change similar to the ones it made.

Thank you for reading, and if you need anymore information, I would be more than happy to help!

**Comment by ironmonk88** [comment]
Closing this as the code has changed and Tokenbar now lets PF2e calculate the XP as I figure the system knows how to do it best.
