### ISSUE TITLE
Doesn't work on Witcher TTRPG system

### ISSUE THREAD

**Issue by DKtric3L** [ironmonk88/monks-tokenbar#255]
Actor tokens are not displayed on the panel, what am i doing wrong?

**Comment by DKtric3L** [comment]
![изображение](https://user-images.githubusercontent.com/105752167/177180934-66275846-a572-4d2f-a8e3-696a83fefa41.png)

**Comment by ironmonk88** [comment]
For a token to show on the panel, they have to be owned by a player, and of friendly disposition.
You can manually add them to the tokenbar from the token config window if that doesn't work.
