### ISSUE TITLE
[Feature Request] Additional display option

### ISSUE THREAD

**Issue by LukasPrism** [ironmonk88/monks-tokenbar#256]
Hiya! Please consider adding another option to this dropdown:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/104886594/178127479-3f6defc5-ac77-4b7f-906e-81703c6d20e5.png">

Along the lines of: "Include for everyone" – that means the token is displayed in all player's bars, irrespective of their permissions. This way we'd be able to have the other party members in the bar without needing Observer permissions. Meaning we can pan to them, whisper to those players, and see how they're faring health-wise.

Much appreciated!

**Comment by ironmonk88** [comment]
![image](https://github.com/ironmonk88/monks-tokenbar/assets/75920956/cdc53b12-27f7-49b3-9fb6-e34a4dfded27)
You can change it in the settings to allow for limited permissions to be viewable on the tokenbar.
