### ISSUE TITLE
[Feature request] Group roll skill checks

### ISSUE THREAD

**Issue by DjKrayl** [ironmonk88/monks-tokenbar#257]
Hello! I was wondering if a group skill check, as an optional box to check or something, could be added to the request roll window.

**Comment by LukasPrism** [comment]
This would be great, our GM never uses group skill checks because he's unclear on them. If it was an option in here it would be very clear if it's a success or fail :)

**Comment by apoapostolov** [comment]
You can make Group skill checks right now. You need to open the Request Check, add all players, and select desired check, then save it as a macro and use this macro to trigger the group check. You always need to have all included players on the scene.

**Comment by DjKrayl** [comment]
> You can make Group skill checks right now. You need to open the Request Check, add all players, and select desired check, then save it as a macro and use this macro to trigger the group check. You always need to have all included players on the scene.

I guess I shouldve been more clear. You are correct. You can do a skill check to a group of people. The group skill check I meant is having an option for an averaged roll, like on a stealth check.

**Comment by LukasPrism** [comment]
Yes, per the Working Together section in Chapter 7 of the PHB. See, not enough people are using these rules, it's time for Monk to shine a light on it :)

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/178852363-13243c81-a5ab-4dff-bc8a-3b8de81aa7a0.png)
It's already there.

**Comment by LukasPrism** [comment]
OK I guess I wasn’t on the same page as you guys haha. I was thinking of the Group Checks rules from the PHB. This is actually cooler though! Thanks

**Comment by DjKrayl** [comment]
ahhhh i see now. It just auto converts from a straight dc to average then. thank you for answering!
