### ISSUE TITLE
Feature Request: Pop-Out Tokens in Tokenbar

### ISSUE THREAD

**Issue by MrVauxs** [ironmonk88/monks-tokenbar#261]
It would be great to have token bar `transform scale` the size of the tokens based on their on-map token scale.

**Comment by ironmonk88** [comment]
Due to styling reasons this isn't feasible.  The tokens need to be a consistent size otherwise you'd have a hard time find them with all the varying sizes and positioning.  The canvas is a great place to have different sized icons, but the tokenbar should be all the same size.
