### ISSUE TITLE
Feature Request: permanent Actors on the tokenbar

### ISSUE THREAD

**Issue by franckflo** [ironmonk88/monks-tokenbar#267]
Would it be possible to add a toggle for each actor (right-click on the sidebar icon for the actor) so that they are always in the tokenbar, even if their icon is not on the current's scene's map? That would be nice for "theater of the mind" situations. 

Thanks!

**Comment by ironmonk88** [comment]
Added the option to show player actors on the tokenbar even if the token isn't on the current scene.
