### ISSUE TITLE
Small error when change the token-size

### ISSUE THREAD

**Issue by sanguaire** [ironmonk88/monks-tokenbar#268]
Hello,

there is a small error in the style of the token.

` let innerHTML = `
#tokenbar .token {
    flex: 0 0 ${setting('token-size')}px;
    width: ${setting('token-size')};
}
`;`

The value of the width property must end with px, otherwise chrome shows some css error.

File: monks-tokenbar.js
Line: 144

Can you fix it?

Thanks.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
