### ISSUE TITLE
Bug: V10 Convert Loot Settings

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#273]
https://user-images.githubusercontent.com/99844555/188282290-4ac446c6-024c-45f3-8627-e1f3d430388b.mp4
Do Not Convert doesn't appear in the dropdown. Then changing it to any others sets it to Do Not Convert and the other options disappear.

**Comment by ironmonk88** [comment]
This is an old interface and should be fixed now.
