### ISSUE TITLE
[BUG] Assign XP (MATT)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#274]
Its no longer adding XP to the actor (it is owned by a player). No errors.

![image](https://user-images.githubusercontent.com/99844555/188738540-1ca08c83-7a9c-4145-b0b2-b96710067aa6.png)

**Comment by ironmonk88** [comment]
Technically MATT doesn't assign XP.  It just opens a chat message for the players to click a button and assign their own XP.
I've updated the MATT action to include the option to by pass the dialog, and the auto assign.
So next version you'll be able to assign XP directly to the actor.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
