### ISSUE TITLE
[BUG] Auto-Roll in PF1

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#276]
![image](https://user-images.githubusercontent.com/99844555/190886144-4abbec23-4ebe-4913-a9d4-1e0a8fdbfc14.png)

The auto-roll setting in PF has an issue; it skips having to click the dice in the chat window card, but it always triggers this prompt, regardless of the system setting (below).

Occurs when triggered via both Token Bar and MATT.

![image](https://user-images.githubusercontent.com/99844555/190886133-5e4786f1-51fd-4a71-a03e-c293beed8e36.png)

Token Bar 10.1.
![image](https://user-images.githubusercontent.com/99844555/190886253-fe649f5b-0de4-44b7-9235-1fd95aa9138e.png)

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
