### ISSUE TITLE
GM rolling for a player causes all other players to disappear, error in console

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-tokenbar#279]
savingthrow.js:778 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'total')
[Detected 1 package: monks-tokenbar]
    at Object.fn (savingthrow.js:778:49)

From this state

![image](https://user-images.githubusercontent.com/4083812/192107928-2468c9d8-2497-4464-9279-56180468c94b.png)

Clicking on Merisiel for example causes all other players to disappear

![image](https://user-images.githubusercontent.com/4083812/192107944-6212a821-67b7-4964-b360-6b242981a2cf.png)

**Comment by ironmonk88** [comment]
Foundry made a change to how it was serializing the roll data.
I put in a ticket for a correction.  https://github.com/foundryvtt/foundryvtt/issues/8260
In the meantime I'm compensating in my code, but it sort of depends who releases a patch first.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.

**Comment by apoapostolov** [comment]
Thank you, it is fixed now.
