### ISSUE TITLE
[BUG] Error when Opening Request Roll

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#280]
https://user-images.githubusercontent.com/99844555/192131034-d16b4b2e-7624-4aa3-bdba-1dad622cbf67.mp4

![image](https://user-images.githubusercontent.com/99844555/192131041-69b62254-dcbf-497f-be62-a1b89ab9b163.png)

Update: PF2 & DnD5e 2.0.3

MATT & Tokenbar 10.2
![image](https://user-images.githubusercontent.com/99844555/192131045-767bfb24-c6c8-407b-8f04-27fee1fa33fb.png)

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
