### ISSUE TITLE
[BUG] PF2e. Ctrl Multi-Select

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#281]
Holding Ctrl and trying to select a second roll option results in this error. 
![image](https://user-images.githubusercontent.com/99844555/192131101-bc0e6c92-308f-4b57-ab0e-b3252c4f6ba5.png)

MATT & Tokenbar 10.2
![image](https://user-images.githubusercontent.com/99844555/192131126-e296d4c1-c5de-40e0-8338-28216ca14404.png)

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
