### ISSUE TITLE
[BUG] Request Contested Roll

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#282]
### D&D 5e & PF2e.

https://user-images.githubusercontent.com/99844555/192131178-78cd654d-25ea-458f-91cb-77a83b277966.mp4

![image](https://user-images.githubusercontent.com/99844555/192131188-fd12a9f7-3dc9-4d7f-b47d-8c6868724e77.png)

### Just PF2e.

Doing the request and clicking the chat card dice gets this below one.
![image](https://user-images.githubusercontent.com/99844555/192131742-cb72652a-51ad-4bab-b517-633012d6f2dc.png)

D&D 5e 2.0.3 and PF2e.

MATT & Tokenbar 10.2
![image](https://user-images.githubusercontent.com/99844555/192131198-8a062869-f161-4255-960f-490f61a488e1.png)

**Comment by Wokeye27** [comment]
Yep, I get this also.

**Comment by AllGearNoSkil** [comment]
Same here. I've observed it with strength checks using the button, but it also occurs when 'saving' any combination of rolls as a macro, setting `silent:true` and running the macro.

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
