### ISSUE TITLE
[BUG] PF2e. Error when Clicking Chat Card Dice

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#283]
Uploading Foundry_Virtual_Tabletop_cXqdQzPv54.mp4…

![image](https://user-images.githubusercontent.com/99844555/192131310-e476946e-e311-4677-99d1-3ee5dc49ffef.png)

MATT & Tokenbar 10.2

![image](https://user-images.githubusercontent.com/99844555/192131315-7b1556bc-d426-4281-8955-baaf7abdb7bf.png)

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
