### ISSUE TITLE
Set player token to token bar for assistant GMs?

### ISSUE THREAD

**Issue by SirAron111** [ironmonk88/monks-tokenbar#284]
**Is your feature request related to a problem? Please describe.**
I am the assistant GM of one of my players who is DM ing a game on Foundry for the first time. But since i have the assistant GM mode assigned, i cant have an assigned player character token and thus can't appear in the Token Bar. Is there a way to integrate this? I use the assistant gm mode to help behind the scene while, so he can focus on DMing since he isn't used to the foundry stuff yet, but not being able to use the functions the Token Bar provides is sad.

**Describe the solution you'd like**
Adding an option to either set a token to the bar that's not currently player assigned or make it possible to assign assistant GMs a player token as well so the module registers it.

**Additional context**
None

**Comment by Crowguard** [comment]
On the prototype token window for the actor. 
![image](https://user-images.githubusercontent.com/99844555/192183373-e3510440-4c7e-493e-9158-e52e30f10d89.png)

**Comment by LukasPrism** [comment]
I would love a bit more control in this regard. Our party would like to be able to see all players in our token bars (not just ourselves). The only way to do it now is to set players to Observers of other players, but that messes up vision etc. Perhaps if Trusted Players could also see what is set to “Include” in token bar, as well as Assistant GMs? Or have a minimum permissions level for them to show up.
