### ISSUE TITLE
[BUG] PF1. Request Roll

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#287]
### Error 
Occurs when opening the Request Roll window for the first time.
![image](https://user-images.githubusercontent.com/99844555/192679062-d13363a7-03a0-4488-9342-366e29d772d4.png)

### Result
Clicking the chat card die/doing a Request With Roll results in a blank result. No error.
![image](https://user-images.githubusercontent.com/99844555/192679414-715037e7-cc18-4406-9b53-af108b1db067.png)

https://user-images.githubusercontent.com/99844555/192679466-f40dcd7c-646f-4dd7-bcf9-1d918b38bb15.mp4

Foundry 10.286
Tokenbar 10.2
PF1 0.82.2

**Comment by ironmonk88** [comment]
This was actually two different bugs.  Both are fixed.

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
