### ISSUE TITLE
[BUG] PF2e. Awarding XP after Combat

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#289]
Token bar fails to add the XP to the selected actors after combat.

![image](https://user-images.githubusercontent.com/99844555/193505526-fe72f131-1d5f-463e-afdd-055e18c1ee4c.png)
![image](https://user-images.githubusercontent.com/99844555/193505560-587d0cb3-3467-43c2-854b-57b3c5f6cf40.png)
 
 
 Token Bar 10.2
  
![image](https://user-images.githubusercontent.com/99844555/193505608-3f15bde0-d993-45e8-a393-189c9a27c28a.png)

**Comment by Provaporizer** [comment]
A friend and I are also having this same issue in PF2E

**Comment by Joshmvii7** [comment]
Came here to report the same issue.

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
