### ISSUE TITLE
Players can see die result of blind GM rolls through the tokenbar

### ISSUE THREAD

**Issue by grankless** [ironmonk88/monks-tokenbar#29]
https://cdn.discordapp.com/attachments/319721075988758528/811819776791805962/8f92Jl9.png

Picture from player's view. Is this intended behavior? The players should probably not be able to see what the number they got is, especially since the actual total result is obfuscated.

**Comment by ironmonk88** [comment]
Well, that's not good.  Thank you for catching that.  I'll start working on that.

**Comment by ironmonk88** [comment]
Should be fixed in 1.0.16.
