### ISSUE TITLE
[BUG] Duplicate Skills Requested

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#292]
**Describe the bug**
Skills can be duplicated when ctrl-clicking in the request roll window.

![image](https://user-images.githubusercontent.com/99844555/196550681-4667b96d-f3d7-4568-a026-032f7707ac6d.png)

**To Reproduce**
Normal click a skill to select it, then ctrl-click the same skill, then request the roll.

**Please complete as much of the following information as possible:**
Foundry 10.288
D&D 5e 2.0.3
Tokenbar 10.2
FTC ✔️

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
