### ISSUE TITLE
[BUG] Request Roll, Private Roll w Results Hidden

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#294]
This option is only showing the chat card on the GM screen now; no errors.

https://user-images.githubusercontent.com/99844555/197293283-33ae0198-4dbf-4623-a37b-ff29d856bb04.mp4

Foundry 10.288
D&D 5e 2.0.3
Tokenbar 10.2

**Comment by weepingminotaur** [comment]
Can confirm this is fixed in MTB 10.3

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
