### ISSUE TITLE
[BUG] Request Roll, Initiative

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#295]
When requesting an initiative roll, whether using auto-roll or having the player clicking the dice, does not update the chat card despite forwarding the roll to the combat tracker. This also seems to be having the side effect of messing with MATT action threads waiting for the Request Roll action to be finalized before continuing.

https://user-images.githubusercontent.com/99844555/197295794-5947236a-1209-4471-8255-d36830f99852.mp4

![image](https://user-images.githubusercontent.com/99844555/197296793-e0745084-305c-492d-b338-8b8a600f6b7d.png)

[fvtt-tiledata-initativetile.zip](https://github.com/ironmonk88/monks-tokenbar/files/9842821/fvtt-tiledata-initativetile.zip)

Foundry 10.288
MATT 10.3
Tokenbar 10.2
D&D 5e 2.0.3
FTC

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
