### ISSUE TITLE
[BUG] "Transfert loot from selected token(s)" give a error in the console

### ISSUE THREAD

**Issue by CaosFR** [ironmonk88/monks-tokenbar#297]
**Describe the bug**
Hi, thanks for your work. I canno't "Transfert loot from selected token(s)" automaticely at the end of combat or manually by clicking on the button in the side bar. I got a error in the console and nothing appear in the screen.

**To Reproduce**
1. Click to ""Transfert loot from selected token(s)" in sidebar or finish a combat
2. See error

**Expected behavior**
Generate a "item piles" loot.

**Screenshots**
Error console
![image](https://user-images.githubusercontent.com/37581932/198320532-a60128d4-e7f4-48c2-989a-d5baaf08af05.png)

Setting 
![image](https://user-images.githubusercontent.com/37581932/198321369-900b132c-53b0-4139-9498-507e5575df56.png)

Token
![image](https://user-images.githubusercontent.com/37581932/198322741-7a6609b6-9a78-483a-9a9c-9acdc7a9def1.png)

**Please complete as much of the following information as possible:**
 - Browser : Chrome
 - Foundry Version : 10.288
 - System : DnD5e 2.0.3
 - Module version : 10.3
 - Are there any errors in the console : Yes
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction : Yes

**Additional context**
All other module instead of items-piles are disables.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
If it isn't, please re-open the ticket.
