### ISSUE TITLE
[BUG] Tokenbar wanders when using the expand/colapse arrow

### ISSUE THREAD

**Issue by Kurokasa** [ironmonk88/monks-tokenbar#299]
Hi, this is a smaller bug, but i thought i mention it anyway. When the tokenbar is collapsed and expanded again the tokenbar wanders a tiny bit to the right. You can see it well when you spam the funktion while keeping the mouse still.

1. Click on the little arrow to collapse / expand the tokenbar on the game canvas.
2. You should see the tokenbar drifting to the right
3. Clicking mutliple times makes it more obviouse

**Screenshots**
![Tokenbar-Driftking](https://user-images.githubusercontent.com/102412559/198526405-5c842197-edbf-40b3-9103-4cac962179c3.gif)

**Please complete as much of the following information as possible:**
 - Browser [chrome]
 - Foundry Version [v10]
 - System [D&D5e]
 - Module version [10.3]
 - Are there any errors in the console [No errors]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction [No].

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
