### ISSUE TITLE
XP Dialogo is show to players

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-tokenbar#3]
the dialog to distribute xp (after a fight) is displayed to all players, so they can change the xp or even everyone who clicks the button to receive the duplicate xp.

**Comment by ironmonk88** [comment]
Thank you for catching that.  Updated the code to restrict the dialog to GM only.  Should be available in the next patch.

**Comment by ironmonk88** [comment]
1.0.5 is available, issue should be fixed.
