### ISSUE TITLE
Dueling Parry Feat effect doesn't update AC in Token Bar

### ISSUE THREAD

**Issue by Mr-Monocyte** [ironmonk88/monks-tokenbar#30]
The AC seems to update correctly when doing other things that modify the AC but applying this Feat Effect (+2 AC) doesn't change the displayed AC. The Character sheet does show the correct AC with the +2 applied.

**Comment by Mr-Monocyte** [comment]
Sorry. The issue seems to be with the spell effect itself. It is shown as "expired" immediately upon application.

Odd same thing happens with Stances that modify AC. the changes show for the character sheet ( and Token Info Icons module) but not the Token Bar

**Comment by ironmonk88** [comment]
I'm not familiar with PF2E... how do you activate a feat?

**Comment by ironmonk88** [comment]
I've changed the way I update the values.  This should be fixed.  re-open if it is not.
