### ISSUE TITLE
[PF2E] Ability to bypass roll dialogs by holding down Shift

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-tokenbar#300]
Right now, selecting tokens and using the Request with Roll option still pops up the individual roll dialogs for each token, even if you're holding down Shift, which is Pf2e's hard-coded "bypass roll dialog and just roll" keybind. Have verified in a clean world with 0 modules installed except MTB, Foundry v10.288, Pf2e 4.3.1, MTB 10.3.

It would be great to be able to use Shift to bypass those roll dialogs, either when using Request with Roll or clicking the dice icons in the Request Roll chat message.

**Comment by ironmonk88** [comment]
Closing this as it was added awhile ago.
