### ISSUE TITLE
[BUG] [T20] - Requests Rolls Don't Work on T20 System

### ISSUE THREAD

**Issue by GabrielDeschain** [ironmonk88/monks-tokenbar#301]
Requests Rolls Don't Work on Tormenta 20 System.

When we use the button of request roll in tokenbar, the request show up in chat, but the players and the GM don't can click the dice icon and make the roll.

I would like to know if this is a system specific problem or if you can solve it there.

Please complete as much of the following information as possible:

Browser [ALL]
Foundry Version [v10]
System [Tormenta 20]
Module version [1.0.6]
Are there any errors in the console [I don't know]
Have you tried using Find the Culprit to make sure it isn't a module interaction [Yes].

**Comment by ironmonk88** [comment]
I'm unable to replicate this.
The latest version of Tokenbar is 10.3 though, are you sure you're on the latest version?

**Comment by ironmonk88** [comment]
Closing this as I'm unable to replicate, it's old, and there's been no response.
