### ISSUE TITLE
[BUG] Request with Roll fast forwarding doesn't work on PF2E

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-tokenbar#302]
When you set the roll to fast forward and Request with Roll, you expect the rolls to be made automatically in the chat window. Instead, the dice show up, and roll dialogs pop up for each token.

**Comment by ironmonk88** [comment]
Is this still an issue?

**Comment by weepingminotaur** [comment]
No, not that I know of.

**Comment by ironmonk88** [comment]
Closing the ticket.  :-)
