### ISSUE TITLE
[Feature Request] Party Mode

### ISSUE THREAD

**Issue by LukasPrism** [ironmonk88/monks-tokenbar#303]
Heya, thanks for a wonderful, indispensable module!

Our group are huge CRPG fans. We'd love token bar to work how it typically does in those games – it's already nearly there. To do so would require quite minor changes:

- Allow a mode where all members of the party are visible in the token bar to each other (not just the GM)
- Allow an Alt-click to target/untarget party members (eg if you're casting Bless you can target three allies in the token bar with three Alt-clicks)

Having this mode would also make it very easy to Whisper to your fellow party members (right now it requires using risky chat syntax which can go wrong if you type it in wrong – a whisper becomes a broadcast).

Thanks for considering this.

**Comment by weepingminotaur** [comment]
Neat idea, though I will say that there is a Whisper macro bundled with Foundry Community Macros (I think?) and also the Sweet Nothings module, both of which are way better than whisper syntax in chat (I agree it's too risky). For targeting other party members, they can target each other's tokens on the canvas, so I'm not sure if targeting on MTB would be worth it.

**Comment by LukasPrism** [comment]
You can already target with MTB, it’s on the context menu. Alt-click would just make it quicker and makes sense if you’re opening up the bar fully to all players. As in a CRPG game it’s much faster to target portraits than chase characters around a map. 

And yeah the whisper thing would just be a bonus with no extra work by Monk. The feature is already there. Saves installing another module :)

**Comment by ironmonk88** [comment]
Ctrl click already targets tokens on the tokenbar.
I've added the option in the settings to set the minimum player permission needed to view a token on the tokenbar.  Currently it's set to Owner.  But if you change it to Observer and give players the Observer permissions to tokens that aren't theirs, they'll be able to see them in the tokenbar.
