### ISSUE TITLE
Contest roll error in Savage Worlds.

### ISSUE THREAD

**Issue by flynnkd** [ironmonk88/monks-tokenbar#304]
For Savage Worlds... the request contest roll for traits shows an error, but works for skills and dice roll requests... attached image.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/74580085/200455046-1df6aa24-c0fc-48e0-98d4-9518f2db6717.png">

**Comment by jseeley150** [comment]
Changing swade-rolls.js line 104 from

`let item = actor.items.find(i => i.name == request.key && i.type == 'skill');`

to

`let item = actor.items.find(i => MonksTokenBar.slugify(i.name) == request.key && i.type == 'skill');`

resolves the issue. This is an issue caused by case sensitivity.

**Comment by ironmonk88** [comment]
Closing this as it should have been fixed in a previous release.
