### ISSUE TITLE
[Feature Request]  A non-combat “Turn-by-Turn mode”

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#309]
From https://discord.com/channels/862414864692281386/862421107687817288/1045133872289021984

Description: A UI button which locks all player token movement when out of combat - GM has the ability to click ‘next’ which grants free movement to tokens in rotation one after another, while locking them after their turn is complete. 

Alternatively, allow movement state to be controllable with a macro - opening up possibility of putting it in user’s macro bar to “end their exploration turn”. 

"Alternatively, double right click player icon in TokenBar to mark player as free movement while locking all others"

game.actors.getName(‘Player1’).movement.render(false);
game.actors.getName(‘Player2’).movement.render(true);
game.actors.getName(‘Player3’).movement.render(true);
game.actors.getName(‘Player4’).movement.render(true);

**Comment by ironmonk88** [comment]
Added the option to Alt Click a token while in no movement mode to set the token's movement to free movement.
