### ISSUE TITLE
Webm tokens do not render.

### ISSUE THREAD

**Issue by mtvjr** [ironmonk88/monks-tokenbar#31]
When a token has a webm image, the icon does not render correctly in the tokenbar.

![image](https://user-images.githubusercontent.com/9865643/108402199-d250f280-71e2-11eb-8868-9e9f5a72adfe.png)

Web Browser: Firefox
Foundry Version: 0.7.9
Module Version: 1.0.14

**Comment by ironmonk88** [comment]
Added in support for video files.
Should be available with the next patch.

**Comment by ironmonk88** [comment]
1.0.15 has been released, this should be fixed now.
Thank you for catching this bug.
