### ISSUE TITLE
[Feature Request] Pathfinder 2e - Take feats into account when calculating degrees of success for requested rolls

### ISSUE THREAD

**Issue by DanielKispert** [ironmonk88/monks-tokenbar#311]
**Is your feature request related to a problem? Please describe.**
In Pathfinder 2e, there are certain feats that adjust behavior on a successful roll. For example, a level 7 ranger gains "Evasion", which makes their Reflex Save Successes be counted as Critical Successes. Currently, when you request a roll for a ranger with Evasion, or any other token with a feat like that, this is not taken into account and the roll will display a normal Success:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/34270661/204065937-826a99cf-f5a5-46a8-9f10-87e5fad1ac79.png">

**Describe the solution you'd like**
It would be great if requested rolls whose degrees of success are influenced by a feat would either automatically consider it, e.g. always show a Critical Success instead of a Success, or show that a feat influences this, so that I can manually adjust the degree of success.

**Additional context**
regular rolls already support this. This is the behavior when requesting a roll through chat:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/34270661/204066115-2d8f8bdf-169f-4cf0-b74d-6cc6fbf85546.png">
Maybe it is possible to plug into that functionality?

**Comment by ironmonk88** [comment]
Closing this as it was added in a previous release.
