### ISSUE TITLE
[BUG] Assigning combat XP not working in DS4 system

### ISSUE THREAD

**Issue by Athemis** [ironmonk88/monks-tokenbar#313]
**Describe the bug**
After closing the encounter the total XP available for distribution is shown as zero ("0") when using the DS4 system.

**To Reproduce**
1. Use DS4 system
2. Add actors and (PCs and NPCs) to encounter
3. Start combat encounter
4. End combat encounter
5. Observe XP assignment dialogue

**Expected behavior**
The correct total amount ov XP should be available for distribution

**Screenshots**
Didn't take shots.

**Please complete as much of the following information as possible:**
 - Browser: Firefox 107
 - Foundry Version: v10
 - System: DS4
 - Module version: 10.3
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction? Yes, not caused by interaction with other modules.

**Additional context**
I was able to fix this by changing line 49 in apps/assignxp.js to read

`combatxp += (MonksTokenBar.system.getXP(combatant.actor) || 0);`
instead of
`combatxp += (MonksTokenBar.system.getXP(combatant.actor)?.value || 0);`

and line 25 in systems/ds4-rolls.js to read

`return actor?.system.baseInfo?.experiencePoints || 0;`
instead of 
`return actor?.system.progression?.experiencePoints || 0;`

While this works for ds4, I have not tested if the change to assignxp.js breaks proper behaviour for other systems. If this is some ds4-specific quirk and/or not easy to fix within tokenbar, I'll ask the ds4 maintainer to adjust the behaviour according to other systems.

**Comment by ironmonk88** [comment]
That would end up breaking all the other systems.
The code in d24-rolls.js should change to 
```
getXP(actor) {
        return {
            value: actor?.system.progression?.experiencePoints || actor?.system.baseInfo?.experiencePoints || 0
        };
    }
```
And all systems handle it differently, so there's no real standard.  Tokenbar formats it to requiring a `value` to be returned so that extra information can be passed for those systems that provide extra information.

Changes will be added to the next release.

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
