### ISSUE TITLE
Token bar size scale

### ISSUE THREAD

**Issue by gubacelar** [ironmonk88/monks-tokenbar#314]
**Is your feature request related to a problem? Please describe.**
The token bar is great and helpful for players and gm, but I wish to use this on streaming as well, and the size of the token bar is small for this purpose.

**Describe the solution you'd like**
A config to allow us to change the token bar scale for individual players. That way we can use a streaming user to have the token bar higher than usual.

**Additional context**
The token bar would help to show stats for spectators that are watching the game.

**Comment by FeistyMango** [comment]
@gubacelar You can somewhat scale the token bar by adjusting the scale of the token image setting. 
![image](https://user-images.githubusercontent.com/3461388/216760293-25994c49-d84a-4754-a070-2f1ef42807db.png)

**Comment by davidR1974** [comment]
not perfect solution but was able to adjust size for the vertical display by using Custom CSS and the following modification to the stylesheet...


```
/* Custom CSS */

#tokenbar.vertical {
    align-items: flex-start;
    align-content: flex-start;
    vertical-align: top;
    flex-direction: column;
    min-width: 200px;
}

#tokenbar.vertical #token-action-bar .token-list {
    width: 200px;
    flex-direction: column;
}

#tokenbar .token .token-icon {
    width: 100%;
    height: 100%;
    object-position: 40% 40%;
    border: none;
}

#tokenbar .token .token-content {
    flex: 180px;
    height: 200px;
    justify-content: center;
    display: flex;
}


#tokenbar.vertical #token-action-bar .token-list .token {
    flex-wrap: nowrap;
    flex-direction: row-reverse;
    width: 100%;
    justify-content: flex-start;
}
```
