### ISSUE TITLE
[BUG] Tool Check Request Macro With Silent:True Returns Name Undefined

### ISSUE THREAD

**Issue by harrisog** [ironmonk88/monks-tokenbar#315]
**Describe the bug**
Saving a tool roll request as a macro and setting the mode to `silent:true` causes the request's `name` to come up as `undefined Check` in the chat prompt

**To Reproduce**
1. Give tool to character
2. Generate roll request macro via UI
3. Edit macro so that `silent:true`
4. Test macro and see chat description

**Expected behavior**
Chat description should have name of tool instead of `undefined`

**Please complete as much of the following information as possible:**
 - Browser : Chrome
 - Foundry Version : 10.290
 - System : D&D 5E
 - Module version : 10.4
 - Are there any errors in the console : no red text errors in console
 - Have you tried using `Find the Culprit` : yes, the issue persists

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
