### ISSUE TITLE
[BUG] Contested Roll lacks adv/disadv buttons.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#317]
Green & red buttons don't appear when mousing over the chat card for a contested roll. 

![image](https://user-images.githubusercontent.com/99844555/204864379-c30e6d2f-e7b3-49e6-bd3c-2c249e998f99.png)

Tokenbar 10.4

**Comment by ironmonk88** [comment]
Should be added to the latest version.
