### ISSUE TITLE
[BUG] [Starfinder] When requesting group rolls the chat dialog is not updating with rolls instead outputting to a new chat card

### ISSUE THREAD

**Issue by NRschwier** [ironmonk88/monks-tokenbar#320]
[BUG] [Starfinder] When requesting group rolls the chat dialog is not updating with rolls instead outputting to a new chat card

**To Reproduce**
While in a starfinder world, request a party roll of any type and then click the roll button for the generated chat card.

**Expected behavior**
The rolls should update the original chat cards instead of creating new ones for each players rolls

**Comment by ironmonk88** [comment]
Duplicate of #159
