### ISSUE TITLE
[BUG] PF2E Lore skill not working

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-tokenbar#322]
The Lore roll doesn't seem to be working for MTB in PF2e system (Foundry v10, build 291, Pf2e 4.4.2, MTB 10.5). If you request a Lore roll from a token, the chat prompt appears normally, but clicking the dice button returns an"Error!" with the message, "Could not find function to roll" (toast notification and console log yellow "warning").

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
