### ISSUE TITLE
[BUG] Request Roll, Initiative

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#323]
A player clicking the chat card to roll initiative results in this error (player side, not GM side).

![image](https://user-images.githubusercontent.com/99844555/206920713-58c956f2-3766-4932-85ed-60d16af09d3f.png)

### Dice So Nice

A player clicking to roll with DSN active results in the chat card not updating, despite sending the info to the combat tracker. Same error as above.

![image](https://user-images.githubusercontent.com/99844555/206921067-8ea55e4b-4840-43bf-af69-f44da5267b0f.png)

![image](https://user-images.githubusercontent.com/99844555/206920868-4a15fbc0-a637-4a7e-9eb4-d95486f2b144.png)

Foundry 10.291
D&D 5e 2.0.3
Tokenbar 10.5
Dice So Nice 4.6.5

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
