### ISSUE TITLE
[BUG] "Allow active Combatant NPC to move" prevents drag movement in combat

### ISSUE THREAD

**Issue by DanielKispert** [ironmonk88/monks-tokenbar#324]
**Describe the bug**
If the setting "allow active combatant NPC to move" is turned on, players cannot drag their tokens in combat, instead they have to move with WASD

**To Reproduce**
1. Turn on the setting
2. be in combat
3. login as a player
4. try to drag your token

**Expected behavior**
The token can be moved with the mouse

**Screenshots**

**Please complete as much of the following information as possible:**
 - Foundry Version v10
 - System Pathfinder2e
 - Module version 10.5
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: yes, everything else disabled still leads to the error

**Additional context**

**Comment by ironmonk88** [comment]
I'm able to move both my token and NPC via the mouse when it's their turn in combat.

**Comment by DanielKispert** [comment]
more steps to reproduce:
1. I'm running Foundry 10.291 and Pathfinder2e 4.4.2. TokenBar is on 10.5
2. Created a new world with the Pathfinder2e Game System
3. activated only the TokenBar module
4. I did not touch the settings except for activating this one:
![grafik](https://user-images.githubusercontent.com/34270661/206935293-27807627-53cb-4a6d-b31b-fa0f2a8ef447.png)
5. created an empty scene, a NPC and a player character
![grafik](https://user-images.githubusercontent.com/34270661/206935354-d50c6871-fd2d-47ba-98d4-fef9ef7b7f83.png)
6. created a "player" user, gave them ownership of the player character
7. start combat, make it the player character's turn
![grafik](https://user-images.githubusercontent.com/34270661/206935403-b92efdaa-3d87-41f7-a834-7a53c29ec8cd.png)
8. log into the "player" account, try to move the token by dragging, it pings instead 
![grafik](https://user-images.githubusercontent.com/34270661/206935435-b7f19e62-affe-4b2b-a761-c6ca5b6b089b.png)
9.

**Comment by DanielKispert** [comment]
tested it in a completely new world and could also not reproduce it again, sorry for not properly checking module interactions before. Should be one of those.

**Comment by DanielKispert** [comment]
![grafik](https://user-images.githubusercontent.com/34270661/206935933-10ec3802-3886-4006-85f8-bb501346ac52.png)
Uncaught TypeError: game.users.get(...) is undefined
[Detected 2 packages: monks-tokenbar, lib-wrapper]
    allowNpc monks-tokenbar.js:502
    blockCombat monks-tokenbar.js:502
    allowMovement monks-tokenbar.js:518
    canDrag monks-tokenbar.js:121
    call_wrapper libWrapper-wrapper.js:616
    _canDrag#0 libWrapper-wrapper.js:189
    can foundry.js:27799
    _handleClickLeft foundry.js:28013
    _handleMouseDown foundry.js:27990
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerDown interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerDown interaction.min.mjs:8
    addEvents interaction.min.mjs:8
    setTargetElement interaction.min.mjs:8
    r interaction.min.mjs:8
    initPlugins core.min.mjs:8
    r core.min.mjs:8
    create core.min.mjs:8
    ro core.min.mjs:8
    e app.min.mjs:8
    #createApplication foundry.js:23356
    initialize foundry.js:23258
    initializeCanvas foundry.js:8094
    setupGame foundry.js:7929
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
monks-tokenbar.js:502:91

here's the error messages in case that helps

**Comment by ironmonk88** [comment]
Huh.  That is a strange error.  Considering there always has the be at least one user.
I can have it avoid that error message... but I have no idea how you'd get a world that has no users.

**Comment by DanielKispert** [comment]
> Huh. That is a strange error. Considering there always has the be at least one user. I can have it avoid that error message... but I have no idea how you'd get a world that has no users.
I had previously removed the default "Gamemaster" user and replaced it with another user with gamemaster rights. Since that user created the player actors, I went through the actor permissions for each and updated them (without changing anything, just going in and saving). After doing that, I was unable to reproduce the error anymore, so I suspect that this removed GM user was the cause.
