### ISSUE TITLE
[Feature Request] Add the option to add or remove actors from the token bar on right click

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-tokenbar#325]
Add the option to add or remove a token with a right click menu

![image](https://user-images.githubusercontent.com/98988680/207422866-ea848740-f0a1-44c7-8ccb-782d05e1de67.png)

**Comment by ironmonk88** [comment]
Technically you can only include remove.  
Since... the only way to get the context menu is if the token is already added.

**Comment by ironmonk88** [comment]
Should be added to the latest version.
