### ISSUE TITLE
[BUG] Post Combat Looting

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#326]
Converting a token to lootable after combat results in this error when the "Loot Entry" setting is targeting a specific MEJ journal; creating a new entry works as expected.

![image](https://user-images.githubusercontent.com/99844555/207477249-50daa08e-96d5-4e06-a97f-e149d4e27c0c.png)

![image](https://user-images.githubusercontent.com/99844555/207477271-6affe022-60f2-46d2-8d2e-2bb315e8916d.png)

Moto said Tokenbar 10.3 is where this setting works again after reverting.

Tokenbar 10.5
MEJ 10.6
Foundry 10.290 & 10.291
D&D 5e 2.0.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
