### ISSUE TITLE
[Feature Request] Support for Twilight: 2000 4e

### ISSUE THREAD

**Issue by Vcutter** [ironmonk88/monks-tokenbar#327]
Request for support of the Free Leagues Twilight: 2000 4e system, specifically the "roll request" for pass/fail of a skill roll integration with MATT.
The mechanics of the TW system are identical with the new Blade Runner rpg from Free League and the developer of Foundry module (Stefouch) is the same for both so there might be the possiblity of easily supporting both systems.

**Comment by ironmonk88** [comment]
Added in the latest version.
