### ISSUE TITLE
[Feature Request] Add XP Split Between PCS & PCs 

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#331]
A user is requesting the ability to have the option to have the XP split include allied NPCS, as RAW in 5e apparently.

**Comment by LukasPrism** [comment]
The party is gonna *love* animal companions and familiars stealing a share of the XP lol

**Comment by Crowguard** [comment]
@LukasPrism Don't look at me. I hate XP lol.

And I guess it's already possible; NPC's need to be friendly & owned by a player (use a dummy player if need be).
