### ISSUE TITLE
[BUG] Request Roll keybinding can include GM-Only rolls, despite a specific keybinding already existing for GM-Only rolls.

### ISSUE THREAD

**Issue by guldelox** [ironmonk88/monks-tokenbar#332]
**Describe the bug**
There are two keybindings, "Request Roll" and "Request Roll, GM Only". The GM-only roll request behaves as expected, but the regular roll request will default to a GM only request if that is the last one used. This seems incorrect - if there's a specific binding for GM-only rolls, then the regular roll request should not include that as a possible last-used roll.
This creates added friction in games, where I am switching between requesting public rolls from the players, but also making GM-only rolls. I have Roll Request bound to the R key, and GM-only requests bound to G.

**To Reproduce**
1. Bind "Request Roll" and "Request Roll, GM Only" to keys (in this example R and G respectively).
2. Press R. Observe that the selected roll defaults to "Public Roll".
3. Press G. Observe that the selected roll defaults to "GM Only".
4. Finish requesting the GM Only roll, making the chat message appear.
5. Press R. Observe that the selected roll is now "GM Only."

**Expected behavior**
It is understood that the "Request Roll" keybinding requests the last-used roll, however if there is a specific keybinding for GM-only rolls, it would seem that including GM-only rolls in the list of viable "last-used" rolls is incorrect.

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: v10 Build 291
 - System: D&D5e 2.0.3
 - Module Version: 10.5
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Problem exists even when only Monk's TokenBar is active.

**Additional context**
This is possibly a Feature request. Updating the Request Roll keybinding to ignore GM only rolls as an option, since a keybinding for it already exists. Or possibly include an option to impose that behavior.

**Comment by ironmonk88** [comment]
Closing this as the feature was added in a previous release.  If the previous roll was a self roll, then it will bump it down to a blind roll.
