### ISSUE TITLE
[BUG] Player tokens aren't automatically added to the tokenbar (wfrp4e)

### ISSUE THREAD

**Issue by orangebutblue** [ironmonk88/monks-tokenbar#333]
Player tokens aren't automatically added to the tokenbar (wfrp4).
They can be manually added to the token bar, via token settings -> "show on tokenbar" -> Include
However, the "default" setting doesn't add player tokens

**Comment by ironmonk88** [comment]
They're adding correctly for me.
Please check that the token is set to friendly disposition, and is owned by a player.

**Comment by orangebutblue** [comment]
![image](https://user-images.githubusercontent.com/4688096/218678334-85ebbf31-db56-43c1-a849-a93e26e3318e.png)

It's a Player Character token

**Comment by ironmonk88** [comment]
Can you open the console window (F12)
And type in `game.MonksTokenBar.debugEnabled = 2`
Then change the scene to one with a token that's supposed to be visible on the Tokenbar... and preferably very few other tokens, as it's going to list what it thinks about every token on the scene.
Find the line that says `DEBUG: monks-tokenbar |  Checking token ` that relates to the token in question, and send me a screenshot of what it says.

**Comment by orangebutblue** [comment]
My bad. it seems to be working when the disposition is set to friendly and only after switching the scene. Sorry to have wasted your time 😔
