### ISSUE TITLE
[BUG] Loot Entity Settings

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#334]
![image](https://user-images.githubusercontent.com/99844555/212421578-f98a65ca-2328-412e-b99c-3d1683b3a963.png)

The settings dropdown isn't rendering properly, and I'm unable to open it.

Foundry 10.291
D&D 5e 2.1.2
![image](https://user-images.githubusercontent.com/99844555/212421686-6fd95d6b-2694-42a1-9e19-5bb75696c205.png)

**Comment by ironmonk88** [comment]
Any errors in the console?
And what browser are you using?

**Comment by Crowguard** [comment]
No errors; Chrome 109.0.5414.74. Except now it seems to be normal again?

**Comment by kculver14** [comment]
I'm getting the same problem.

![image](https://user-images.githubusercontent.com/49567312/215236779-5030036c-f884-40ca-8fdb-4465379c0ef8.png)

Chrome: Version 109.0.5414.120 (Official Build) (64-bit)

No error messages in log

**Comment by ctbritt** [comment]
I'm getting an error message. it says, 
<img width="828" alt="CleanShot 2023-03-07 at 23 17 12@2x" src="https://user-images.githubusercontent.com/4516034/223618342-32fdcea2-6cc2-473e-a331-6c949b2abcb1.png">
And the dropdown is not rendering properly for me, either. Only modules enabled at MTB, Item Piles, socketlib, and libwrapper.

**Comment by sPOiDar** [comment]
I don't see any console errors, but perhaps it's not rendering correctly because of this weird markup:

```html
<div class="journal-select" tabindex="0">
  <div class="flexrow" style="font: 14px Signika, sans-serif;">
    <span class="journal-select-text">Convert tokens</span><i class="fas fa-chevron-down"></i>
  </div>
  <ul class="journal-list">
    <li class="journal-item convert-item selected" data-uuid="convert">
      <div class="journal-title">-- convert tokens --</div>
    </li>
    <li class="journal-item create-item">
      <div class="journal-title">-- create entry here --</div>
    </li>
  </ul>
</div>
```

Is this perhaps broken because it's using markup that's only supported by `Monk's Enhanced Journal` or something?

**Comment by Ikabodo** [comment]
Same issue as above.
![image](https://user-images.githubusercontent.com/7766890/234225060-53f59bd8-ab51-4766-9aa2-f967e4202efa.png)

**Comment by ironmonk88** [comment]
Fixed in the latest version.
