### ISSUE TITLE
[BUG] Tokens Are Converted to Lootable Even Though Their HP is Not Zero

### ISSUE THREAD

**Issue by KelSolaar** [ironmonk88/monks-tokenbar#336]
**Describe the bug**
After a combat end, if a NPC has still HP, e.g.  surrendered, escaped, it is still being prompted for being converted to lootable.
Note that I'm using **ItemPiles** here.

**To Reproduce**
1. Add NPC to combat
2. Begin combat
3. End combat
4. Prompt for lootable conversion occurs.

**Expected behavior**
Ideally, and given that NPC HP is not zero, the NPC should not be prompted for being converted.

**Screenshots**
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/99779/212752510-12e8f16d-89c2-46a2-a06c-bbfd17da5e24.png">

**Please complete as much of the following information as possible:**
 - Browser: N/A
 - Foundry Version: 10.291
 - System: DnD5e 2.1.1
 - Module version: 10.6
 - Are there any errors in the console: N/A
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: N/A

**Additional context**
Add any other context about the problem here: N/A

**Comment by KelSolaar** [comment]
A quick fix would be to change the following line: https://github.com/ironmonk88/monks-tokenbar/blob/main/apps/lootables.js#L17 to:

```javascript
                return c.actor?.token && c.token?.disposition != 1 && c.actor?.system?.attributes?.hp?.value == 0
```

I can make a PR if your want and add a setting to make the behaviour optional?

**Comment by ironmonk88** [comment]
Added setting in the latest release.
