### ISSUE TITLE
[BUG] Revealing Request Result

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#338]
When revealing a private roll, the players still are unable to see the number rolled.

https://user-images.githubusercontent.com/99844555/213901235-c7a9e121-5741-41da-8d58-57808385e632.mp4

Foundry 10.291
5e 2.1.1
Tokenbar 10.6

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
