### ISSUE TITLE
[BUG] Players Can't Request Rolls

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#339]
Players are unable to see the request roll buttons, despite it being enabled in the module settings.

![image](https://user-images.githubusercontent.com/99844555/214396660-e59db3da-a823-4087-a605-ab51e921a045.png)

![image](https://user-images.githubusercontent.com/99844555/214396738-1adf570b-8f8d-4b8b-8373-2d843d2f8a7d.png)

Foundry 10.291
Tokenbar 10.6
PF2 4.6.8

**Comment by ironmonk88** [comment]
By design.
It will allow players to request a roll through Macros though. So the GM has to set something up for them.

**Comment by Crowguard** [comment]
Got it, and noted. Thanks.
