### ISSUE TITLE
[PF2e] Request roll not using system roller

### ISSUE THREAD

**Issue by ScyllPoesis** [ironmonk88/monks-tokenbar#340]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but just a usability/consistency matter. Currently the roller prompt that comes up when players (or GMs) go to roll off of the group message is a simple dialog prompt. This means the players do not get the visual layout of their current modifiers and toggles that the native system rolls have. 

**Describe the solution you'd like**
It would be perfect to me if you would instead use the native roll prompts, the same way they are prompted from DCs within items or skill effects. Attached examples below.

As a bonus it would also be nice to have a setting to allow the actual chat cards for the individual rolls to go through, as they contain information on modifiers and roll breakdown, and some players enjoy seeing that information as opposed to just the total result on the group check card.

**Additional context**
Example of card that has a prompt hook encoded in the description:
![image](https://user-images.githubusercontent.com/40338743/214437131-114aea6e-a799-4b74-bf3a-de706c64acce.png)

Comparison of UX; the right was spawned by clicking the DC prompt in the chat card, the left via Request Roll:
![image](https://user-images.githubusercontent.com/40338743/214437264-0388977e-9dfc-4e50-978b-dcdb8a6e261d.png)

I've bounced around a few of these overviews,, but really love how this one has turned out, and have always been a big fan of your other contributions (MATT, of course). Cheers!

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
