### ISSUE TITLE
[BUG] Token Bar - Edit Stats list overlaps buttons if there are too many items in the list

### ISSUE THREAD

**Issue by FeistyMango** [ironmonk88/monks-tokenbar#341]
**Describe the bug**
 Once the Edit Stats dialog for Token Bar contains 7 stat items, the list overflows on top of the save button, preventing the user from being able to add anymore stats.

**To Reproduce**
1. Go to Settings Settings
2. Click Configure Settings
3. Scroll down the left nav pane
4. Click Monk's Tokenbar
5. Click Edit Stats button
6. Add 7 stats, then you will not be able to click the Save Changes button anymore

**Expected behavior**
Should provide either a way to resize the popout dialog or provided a scollable region within the dialog to prevent long lists from overflowing on top of the buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/3461388/216759925-cef1fecb-c0f3-4f22-8b78-1d8543e96c71.png)

**Please complete as much of the following information as possible:**
 - Chrome v109.0.5414.120 (Official Build) (64-bit)
 - Foundry Version v10.291
 - D&D5e v2.1.4
 - Monk's Tokenbar v10.6
 - No console errors
 - `Find the Culprit` - Confirmed this happens when only running this module

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.

**Comment by FeistyMango** [comment]
Confirmed this is working. Thanks!
