### ISSUE TITLE
[BUG] Selecting multiple skills for RR doesn't work

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-tokenbar#345]
Can confirm that selecting multiple skills for an MTB request roll does not work on a Mac. Foundry v10 build 291, Pf2e 4.7.4 blank world with nothing but MTB, libWrapper, and Socketlib enabled. Using Chrome 109.0.5414.119. No console errors either.

**Comment by ironmonk88** [comment]
Should work in the latest version using the meta key?

**Comment by weepingminotaur** [comment]
yep, tested and it works now!

**Comment by ironmonk88** [comment]
Working in the latest version, closing the ticket.
