### ISSUE TITLE
[Feature request] show passive investigation

### ISSUE THREAD

**Issue by Fridan99** [ironmonk88/monks-tokenbar#346]
**Is your feature request related to a problem? NO.**

It would be nice to be able to include the passive Investigation value into the monk token bar.

There are many GMs that use the passive of this skill, and feats like observant already show that it is useful in its passive form.

**Comment by Crowguard** [comment]
@Fridan99 You can add that in the module settings.
![image](https://user-images.githubusercontent.com/99844555/220494718-35f8a7f7-e5f5-4e97-ba71-3912dd32c248.png)

**Comment by Fridan99** [comment]
Ahhh wow, I didn't know about that option. 🤣 sorry for opening such an unnecessary thread. 

Thanks for the reply.
