### ISSUE TITLE
Request: Copy and Paste stats settings 

### ISSUE THREAD

**Issue by Co0nmz** [ironmonk88/monks-tokenbar#348]
Right now you have to manually copy and paste the stats settings for the stats shown above the token bar actor image for every single actor. This is especially tedious because the icon selection window is very unorganized.

It would be nice to have a little button like "apply to all actors" to simply apply the chosen settings to all other actors shown on the token bar.

**Comment by ironmonk88** [comment]
So like, the Edit Stats button in the Tokebar settings, that will affect all tokens?
![image](https://user-images.githubusercontent.com/75920956/220774460-bf09e289-8837-41f3-bc85-6d7886ad8cee.png)

**Comment by Co0nmz** [comment]
I don't know, it doesn't say that in the description ;)

I guess this request is useless then, but I suggest adding a hint in the Individual settings menu that there is this option available. Because I use your mod for half a year now and didn't know this :D

**Comment by ironmonk88** [comment]
Added additional text to make it clearer that there are general settings
