### ISSUE TITLE
[BUG] assign xp in Starfinder

### ISSUE THREAD

**Issue by Carantin** [ironmonk88/monks-tokenbar#349]
Hello good.
A few days ago the icon to assign experience for Starfinder disappeared, until recently it worked quite well, I leave you a photo.
![xp](https://user-images.githubusercontent.com/85190325/221177071-52c71f6f-76e7-40c3-956f-f14330b54dc6.PNG)

In others how Pathfinder work normaly.
![xp2](https://user-images.githubusercontent.com/85190325/221178271-177fa4f0-d701-43f2-b23b-a4ba7ea80288.PNG)

Thanks

**Comment by Crowguard** [comment]
I can confirm its also missing in PF1 after the one user report there; 
![image](https://user-images.githubusercontent.com/99844555/222010034-0b750cb9-4fa0-4dc7-9ed2-b9a1d47f255f.png)

Tokenbar 10.8

**Comment by madcatprimary** [comment]
I can corroborate this issue. Thought it may have moved to a different module, but can't find any evidence that's true. 
![image](https://user-images.githubusercontent.com/67210079/222919090-9aebb6a0-f5b7-4e5f-be52-aff2acbe6d44.png)
Same version info as above.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
