### ISSUE TITLE
[Bug] Request Tool Roll missing?

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#35]
I can see the request Death-Save option and assume to find the tool-roll there too. But I can't see it.

![grafik](https://user-images.githubusercontent.com/44159008/108714054-5aa00200-7519-11eb-8ff7-82f31c716019.png)

Version should be good:
![grafik](https://user-images.githubusercontent.com/44159008/108714279-a783d880-7519-11eb-913a-404da0154ad1.png)

**Comment by ironmonk88** [comment]
Version 1.0.17, hasn't been released yet.  I update the changelog ahead of time to remember what's going into the next version.  Just in the middle of testing it, but should be out shortly.  Still working out bugs when someone doesn't have the toolkit specified.

**Comment by tagnullde** [comment]
I really try to spot errors on my part. But these little details often go unnoticed. Sorry for the trouble. xD

**Comment by ironmonk88** [comment]
No worries.  I always appreciate the effort this community puts in to find bugs.  And it's pretty cool that someone actually reads the changelog!  :-)
To be fair... it's not entirely clear, so I'll update the changelog to list the changes in development.
