### ISSUE TITLE
[BUG] Group actor roll results in error

### ISSUE THREAD

**Issue by metodi022** [ironmonk88/monks-tokenbar#350]
**Describe the bug**
This issue happens in the latest _D&D5e_ system. When you do a roll request for a token that belongs to _group_ actor, and you click the roll button die, an error "Error!" appears.

**To Reproduce**
1. Create a group actor from Create Actor -> Type = Group
2. Place the group actor's token on the board.
3. Select that token and request a roll.
4. When the request message appears in chat, click the button to roll the die.
5. The error "Error!" appears instead of a result.

**Expected behavior**
The roll request in the chat should include instead all actors that belong to the group actor. The group actor should not appear in the roll request.

**Screenshots**
https://imgur.com/a/gNHVF61

**Please complete as much of the following information as possible:**
 - Browser Chrome, Firefox, Edge
 - Foundry Version 10 - Build 291
 - System D&D5e 2.1.5
 - Module version 10.8
 - No errors appear in the developer console.
 - I have _not_ used `Find the Culprit`.

**Additional context**
I think the problem occurs because the D&D5e system recently introduced a new actor type called "Group". This group actor functions like a party token. It contains the other actors.

**Comment by ironmonk88** [comment]
Fixed in the latest version.
