### ISSUE TITLE
[BUG] No results on clients with `disable game canvas` enabled

### ISSUE THREAD

**Issue by Sinled** [ironmonk88/monks-tokenbar#351]
**Describe the bug**
Final roll result is not visible on clients with disabled canvas.  But if i click 3 dots in gm chat - result becomes visible. 
For clients that have canvas enabled - everything works correctly. (There also three dots visible while 3d dice are rolled, but then they are replaced with final result)

**To Reproduce**
1. Have a client with `disabled game canvas` enabled
2. Request roll
3. Click dice on client in chat message
4. Final result is not visible

**Expected behavior**
Final roll result should appear on clients with disabled game canvas without additional clicks from GM

**Screenshots**
<img width="285" alt="roll" src="https://user-images.githubusercontent.com/1402135/223534061-72c6e9b7-acf1-459c-a963-5ca084dfbd12.png">

**Please complete as much of the following information as possible:**
 - Browsers - tried in both latest chrome and mobile safari 16
 - Foundry Version v10
 - System D&D5e 
 - Module version - 10.8
 - no errors in console

**Comment by Sinled** [comment]
It seems you need to add check for core setting, such snippet solved my problem

```
const shouldRevealDice = (game) => {
    if (!game.settings.get("core", "noCanvas") || !game.dice3d) {
        return true;
    }

    return game.settings.get("dice-so-nice", "immediatelyDisplayChatMessages");
}
```

**Comment by ironmonk88** [comment]
Fixed in the latest version.
