### ISSUE TITLE
XP Calculator Seems Broken

### ISSUE THREAD

**Issue by Nuku** [ironmonk88/monks-tokenbar#352]
When the player party is not 4, I'm not sure it's calculating properly. A combat that showed up as 'low' once tried to give 100 xp to the party, when it should giving closer to 60 xp as per https://2e.aonprd.com/Rules.aspx?ID=497

The difficulty of the battle should determine the xp given out, not any amount of dividing among the players, just the difficulty.

**Comment by JDCalvert** [comment]
This would be fixed by #343.

**Comment by josh-koonce** [comment]
Do you know when this fix will be pushed live?

**Comment by ironmonk88** [comment]
Fixed in the latest version
