### ISSUE TITLE
[BUG]? Request Tool Rolls

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#353]
Rolls made for tool requests only work when using the SRD compendium versions of those items, not any created using Beyond Importer or self-made.

https://user-images.githubusercontent.com/99844555/227406100-6e06cbf5-1496-4d14-81a7-117040eceec2.mp4

Tokenbar 10.8
D&D 5e 2.1.5

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
