### ISSUE TITLE
[BUG] Issues creating loot using ItemPiles

### ISSUE THREAD

**Issue by StevenEvans1966** [ironmonk88/monks-tokenbar#355]
**Describe the bug**
Several issues
1. side bar loot itempile actor is empty
![2023-03-24 16_42_23-D D • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/81326195/227589431-e148e124-315e-4c71-8838-c1fd12a7c018.png)
2. canvers item is missing cash
![2023-03-24 16_43_22-D D • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/81326195/227589617-1bdbd0eb-94cd-4ae6-b532-251c9e22b5a6.png)

**To Reproduce**
Create loot either by ending combat or using token layer button e.g.
![2023-03-24 16_41_33-D D • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/81326195/227589036-044f8a2f-62c8-4919-ab7e-bd95f3a69c85.png)

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version v10.291
 - System D&D5e
 - Module version 10.8
 - no console errors

Note Monk's Enhanced Journal must be installed.

### Active Modules
Compendium Folders v2.5.7
D&D Beyond Importer v3.4.7
DDB Import (Shared Compendiums) v2.0
Item Containers v10.0.9
Item Piles v2.5.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
libWrapper v1.12.12.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
socketlib v1.0.12 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Module Management+ v2.1.6 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Enhanced Journal v10.14 [Bugs URL](https://github.com/ironmonk88/monks-enhanced-journal/issues)
Monk's TokenBar v10.8 [Bugs URL](https://github.com/ironmonk88/monks-tokenbar/issues)

**Comment by ironmonk88** [comment]
Fixed in the latest version.
