### ISSUE TITLE
addition to "Request Roll" request

### ISSUE THREAD

**Issue by Weskernation** [ironmonk88/monks-tokenbar#357]
**When using "Request a roll.**

- Would it be possible to add "Thieves' Tools" to the list? and the program auto checks for the tools of the requested player. With checkbox adds proficiencie bonus, if there are any.
- A line to fill in a text "When item is not present"

- Thieves' Tools would be the standard item, through a dropdown menu we can select the other tools. 

On the bottom of this list there is "Specify" where we can type in a word where the module checks for. If we want a check to be made with e.g. a hammer or crowbar. We can type in/drag the name of the item

![Request_Roll_Request](https://user-images.githubusercontent.com/119079571/216836202-f52db153-8be8-40d3-ba37-280e6b73751d.jpg)

If on the short term Thieves' Tools only are added that would help most since checks with this tool are asked frequently

**Comment by ironmonk88** [comment]
Closing this as it was added awhile ago.
![image](https://github.com/ironmonk88/monks-tokenbar/assets/75920956/a9242a2c-bb88-487c-987f-c8f692893ecd)
If any of the selected tokens has a tool that can be used it will get added to the list.  And Ctrl click will allow you to select a back up roll request.  Players will be presented with the option of which to use, provided they have that tool.
