### ISSUE TITLE
[BUG] Request Multiple Rolls

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#358]
User is reporting that a multiple choice request only displays the first skill selected to the GM, regardless of which one the player actually selected to roll. I haven't been able to replicate it so far.

Its off-screen, but the skill selected in the video was Nature, and displays Perception.

https://user-images.githubusercontent.com/99844555/231239330-4d1893a6-7807-4419-9646-5e5d28f6470f.mp4

Tokenbar 10.9
5e 2.1.5

**Comment by ironmonk88** [comment]
Fixed in the latest release
