### ISSUE TITLE
[BUG] Stats disappearing when customized per token

### ISSUE THREAD

**Issue by LukasPrism** [ironmonk88/monks-tokenbar#360]
If you use the context menu on a token portrait in MTB to customize the stats, those are saved as flags on the token, even if linked to an actor. If you delete the token and drag it out again, the stats have reset.
For linked tokens the flags would ideally be stored on the actor, meaning they are persistent and you won’t lose them if you change scenes. 

Thanks

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
Stats have been moved to the actor.
