### ISSUE TITLE
[BUG] Starfinder, Unable to see roll

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#363]
In Starfinder, you're unable to double click the roll result to see what the dice roll was.

### PF2 Example
![image](https://github.com/ironmonk88/monks-tokenbar/assets/99844555/3f381a3e-14af-40c8-b57f-a639ebe82631)

### Starfinder Example

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/685dd31a-1902-4f49-ae0b-e8e3ccb4d5b0

No errors
Foundry 10.291
Tokenbar 10.10
Starfinder 0.23.0

**Comment by Crowguard** [comment]
This might be part of the issue of #159. I just was not 100% sure whether this counted as a separate issue or not.

**Comment by ironmonk88** [comment]
Fixed in the latest version.
