### ISSUE TITLE
[BUG] Convert to Item Piles, Loot Entity not saving.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#365]
The setting dropdown here doesn't seem to save.

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/1603ec39-8f7b-4739-9000-0116b2c6124a

Manually selecting it after combat results in "Could not find loot entity".

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/e1ae94a0-dab9-4395-b2b5-4d4563dd7005

Tokenbar 10.11
Item Pile 2.6.12

**Comment by ironmonk88** [comment]
Fixed in the recent release.
