### ISSUE TITLE
[BUG] MATT, Tokenbar Targeting.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#366]
* Assign Xp
* Request Contested Roll
* Request Roll

`This Tile` snuck in to the targeting here at some point for these actions.

![image](https://github.com/ironmonk88/monks-tokenbar/assets/99844555/50e53208-b900-4ec3-ab0d-2a3be2c450d4)

MATT 10.20
Tokenbar 10.11

**Comment by ironmonk88** [comment]
Fixed in the recent release.
