### ISSUE TITLE
[BUG] Pf2e - adding exp causes extreme CPU spike

### ISSUE THREAD

**Issue by DawidIzydor** [ironmonk88/monks-tokenbar#367]
**Describe the bug**
Adding experience using the XP Dialog causes extreme CPU spike, including crashing the server

**To Reproduce**
1. Enable XP dialog
2. Start an encounter with at least one PC
3. End the encounter and add exp
4. After clicking "add exp" in the chat CPU spikes rapidly, with multiple players doing it at once it crashes the server

**Expected behavior**

**Screenshots**
Screenshot of a snapshot taken in firefox
![obraz](https://github.com/ironmonk88/monks-tokenbar/assets/30767613/c0cd2510-011a-4fd1-bd89-b2445ed4090d)

**Please complete as much of the following information as possible:**
 - Browser firefox 113.0.2
 - Foundry Version 10.291
 - System Pathfinder 2e v 4.12.2
 - Module version 10.11
 - Are there any errors in the console lots of these warnings
 "Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    logCompatibilityWarning commons.js:1692
    get data commons.js:11759
    lookupCompatibility SpreadsheetController.js:87
    applyModuleManagementColors index.js:51
    applyModuleManagementColors index.js:49
    async* index.js:12
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5153
    _render foundry.js:5822
    render foundry.js:5067
    _onSettingsButton foundry.js:76701
    jQuery 9
    activateListeners foundry.js:76682
    _render foundry.js:5138
    _render foundry.js:60343
    _render foundry.js:60113
    render foundry.js:5067
    initializeUI foundry.js:8069
    setupGame foundry.js:7931
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675"
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. tested on a blank word with only the tokenbar module active, the CPU usage peak was smaller than on live world but still notable

**Additional context**

**Comment by ironmonk88** [comment]
Fixed in the recent release.
