### ISSUE TITLE
Respect Anonymous settings to not spoil creature names

### ISSUE THREAD

**Issue by LukasPrism** [ironmonk88/monks-tokenbar#375]
Currently if a GM is using Anonymous to hide creature/npc names from the party, MTB will spoil that name on a saving throw or contested roll. 

Anonymous has an API on its package page (at the bottom):
https://foundryvtt.com/packages/anonymous

Here's a snippet of how it's used in midi:

```js
function getTokenPlayerName(token) {
    if (!token)
        return game.user?.name;
    if (installedModules.get("anonymous")) { //installedModules == game.modules
        //@ts-expect-error .api
        const api = game.modules.get("anonymous")?.api;
        if (api.playersSeeName(token.actor))
            return token.name;
        else
            return api.getName(token.actor);
    }
    return token.name;
}
```

Hopefully a pretty easy fix? Many thanks again for your wonderful modules.

**Comment by ironmonk88** [comment]
Added to the latest version
