### ISSUE TITLE
Adding NPCs

### ISSUE THREAD

**Issue by BagOfTips** [ironmonk88/monks-tokenbar#377]
**Is your feature request related to a problem? Please describe.**
I use a low of NPCs to support my party of 2. I have always felt the option to add friendly NPCs within the party was lacking.

**Describe the solution you'd like**
When an NPC is set to friendly, they should appear on the tokenbar.

**Comment by ironmonk88** [comment]
![image](https://github.com/ironmonk88/monks-tokenbar/assets/75920956/ee2488d7-7712-425f-9ef2-281d2377003a)

**Comment by ironmonk88** [comment]
Closing this as there's a solution to the issue.
Automatically adding friendly NPCs could potentially add too many.  But you can add them manually if you want to.
