### ISSUE TITLE
[BUG] PF2e Perception Skill Doesn't Work With "Request For Roll" Feature

### ISSUE THREAD

**Issue by josh-koonce** [ironmonk88/monks-tokenbar#379]
**Describe the bug**
When using the "Request a Roll" feature, it works normally in PF2e EXCEPT for Perception, where it reports "Could Not Find Function to Roll". All other attributes and skills seem to work normally.

**To Reproduce**
1. Press Alt-Shift-R to request a roll from a token player
2. Use Perception
3. Send the request with roll
4. See the error

**Expected behavior**
A Perception roll to happen.

**Please complete as much of the following information as possible:**
 - Foundry Version 11
 - System Pathfinder2e
 - Module version 10.12
 - No red errors, just the yellow warning with text above

**Comment by Silvertower** [comment]
This happens with module version 11.01 as well.

**Comment by josh-koonce** [comment]
True. I upgraded and tried it today and can confirm.

**Comment by this-gavagai** [comment]
At some point, the location of the `SimpleStatistic` object for the Perception attribute changed on the actor. I've made a PR with working code.

**Comment by josh-koonce** [comment]
Thank you so much! God bless coders!
