### ISSUE TITLE
[Bug] Request Thief's Tools Roll throws error

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#38]
Reproduce:
1. Ask PC to Roll a Thief's Tools check
2. Player clicks "roll" in chat
3. Nothing happens and console presents the following error

![grafik](https://user-images.githubusercontent.com/44159008/109123933-a84f8100-774a-11eb-9c5e-131273fa3818.png)

Works with other Tools though:

![grafik](https://user-images.githubusercontent.com/44159008/109124764-97ebd600-774b-11eb-9516-b1c420950f2d.png)

**Comment by ironmonk88** [comment]
Tools are a bit of a weird thing.  My guess is that the character in question doesn't have that tool available.  Or it couldn't find the tool when it went to use it.  I'll update the code to be more informative about it.

**Comment by ironmonk88** [comment]
Version 1.0.18 just released that hopefully addresses that.  I'm not sure it's fixed per say but it should give you a better idea of what's happening rather than throwing an error.

**Comment by tagnullde** [comment]
When requesting the roll it says two things:

![image](https://user-images.githubusercontent.com/44159008/109412303-6d965480-79a7-11eb-84d1-87b995b45191.png)

The latter however isn't true. It's at least in her inventory and equipped.

![image](https://user-images.githubusercontent.com/44159008/109412268-4770b480-79a7-11eb-81c2-287b5e2d5f05.png)

**Comment by ironmonk88** [comment]
Found out the issue.  I was trying to find the item based on the core compendium id.  But if that's not available then I'm falling back on the id of the item itself.  Fix should be available with the next release.

**Comment by ironmonk88** [comment]
1.0.21 has released.  Let me know if this is fixed now.

**Comment by tagnullde** [comment]
It works now.
But it seems it's now compatible with Mars5e (or the other way around). Just assuming because of the popout instead of right-clicking for advantage and disadvantage. But it's fine for me. Thanks. 

![image](https://user-images.githubusercontent.com/44159008/110525788-4c570600-8115-11eb-9ca9-1cc1f3c49663.png)
