### ISSUE TITLE
Tokens converted to lootable with Item Piles not going transparent

### ISSUE THREAD

**Issue by ChobitsCrazy** [ironmonk88/monks-tokenbar#382]
**Describe the bug**
After combat completing and prompting for converting tokens to item piles, select to convert the tokens and the tokens no longer will show transparent. I believe this started after the mod split but not quite sure. This is a combination of mods:
Monk's Tokenbar
Monk's Bloodsplats
Item Piles

**To Reproduce**
1. Enter combat with a token that has loot
2. Complete combat and select option to convert tokens to lootable
![image](https://github.com/ironmonk88/monks-tokenbar/assets/21301107/bb718cd9-417b-4615-bf9d-9248ebe1955e)
3. Token does not change to transparent
![image](https://github.com/ironmonk88/monks-tokenbar/assets/21301107/8fefcd9b-7640-4df8-b028-3909a1ff8acd)

**Expected behavior**
In the older version the token would go transparent as such:
![image](https://github.com/ironmonk88/monks-tokenbar/assets/21301107/7cc09880-1368-4a3d-98b2-5b69e086db88)
It's a bad picture but the orc token was made transparent for looting.

**Please complete as much of the following information as possible:**
 - Foundry Version v10.291
 - System D&D5e
 - Module version 10.9
 - Are there any errors in the console No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Only these 3 modules are installed.

**Comment by ironmonk88** [comment]
That's working as expected now.  It wasn't working properly before.
If you convert the token, then you can't make that token transparent, because there would be nothing for the players to click on.
And changing of the token icon is up to Item Piles.  If Tokenbar tried to do anything then it would get in the way of whatever Item Piles chooses to do when an actor is converted to loot.

**Comment by ChobitsCrazy** [comment]
Thank you for the response Ironmonk, I'm not sure if item piles will convert the token icon when converted to lootable that I can find. So I'll have to wait for that functionality in the future.
