### ISSUE TITLE
[BUG] Convert to Item Pile, Quantity

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#384]
Converting items to a new Item Pile is seems to be losing the quantities.

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/2b038023-3f8a-4946-9554-caa70f50f40d

### MEJ

Works as expected. Two items with the name appended to (4)

![image](https://github.com/ironmonk88/monks-tokenbar/assets/99844555/adf0f2ec-fdd7-42dd-99fc-ba384a0d3d28)

### Item Pile

Two items. No name change.

![image](https://github.com/ironmonk88/monks-tokenbar/assets/99844555/599ac5a8-fe00-469c-b0ef-072ecea23a7e)

### Info

Tokenbar 11.01
Item Pile 2.6.16
Foundry 11.302

User reported it on Foundry v10.291, Pathfinder 1E v0.82.5, MEJ v10.17, MTB v10.12, Item Piles v2.6.16

**Comment by ironmonk88** [comment]
Fixed in the latest version.
