### ISSUE TITLE
[BUG] Convert to Item Pile fails without MEJ

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#385]
Despite having the loot settings pointed to Item Piles, its failing to bring up the loot window without MEJ active. Works as expected with MEJ active, seen in #384.

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/ad4a875f-21c8-4737-abc0-61047c329002

Tokenbar 11.01
Item Pile 2.6.16
Foundry 11.302

**Comment by ironmonk88** [comment]
Fixed in the latest version.
