### ISSUE TITLE
[BUG] Request Roll, PF2 Perception

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#386]
https://github.com/ironmonk88/monks-tokenbar/assets/99844555/3b5c6689-8fb2-4125-b381-05b4b8218e35

Tokenbar 11.01
PF 5.0.0
Foundry 11.303

**Comment by this-gavagai** [comment]
Duplicate of #379

**Comment by Crowguard** [comment]
So it is. Thank you.
