### ISSUE TITLE
[BUG] TokenBar request for Perception rolls in PF2E- apologies, found duplicate bug reported already #379

### ISSUE THREAD

**Issue by Keshyr** [ironmonk88/monks-tokenbar#389]
**Describe the bug**
When using Request Roll (or contested roll) from TokenBar, the Chat card populates correctly, but when the die is clicked to do the roll, it changes to "Error!" and a yellow Warning message pops up ....
    **tokenname : actorname : Could not find function to roll.**
... this happens even on a fresh PF2E world, with only TokenBar installed and active.  Only requests for Perception cause this, other skills work fine.

**To Reproduce**
1. Go to TokenBar
2. Click on Request Roll
3. Click on D20 shadow in chat card
4. See Error!

**Expected behavior**
Perception rolls to work properly like the rest of the skills when a roll is requested.

**Screenshots**
![brokenperception1](https://github.com/ironmonk88/monks-tokenbar/assets/139276912/367437fa-b6bc-4b4f-9fe7-64ff73a14ab0)
![brokenperception2](https://github.com/ironmonk88/monks-tokenbar/assets/139276912/0e687409-083e-4b92-8ae6-6c0169034ed0)
![brokenperception3](https://github.com/ironmonk88/monks-tokenbar/assets/139276912/9e837e5e-9cec-4bde-a677-30a7ed3f4e3a)
![brokenperception4](https://github.com/ironmonk88/monks-tokenbar/assets/139276912/c1ca813d-f498-41f0-85d6-85154462d87f)

**Please complete as much of the following information as possible:**
 - Browser Edge
 - Foundry Version 11.305
 - System PF2E
 - Module version 11.01
 - Are there any errors in the console  - no error, just the warning - see brokenperception4 above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction - no, because it happens even on a fresh world with no other modules.

**Additional context**

**Comment by ironmonk88** [comment]
All good.
Closing as a duplicate though.
