### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by franckflo** [ironmonk88/monks-tokenbar#390]
**Describe the bug**
At the end of a combat, when calculating the experience, unchecking some adversaries does not automatically adjust the experience total like it used to.

**To Reproduce**
1. Start a Combat
2. End a Combat
3. Accept to open the XP panel
4. Try to uncheck some of the opponents, the XP total doesn't adjust

**Expected behavior**
As we uncheck some of the opponents, the Xp total gained should adjust.

**Screenshots**
![image](https://github.com/ironmonk88/monks-tokenbar/assets/80221412/a43525a2-d95e-4d73-9c4d-afcbb7a3f78d)

After unchecking some opponents, the total is the same: 
![image](https://github.com/ironmonk88/monks-tokenbar/assets/80221412/fd7123e1-dfb8-47ee-af13-550f4e9edabf)

**Please complete as much of the following information as possible:**
 - Chrome / FLC / Brave / Opera GX
 - Foundry Version 10.291
 - System DnD 5e 2.2.2
 - Module version 10.1
 - Are there any errors in the console   Not that I could see
 - Have you tried using `Find the Culprit` : Yes, issue persists with only Token Hotbar enabled.

**Additional context**
Thanks for this very useful Module, and all the others !

**Comment by ironmonk88** [comment]
Fixed in the latest version.
