### ISSUE TITLE
[BUG] Blind GM rolls not working with Dice So Nice (no ghost dice)

### ISSUE THREAD

**Issue by Shayulghul** [ironmonk88/monks-tokenbar#391]
**Describe the bug**
If I request a public roll, Dice So Nice works correctly (dice renders on both GM and player clients). If I request a blind GM roll, Dice So Nice doesn't render any dice, which should be the ghost dice. A standard blind roll from the chat renders the ghost dice correctly. I’ve tested this in multiple games. I also tried LMRTFY, and the ghost dice render correctly for blind rolls.

**To Reproduce**
1. Turn on “Show Ghost dice for hidden rolls” setting for Dice So Nice.
2. Choose “Public Roll, Results Hidden.”
3. Player client clicks chat button.
4. Dice rolls in GM client but doesn't in player client. No 3D dice roll on the player client. The dice roll on the GM side correctly.

**Expected behavior**
I would like it if Dice So Nice could show the ghost dice for my players. 

**Settings:**
- Chrome Version 114.0.5735.198
- Foundry v10.303
- System: D&D 5E: 2.2.2
- Modules:
-     Dice So Nice!
-     Monk’s TokenBar

**Comment by ironmonk88** [comment]
Fixed in the latest version.

**Comment by mfozz** [comment]
The ghost dice still aren’t working for me in multiple games. I jumped into my test game to detail the behaviors a bit further.

It’s interesting to note that the roll behaviors don’t match the standard Foundry roll categories. Public Roll and GM Only Roll do match the standard Foundry behaviors, but the “Results Hidden” options don’t. I’ve listed the behaviors below. Note that “Private Roll, Results Hidden” and “GM Only Roll” appear to be doing the same thing.


“Public Roll”
- Working as expected (same as standard Foundry)

“Public Roll, Results Hidden”
(Issue: No dice animation for player)
	1.	DM chooses options and clicks Request
	2.	Request for roll appears in chat for GM and Player
	3.	Player rolls from chat
	4.	DSN animation triggers for GM only
	5.	Dice result appears in chat for player and GM


“Private Roll, Results Hidden”
(Issue: No roll option for player, so no dice animation triggers for player)
- The roll request appears in chat for the GM only. 
- The player doesn’t see a roll option
- No dice animation triggers for the player if the GM rolls it.

	Expected Behavior: I think this option should be mirroring the standard “Private GM Roll.” For example, if I choose Private GM Roll from the standard chat roll options, ghost dice roll for the player and regular dice roll for the GM. The GM sees the result in chat, and the player sees question marks in the chat result.


GM Only Roll
- Working as expected (same as standard Foundry)
