### ISSUE TITLE
Inline Support

### ISSUE THREAD

**Issue by perrinaz** [ironmonk88/monks-tokenbar#393]
**Is your feature request related to a problem? Please describe.**
No problem.  This is ease of use.  If it exists already (as a feature or request) I couldn't find it so...

**Describe the solution you'd like**
Inline support.  At least with PF2e, if the GM puts a line like: @Check[type:fortitude|dc:20|basic:true] the system puts in a clickable link that rolls.  It would be nice if a similar command could be put in that puts up a roll request through the tokenbar where the various options are already pre-selected.  It could have an option for "all" or "target" 

**Additional context**
The sample roll line comes from the pf2e style guide here [https://github.com/foundryvtt/pf2e/wiki/Style-Guide](https://github.com/foundryvtt/pf2e/wiki/Style-Guide)

**Comment by ironmonk88** [comment]
Already exists.
`@Request[perception dc:10 silent fastForward rollmode:gmroll]{flavor text}`
![image](https://github.com/ironmonk88/monks-tokenbar/assets/75920956/4a67c164-7bd2-4fd8-ba4b-570efbbcaa11)
![image](https://github.com/ironmonk88/monks-tokenbar/assets/75920956/3ee361d4-4628-48cc-8eb9-e63aa3143b71)

**Comment by perrinaz** [comment]
OH kewl!  Wait.. where is that header supposed to show up?  I'm trying to add the save request in a new monster NPC sheet action description

**Comment by ironmonk88** [comment]
NPC sheets don't have the button.  Journal Entries do though.
Closing this as the feature exists.
