### ISSUE TITLE
[BUG] PF2e Request Roll (Perception) error

### ISSUE THREAD

**Issue by PlaguedGuard** [ironmonk88/monks-tokenbar#395]
**Describe the bug**
Error using Request Roll for Perception in the PF2e. When trying to pass a Perception check, the message "Error!" appears

**To Reproduce**
1. Set up a Request Roll (Perception)
2. Select token and request a roll
3. When the request message appears in chat, click the button to roll the die.
4. The error "Error!" appears instead of a result.

**Expected behavior**
A Perception check should have occurred, comparing the result of the die roll against the difficulty of the check.

**Screenshots**
https://i.ibb.co/kmQ813F/2023-07-25-193648070.png

**Please complete as much of the following information as possible:**
 - Foundry Version: v11 - Build 306
 - System: Pathfinder 2e, v5.2.2
 - Module version: 11.01

**Comment by ironmonk88** [comment]
Closing, duplicate of #379
