### ISSUE TITLE
[BUG] Perception checks are broken [Pf2e, Maybe More]

### ISSUE THREAD

**Issue by ApocalypseDoggo** [ironmonk88/monks-tokenbar#398]
**Describe the bug**
Using the request a roll feature to request a perception check in Pf2e results in an error

**To Reproduce**
1. Open world with pf2e as system
2.  use the request roll button on token bar
3. choose perception with any token queued
4. click roll with request
5. see error

**Expected behavior**
module would use  the appropriate perception modifier of the selected tokens and then roll a dice to determine the end result

**Screenshots**
![image](https://github.com/ironmonk88/monks-tokenbar/assets/140922433/578872e3-dff9-4023-a452-17896c517044)

**Please complete as much of the following information as possible:**
 - Browser: Foundry.exe
 - Foundry Version: v11
 - System: Pf2e
 - Module Version: Most Recent as of posting
 - Are there any errors in the console: (Token Name) Could not find function to roll
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No, but no modules have changed, this only started very suddenly when i updated to V11. The Perception attribute likely just changed names and needs to be updated.

**Additional context**

**Comment by tehguitarist** [comment]
There is a deprecation in the latest version of the pf2e system that moves away from CORE.PF2E.attributes to look for perception, but there was a temporary fix put in place. What version of pf2e are you on, and are you getting any console errors?

**Comment by ApocalypseDoggo** [comment]
5.2.3. and just this one

![image](https://github.com/ironmonk88/monks-tokenbar/assets/140922433/aeff9a75-710f-4222-b2be-60068b7b275f)

**Comment by ironmonk88** [comment]
Closing this as it's old and I can't replicate it.
