### ISSUE TITLE
[BUG] Compatibility with Ready Set Roll - Quick Roll Support

### ISSUE THREAD

**Issue by DrWiFi** [ironmonk88/monks-tokenbar#399]
**Description**
I do not know which module is not working properly, so I am posting in both.
Monks Token Bar: https://github.com/ironmonk88/monks-tokenbar/issues/399
Ready Set Roll 5e: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/242

The Quick Roll Ability Feature of RSR is not bypassing the default roll prompt when a roll is requested through MTB. 
RSR Correctly bypasses the prompt from all other locations I have tested. MTB will bypass the prompt IF the - or + is clicked on the chat window request.

**Steps to Reproduce**
1. Open Request Roll from Monk's Tool Bar
2. Request any roll
3. In the Chat window, click the d20 icon
4. Default Roll prompt appears

**Expected behavior**
The Ability Check or Saving throw should roll without the prompt as it does other places

**Versions**
 - Module: RSR - [2.1.2] / MTB - [11.02]
 - dnd5e: [2.2.2]
 - Foundry: [11.307]

**Other Modules**
- Ready Set Roll
- Monk's Token Bar

<img width="1079" alt="Screenshot 2023-08-06 at 6 50 58 PM" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/50341031/68c802c8-4dc2-45dc-9622-b1bfdc966225">

**Comment by ironmonk88** [comment]
Added the option in settings to bypass the roll dialog.
