### ISSUE TITLE
[Bug] Need to click global "Free Movement" Button twice to reset individual restrictions

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#4]
Reproduce:

1. right-click one or more actors and restrict movement individualy (Tested with 1 and 2 out of 5 actors in tokenbar)
2. use global "Free Movement" button to reset all restrictions (first usage restriced tokes are still restricted (at least the indicator is still there))
3. repeat step two (now indicator is gone)

Expected: Clicking global "Free Movement" button once should undo/reset individual restrictions.

**Comment by ironmonk88** [comment]
Found the issue.  Thank you for catching that.  I need to wait on the setFlag function to finish before going on to the next token.
Will be fixed in the next patch.

**Comment by ironmonk88** [comment]
Version 1.0.5 is available, issue should be fixed.
