### ISSUE TITLE
Compatibility issue with Turn Marker module. 

### ISSUE THREAD

**Issue by gravagehulk** [ironmonk88/monks-tokenbar#40]
There’s another module I use religiously. It’s called Turn Marker. It puts an animated circle under the token of the next actor in combat. For some reason, it stops working when I have Monk’s Token Bar enabled. Your module looks great and I’d love to use it, but I can’t run my games without Turn Marker. 

The behavior is that the animated disk just stays in one place and never jumps to the next actor. Turn Marker started working correctly as soon as I disabled Monk’s Token Bar. 

I’m on the most current versions of Foundry, DnD 5e, and all of the modules. 

Thanks.

**Comment by ironmonk88** [comment]
Are you positive it isn't a different module?  I just tried it out on my machine and the disk moves to the next player in combat with TokenBar enabled.

**Comment by gravagehulk** [comment]
The only thing I changed from the last 20+ sessions was installing two modules: Monk's Little Things and Monk's Token Bar. I tried disabling Little Things first and there was no change. So I disabled Token Bar and Turn Marker started behaving normally for the rest of the session. Enabling Token Bar again caused it to stop working again. I had a rather large combat that was already set up before I enabled Token Bar, but I can't think of anything else. 

It almost seemed to be responding to the restricted movement or the built-in notification for the next person's turn. I do have a handful of other modules installed, so I suppose it could be a 3-way conflict of some sort, but disabling Token Bar immediately fixes it.

**Comment by gravagehulk** [comment]
I should also mention that the disk will move ONCE, but not subsequently. If you only tested it by forwarding initiative once, you may not have noticed that it gets stuck. 

That said, I just tested in a clean environment with only Turn Marker and Monk's Token Bar and I had the same issue.

**Comment by ironmonk88** [comment]
I'm still not able to figure that one out.  The code should co-operate.  And it's not failing on my copy.
I just released a new version of Little Details though.... that has the functionality of Turn Marker.  But does it with the tokens instead of creating a tile.  Hopefully this will work.  I couldn't use the same images though, so if you want to use the amazing artwork of TurnMarker, replace the icons/turnmarker.png with the image you use from TurnMarker.  Can't set the animation speed or the scale yet, but I'll work to add those.

**Comment by gravagehulk** [comment]
Thanks! I just tested that functionality and it works great. I appreciate you adding that. Your module also works fine with the Next Up module, which I just discovered.

FYI: Someone else reported this on the FoundryVTT Subreddit, so I'm not alone. I'm going to do some more testing and see if I can figure out why you can't replicate it. But the feature you added 100% resolved this for me. Love your modules. Thanks for all of your hard work.

**Comment by ironmonk88** [comment]
Just added the option to change the size and the image that's used.
Thank you for pointing this one out.
