### ISSUE TITLE
[BUG]Getting NaNs for the strike actions MAP in PF2e

### ISSUE THREAD

**Issue by devfinnd** [ironmonk88/monks-tokenbar#407]
**Describe the bug**
The lowest MAP level shows NaN for all characters of the Party (but not npcs/enemies weirdly)

**To Reproduce**
Update to the latest pf2e version (v5.4.1 in my case)

**Expected behavior**
Not showing NaN for the MAP

**Screenshots**
![image](https://github.com/ironmonk88/monks-tokenbar/assets/57416486/f8c94d3f-cb38-40a7-a98e-1f45b9c2bd98)

**Please complete as much of the following information as possible:**

 **Client:** Foundry Client
 **Foundry Version:** V11
 **System:** PF2e
 **Module version:** 11.02
 **Are there any errors in the console:** None that I would relate to this module
 **Have you tried using `Find the Culprit` to make sure it isn't a module interaction:** no

**Additional context**
This does not happen within the character sheet of the players.
The players are also all within the new Party sheet/token hybrid for the PF2e system

**Comment by ironmonk88** [comment]
You would want Token Action HUD.
This is Tokenbar.

**Comment by devfinnd** [comment]
Aye sorry man, my bad 😄
