### ISSUE TITLE
[BUG] Token bar actors when selected open/link to the wrong character sheet.

### ISSUE THREAD

**Issue by CrackJackFlood** [ironmonk88/monks-tokenbar#411]
**Describe the bug**
Title^ - 

**To Reproduce**
Not really sure seems to connected to these setting - 
![image](https://github.com/ironmonk88/monks-tokenbar/assets/49882452/afaf0c1c-8706-4e74-8cec-0e4d8a9565d1)

**Expected behavior**
Tokens link to the correct actor 

**Screenshots**
If applicable, add screenshots to help explain your problem. https://media.discordapp.net/attachments/862421107687817288/1155714946714325052/image.png
https://media.discordapp.net/attachments/862421107687817288/1155715060468023366/image.png
**Please complete as much of the following information as possible:**
 - chromium/electron - [VTT client](https://github.com/OmegaRogue/fvtt-player-client)
 - v11.309 - FVTT
 - 5.3.3 - pf2e
 - 11.02 - Mod
 - no errors
 - yes used find the culprit no culprit was found, issue persists with just pf2e and tokenbar only

**Additional context**
https://discord.com/channels/862414864692281386/862421107687817288/1147285230370173008
https://discord.com/channels/862414864692281386/862421107687817288/1155714947012108369
https://discord.com/channels/862414864692281386/862421107687817288/1155716081768484894

**Comment by CrackJackFlood** [comment]
same as issue #410

**Comment by ironmonk88** [comment]
Closing duplicate ticket.
