### ISSUE TITLE
[BUG] Since v11 releases, MTB causes lag in combat with midiqol

### ISSUE THREAD

**Issue by MotoMoto1234** [ironmonk88/monks-tokenbar#412]
**Describe the bug**
There is a delay that is exponentially worse when clients are connected, when you advance turns when Monk's Tokenbar is enabled with midiqol.  It seems to only occur with a new v11 feature, show offline players on when no client is connected, or regardless when any clients are connected.  Tposney has narrowed it down to some sort of snafu in MTB's code during combat, specifically on combat turn end/start, theres some sort of hiccup.  Noteably if you have monks sound enhancement installed and its set to play a sound on turn start, you can audibly see the delay because nothing happens literally till that sound plays 5-10 seconds after the turns changed, you can drag tokens you can do just about anything, but nothing happens literally till you pass this hiccup of script delay.  It stops happening when Monks Tokenbar is disabled.  

**To Reproduce**
1. Its always present when the two modules are installed and active, but if you have really great hardware its not noticeable, this is mainly a problem with medium to low end hosting hardware

**Expected behavior**
The turn change should be as fluid as it is when monks tokenbar is disabled

**Screenshots**
I shared clips of the delayed turn changes when no client is connected, its 10x longer in delay when there are 6 other clients connected to the world, the two clips are of my two servers, one is low end hardware, the other is decent modern hardware:

Low end hardware:
https://cdn.discordapp.com/attachments/862421107687817288/1143893965481971722/slow_host.webm?ex=652fd845&is=651d6345&hm=eb521f16b95c036ebec70d45b1c24651fd1c83ed3e6c905f9b67dca7eee38cdd&

Newer hardware:
https://cdn.discordapp.com/attachments/862421107687817288/1143894103537496185/fast_host.webm?ex=652fd866&is=651d6366&hm=6cbae580f504294f1cfa6f51c0561b706c80f749f6245908d91e8dad47eecb84&

**Please complete as much of the following information as possible:**
 - Google Chrome, hosted via node.js locally
 - 11.313, was present for all of v11's lifecycle so far, did not happen in v10
 - Definitely present in 2.2.x and 2.3.x dnd5e
 - 11.0.1 and 11.0.2
 - No errors
 - Find the culprit reveals that the problem goes away when MTB is disabled.  

**Additional context**

**Comment by MotoMoto1234** [comment]
I won't be able to 100% confirm till tonight in 17 hours when we finish, but it looks like somehow 11.0.3's changes fixed the lag in combat on turn changes, its most noticeable when clients are connected but it seems to have cleared up testing with just 2 clients connected.

**Comment by ironmonk88** [comment]
Fixed in the latest version
