### ISSUE TITLE
[BUG] Token bar causes a flurry of database transactions on turn update.

### ISSUE THREAD

**Issue by tposney** [ironmonk88/monks-tokenbar#415]
**Describe the bug**
When advancing combat tracker a significant delay is introduced with monks token bar enabled.
I don't pretend to know the details of execution but the proposed fix reduces the number of database transactions significantly.

Change line 1139 of monkstokenbar.js from:
```js
                this.token?.unsetFlag("monks-tokenbar", "notified");
```
to
```js
              if (this.token?.getFlag("monks-tokenbar", "notified"))
                this.token?.unsetFlag("monks-tokenbar", "notified");
```

**Expected behavior**
This reduces the number of database transactions significantly when updating combat and makes advancing the combat tracker more responsive.

**Comment by tposney** [comment]
Been doing a bit more digging and it turns out there is  a cascading of updates triggered by the combat update.
Tokenbar is doing more updates than it should and midi is also guilty of exactly the same issue and the combination ends up doing n*m updates to the database which can quickly get quite large.

**Comment by ironmonk88** [comment]
Is Tokenbar 11.05 doing any better with that?
I removed a bunch of calls to the database.

**Comment by tposney** [comment]
Seems to be much better - now I just need to clean up the excesses in midi-qol.

**Comment by MotoMoto1234** [comment]
A really good way to test without a live session is to have monks sound enhancement set to play a sound for each actor in the dummy combat, cause that sound won't play till everythings done in the stack and is always the tell tale sign that you can start doing things on a turn.  On really fast hardware we're talkin maybe 1 second probably none, but on challenged hardware it can be noteworthy delays.

**Comment by ironmonk88** [comment]
Fixed in the latest version
