### ISSUE TITLE
[BUG] SWADE Not all skills work when requesting for rolls

### ISSUE THREAD

**Issue by picollo-24** [ironmonk88/monks-tokenbar#418]
**Describe the bug**
When I'm trying to request rolls via tokenbar, some skills return error {Character Name]:[Character Name}: Could not find function to roll From my investigations (tested on orc npc, haven't verified all skills), only Unskilled Attempt, and Common Knowledge caused error. Testing custom skill worked as intended (I've been able to roll properly).

**To Reproduce**
1. Have default orc character from the official module as a character on the map
2. Request for roll selecting all possible skills.
3. Most of skills will work correctly, however "Unskilled Attempt" and "Common Knowledge" will return error.

**Expected behavior**
Each skill should work the same way- i.e. when requested, roll should be made normally.

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version 11.307
 - System Savage Worlds Adventure Edition 3.1.4
 - Module version 11.05
 - Are there any errors in the console [e.g. press F12 and look for red text] No errors.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. I haven't, but I tested it on configuration with Foundry +SWADE + Tokenbar only.

**Comment by ironmonk88** [comment]
Fixed in the latest version
