### ISSUE TITLE
[Bug] Not working for players after switching scene

### ISSUE THREAD

**Issue by Deuterazamus** [ironmonk88/monks-tokenbar#42]
Hello there!
in our group we have an npc owned by all players. We wanted to use your amazing token bar to quickly find the npc so we set the "Allow players to use" setting.
However we quickly realized that the TokenBar breaks after a scene change. After that clicking any token in the bar throws

Uncaught (in promise) TypeError: Cannot read property 'position' of null
    at Token.get (DisplayObject.ts:657)
    at Token.refresh (foundry.js:44295)
    at Token._onRelease (foundry.js:11676)
    at Token._onRelease (foundry.js:44814)
    at Token.release (foundry.js:11658)
    at Token.control (foundry.js:11614)
    at TokenBar._onClickToken (tokenbar.js:431)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)

Attaching a simple test world
[testaa.zip](https://github.com/ironmonk88/monks-tokenbar/files/6058135/testaa.zip)

**Comment by Deuterazamus** [comment]
Actually that was in 1.0.18. 
After updating to 1.0.19 the player's bar in attached test world renders correcty. 
However after updating the actual play world I'm seeing an empty bar for players. Used FindTheCulprit to enable only TokenBar and the behaviour is the same, no errors in console. I'll investigate further!

**Comment by ironmonk88** [comment]
1.0.19 is the start of an attempt to fix it but I think there's still issues with it.
Also... thank you for uploading the world as an example!!  That was invaluable.  I wasn't able to replicate it on any of my system, but it showed up immediately with that world for some reason.

I'm pretty sure the empty bar is just 'cause I'm missing a spot in the code where I need to refresh.  Can you give me steps to reproduce?

**Comment by Deuterazamus** [comment]
After updating to 1.0.19 I can't replicate the empty bar in the test world.
It only happens in our play world, even with only TokenBar enabled. If you're ok I can hook you up on Discord and share an invite there

Repro setps are quite simple there:
login as GM, 
start find the culprit select TokenBar, wait for page refresh and leave the GM page there
open another browser window and login as a player
you'll see an empty TokenBar right in the landing page

**Comment by ironmonk88** [comment]
I'll have another look at it.  But I'd love to see what's going on.
Not tonight, but maybe tomorrow?

**Comment by Deuterazamus** [comment]
Judging from the timestamp of your responses I figured that we're probably on very far timezones, so I went ahead and debugged a bit. And it was a serious blast.
First of all let me say that my play world, aka The One Who is Bugged, is hosted on the Forge... this will be crucial later so please stick with me.

By debugging I discovered that 

```
        if ((game.user.isGM || setting("allow-player")) && !setting("disable-tokenbar")) {
            MonksTokenBar.tokenbar = new TokenBar();
            MonksTokenBar.tokenbar.getCurrentTokens().then(() => {
                MonksTokenBar.tokenbar.render(true);
            });
            
        }
```
MonksTokenBar.tokenbar.render(true) was being called before tokenbat.getCurrentTokens() promises resolved. The promises contained the expected tokens but when they resolved the bas was already rendered. This is the code I'm referring to... and you'll probably already understand what happened, while I still didn't:

```
 async getCurrentTokens() {
        log('Get current Tokens');
        let promises = canvas.tokens.placeables
            .filter(t => { return t.actor != undefined && t.actor?.hasPlayerOwner && (game.user.isGM || t.actor?.owner) && t.actor?.data.type != 'npc'; })
            .sort(function (a, b) { return a.name < b.name ? -1 : (a.name > b.name ? 1 : 0); })
            .map(t => { return this.mapToken(t); });

        Promise.all(promises).then(response => {
            this.tokens = response;
        });
    }
```
But why on earth does this not occur on my local test world? So I went on to debug and I discoved that despite having the exact same version of TokenBar (1.0.19), the two instances had different code baselines:

```
    async getCurrentTokens() {
        log('Get current Tokens');
        let promises = canvas.tokens.placeables
            .filter(t => { return t.actor != undefined && t.actor?.hasPlayerOwner && (game.user.isGM || t.actor?.owner) && t.actor?.data.type != 'npc'; })
            .sort(function (a, b) { return a.name < b.name ? -1 : (a.name > b.name ? 1 : 0); })
            .map(t => { return this.mapToken(t); });

        Promise.all(promises).then(response => {
            this.tokens = response;
            this.render(true); // THIS!
        });
    }
```
I had a quick look on your github and saw that the tag for 1.0.19 is labeled "fixing issues with 1.0.19", but being 1.0.19 the very same version being tagged I guess that you re-released the same version for an hotfix.
If this is true, the bug is not in the code but in the release procedure.

Forge's hosting has a module repository/buffer/facade, called The Bazaar, that periodically pulls officially released versions, lets us use very big modules without having them affect our hosting quotas, allows us users to link patreon on it and so on and so forth. 
The Bazaar is a striclty semver compliant repository. 
Once a version is set on it, subsequent releases of the same version will not be pulled (and this is formally correct as versioning is exacly meant to differentiate code bases) and all users we'll be stuck with whatever problem that version had at pulling time.
On a locally hosted machine the immediate solution whould be "uninstall the module and reinstall" but while it's possible to sideload custom modules on the Forge (bypassing the Bazaar) it's very hard to track re-released modules (unless stalking entire Discord servers or manually checking github) and, after all, re-releasing is a very bad practice per se.

So, after all:
- if you did re-release the module with the same version number, I humbly ask you to refrain from this as is a (way too common) bad practice. Just let those version numbers do their job.
- if you did not re-release, then I believe that the next version will probably fix the empty bar problem (I'll let you know).

Thank you so much for all your beautiful modules!

**Comment by ironmonk88** [comment]
You are correct, I did release and then quickly re-release.  Hadn't thought about Forge.
I usually don't but was pushing out an update quickly for someone who had a games night in a couple hours.
Most of the time it gets tested for a few days first before release to avoid that problem.
I'll wrap up some code I'm working on and try and get a new version out sooner rather than later.

And will definitely avoid re-releasing from now on.

Thank you so much for the debugging work!!!

**Comment by ironmonk88** [comment]
1.0.20 has been released and should fix all the weirdness caused by re-releasing 1.0.19.

**Comment by Deuterazamus** [comment]
Confirmed! TokenBar 1.0.20 fixed all issues mentioned!
Thanks!
