### ISSUE TITLE
[BUG] Last Tokens

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#430]
Button seems to do nothing for me; occasionally results in this error.

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/e67fd401-d6ab-4bc4-a680-7588b3a337a3

Foundry 11.315
Tokenbar 11.07
PF2 5.10.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
