### ISSUE TITLE
[BUG] Redirect Request Results

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#432]
Tokens are not being redirected unless they were selected at the time the tile was triggered.

Tokens are both being redirected to one landing instead of being sent to the landing matching their result (third request in the video).

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/9f442237-1305-4c2a-bbb1-71da1fc2d343

Foundry 11.315
MATT 11.17
Tokenbar 11.07

**Comment by gludington** [comment]
Filed a pull request for the persistent failing:

https://github.com/ironmonk88/monks-tokenbar/pull/433

**Comment by ironmonk88** [comment]
Fixed in the latest release.
