### ISSUE TITLE
[BUG] Tokenbar button in Roll Request dialog creates duplicates

### ISSUE THREAD

**Issue by this-gavagai** [ironmonk88/monks-tokenbar#434]
**Describe the bug**
In the latest update, the code for the Tokenbar button event handler in the Roll Request dialog was changed. It no longer clears existing entries before adding new ones. As a consequence, the same tokens will be added over and over again.

**To Reproduce**
1. Create a new Roll Request.
2. Click on "Tokenbar" Actors button twice.

**Expected behavior**
The list of actors should be cleared before new ones are added. 

**Screenshots**
<img width="801" alt="Screenshot 2023-12-18 at 12 58 53 PM" src="https://github.com/ironmonk88/monks-tokenbar/assets/9303694/510aee76-d719-45f9-aed1-5148a8f4b21e">

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
