### ISSUE TITLE
Include PF2e Party Sheet Stash in Loot Distribution

### ISSUE THREAD

**Issue by ottyn** [ironmonk88/monks-tokenbar#437]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
PF2e Party Sheet Stash added to the list for "Distribute enemies loot"?  You can selected The Party actor if you have Item Piles selected in that option, but it then converts the Party Sheet to an Item Pile and makes the sheet unusable for normal functions, and of course if you select MEJ, you can't select an actor.  Not sure if this is possible or not though.

The PF2e Party Sheet is a special actor in the PF2e System.  It has a Stash tab that acts as a loot actor.  You can have multiple Party Sheet actors in a world.

**Additional context**
![image](https://github.com/ironmonk88/monks-tokenbar/assets/97130150/f9977a93-4b17-4f55-9ec9-cfed48535c3c)
![image](https://github.com/ironmonk88/monks-tokenbar/assets/97130150/e34aadc4-23d2-4039-86fc-bb9da8c78e79)

**Comment by ironmonk88** [comment]
Should be added to the latest release
