### ISSUE TITLE
[BUG] Only one token shows up on token bar when no tokens in the scene

### ISSUE THREAD

**Issue by pandabananda** [ironmonk88/monks-tokenbar#439]
**Describe the bug**
The only plaer character showing up on the token when the token is not on screen is the one whown in the screenshot below. 

**Expected behavior**
I would expect the other player characters to show up in the tokenbar not just the one. 

**Screenshots**
![image](https://github.com/ironmonk88/monks-tokenbar/assets/155663594/d6b07877-baa9-4b12-898d-ee0b2caa81d2)

**Please complete as much of the following information as possible:**
 - Foundry Version - V11
 - System - D&D5e
 - Module version - 11.09
 - Are there any errors in the console doesn't look like it.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. - Yes - is an issue with the tokenbar

**Additional context**
The other tokens are set to friendly disposition and are clicked as "shown on tokenbar"
![image](https://github.com/ironmonk88/monks-tokenbar/assets/155663594/0e8986a5-721b-4387-aa77-4027d76db59c)

**Comment by ironmonk88** [comment]
If they're not on the scene, then the token won't actually show on the token bar, that's kind of the point.

You can turn on actors appearing on the scene even if there's not token on the scene in the settings.
![image](https://github.com/ironmonk88/monks-tokenbar/assets/75920956/fa34fff4-3549-4669-94d4-e53bee415abb)
But make sure those actors are owned and assigned to a player.

**Comment by pandabananda** [comment]
Sorry explained this really badly, I have assigned all the actors to players and have ticked the Show actors but the only on the shows up is Ol' Babbel and I have no clue why. 
![image](https://github.com/ironmonk88/monks-tokenbar/assets/155663594/3e2735b9-c80f-4e7b-bdf3-c6282e496750)

**Comment by ironmonk88** [comment]
They own a character but have they been assigned a character.
![image](https://github.com/ironmonk88/monks-tokenbar/assets/75920956/eefbf3f1-2d40-422f-91af-8998b21dea56)

**Comment by pandabananda** [comment]
Thanks so much fixed now!

**Comment by ironmonk88** [comment]
Glad it's fixed.  Closing ticket.
