### ISSUE TITLE
CSS: Change the flex on Saving Throws' Item Controls.

### ISSUE THREAD

**Issue by mclemente** [ironmonk88/monks-tokenbar#44]
The item controls on the savingthrows.html are wrapping on the Portuguese translation. Line 325 on the css, `#requestsavingthrow .monks-tokenbar .sheet .items-list .items-header .item-controls`.
Here's how it looks like currently: 
![image](https://user-images.githubusercontent.com/5288872/109578851-b4369c80-7ad6-11eb-8af3-747015d3af48.png)

My suggestion: change `flex: 0 0 250px` to either `flex: 5` or `flex: 0 0 265px` (or even higher px if there's any language with bigger words), whichever is better for you.
![image](https://user-images.githubusercontent.com/5288872/109579129-198a8d80-7ad7-11eb-9559-336f5fa34764.png)

**Comment by ironmonk88** [comment]
1.0.20 should have this fixed.  Let me know if it looks better.

**Comment by mclemente** [comment]
Looks great now, thanks!
