### ISSUE TITLE
Close "Distribute Lootables" Window Automatically

### ISSUE THREAD

**Issue by 7H3LaughingMan** [ironmonk88/monks-tokenbar#440]
**Is your feature request related to a problem? Please describe.**
When distributing loot after combat it doesn't automatically close the window when you are done. If you aren't paying attention you might distribute lootables twice creating two loot actors.

**Describe the solution you'd like**
When you click on Create New Lootable or Transfer To Lootable it should automatically close the window, similiar to how distributing XP after a combat works.

**Additional context**
N/A

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
