### ISSUE TITLE
[BUG] PF2 Perception

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#447]
The warning still shows up when loading into a world.

https://github.com/ironmonk88/monks-tokenbar/assets/99844555/312d942f-c4bc-4594-bd7c-c3e5e010539f

![image](https://github.com/ironmonk88/monks-tokenbar/assets/99844555/1b0fe8a0-77e6-492e-939e-df2df67b8ac1)

Foundry 11.315
PF2 5.12.7
Tokenbar 11.10

**Comment by ironmonk88** [comment]
That looks like you have custom attributes in the settings that use perception.
The default settings have been fixed, so you'll need to edit that out yourself manually.
