### ISSUE TITLE
Uncaught exception during token image update macro

### ISSUE THREAD

**Issue by kelanel** [ironmonk88/monks-tokenbar#45]
getting this when running my own webm assignments for token images for attack animation overides.
`

  | updateToken | @ | tokenbar.js:207
-- | -- | -- | --
  | (anonymous) | @ | tokenbar.js:597
  | _call | @ | foundry.js:2496
  | callAll | @ | foundry.js:2456
  | _handleUpdateEmbeddedEntity | @ | foundry.js:30047
  | _handleUpdateEmbeddedEntity | @ | foundry.js:34301
  | updateEmbeddedEntity | @ | foundry.js:30015
  | async function (async) |   |  
  | updateEmbeddedEntity | @ | foundry.js:30005
  | update | @ | foundry.js:11475
  | eval | @ | VM1126:19
  | callScriptMacroFunction | @ | Macros.js:179
  | renderMacro | @ | Macros.js:197
  | executeMacro | @ | Macros.js:221
  | _onExecute | @ | foundry.js:18234
  | async function (async) |   |  
  | _onExecute | @ | foundry.js:18233
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

`

I'm just updating some token images with set webm's, it seems to be triggering on the img update part. works otherwise. 

`
let wait = async (ms) => new Promise((resolve)=> setTimeout(resolve, ms));
let swordidle = { 
// set path to webm once complete.
    path: "pathtoidleanimation.webm", 
    timeout: 7300
};
 
let swordAttack1 = { 
//set path to webm
    path: "pathtoattack.webm",
    timeout: 2850 //set timeout value based on length of animation sometiems - 50 ms to smooth out to idle
};
let tok = canvas.tokens.controlled[0];

tok.update({ "img": swordAttack1.path })
tok.refresh();
await wait(swordAttack1.timeout);
tok.update({ "img": swordidle.path })
tok.refresh();
`

**Comment by ironmonk88** [comment]
I just rewrote that section of code and it looks like I missed on one of the variable names.
It should be fixed in code and will be available next release.

**Comment by ironmonk88** [comment]
1.0.21 has released, this should be fixed now.
