### ISSUE TITLE
(Minor Issue) Tokenbar resetting position when dragging

### ISSUE THREAD

**Issue by MarceloCortezz** [ironmonk88/monks-tokenbar#46]
Hi Monk, I've encountered this minor issue when you try repositioning the bar by clicking and dragging (video):
When you click and drag, tokenbar resets its position to the top of the screen.

https://user-images.githubusercontent.com/79060716/109996628-2a611c00-7cee-11eb-84d2-be2ed08bdcb3.mp4

Some test information:
1. This happened even when all modules but tokenbar are OFF.
2. This happens after a certain distance from the top of the screen. When it's at the bottom or below the middle of screen, it resets its position.
3. Both paused and unpaused games were tested.

**Comment by Red5Phil** [comment]
I’ve had precisely the same experience. When you go to drag, the tokenbar immediately resets itself to the top of the screen. Occasionally this results in strange movement behavior for tokens as well - a token will behave as if you’ve changed it to no movement, but cannot be swapped to a different setting.

**Comment by ironmonk88** [comment]
Should be fixed with the next release.  It's due to the change of positioning based on the closest edge.  If the tokenbar is positioned near the bottom, when you go to move it, it has to switch to positioning related to the top of the screen and it wasn't making that switch well.

**Comment by ironmonk88** [comment]
1.0.21 has released this should be fixed now.
