### ISSUE TITLE
[Suggestion] Compatability with Starfinder RPG

### ISSUE THREAD

**Issue by agentnos** [ironmonk88/monks-tokenbar#47]
I downloaded to see how much can be done using the Starfinder system. I managed to get the list of roll requests show up properly for starfinder (e.g. saves and skills etc), but couldn't get the rolls to properly resolve, due to not having the knowledge.

I really love the polish and usefulness of your modules and would love to be able to use them with my starfinder group :)

**Comment by ironmonk88** [comment]
Looking into it.  It takes awhile to find all the functions to hook into properly.

**Comment by rrenna** [comment]
This would be great in Starfinder.

**Comment by ironmonk88** [comment]
Starfinder should now be available with the latest release.
