### ISSUE TITLE
[1.0.20] REQUEST : pf2e system values in settings.js

### ISSUE THREAD

**Issue by 94cents** [ironmonk88/monks-tokenbar#48]
Perhaps intentional, but settings.js no longer includes a default value for perception (Stat2 Resource), which leaves pf2e systems without a default perception value displayed on Token Bar.

**Comment by ironmonk88** [comment]
Default value set to "attributes.perception.value".  There's no good value for passive perception in pf2e so with the switch to fully customized stats, I've had to revert to available character attributes.  Default will appear with the next release.

**Comment by ironmonk88** [comment]
1.0.21 has released, the default should be set to perception.
