### ISSUE TITLE
[Bug] Whisper doesn't autopopulate PC Name

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#49]
When using the right click option in the tokenbar to "whisper" a PC in the chat only "/w" followed by two whitespaces are added.
No errors on the console. Not sure if it's a user-error or a bug.

![image](https://user-images.githubusercontent.com/44159008/110151063-493fdb00-7de0-11eb-97b4-76868b17ddb3.png)

**Comment by ironmonk88** [comment]
I'm guessing the player wasn't logged in a the time.  Corrected so that context menu only shows for players that are logged in.

**Comment by ironmonk88** [comment]
1.0.21 just release, should fix this issue.
