### ISSUE TITLE
[Bug?][Feature?] Incompatibiliy with Mars-5e

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-tokenbar#5]
Using Mars-5e results in new chat card for rolls instead of displaying it within monks chat card. 
(https://foundryvtt.com/packages/mars-5e/)

![image](https://user-images.githubusercontent.com/44159008/105735986-994f9600-5f34-11eb-94d7-a1563d101e88.png)

**Comment by ironmonk88** [comment]
Well... that's not good.  I'll look into the compatibility of the two.  I've been using some of the default classes to save replicating styles, but Mars-5e might be grabbing on to those.

**Comment by tagnullde** [comment]
Maybe libwrapper can help with that too? Not sure - but I think that's what it's for. Would be a dependency though.

**Comment by ironmonk88** [comment]
Looks like it's an incompatibility.  Mars5e has prototyped the actor functions I use to make the roll, and returns a Mars5eMessage instead of the expected Roll.  I could work around it if the roll information was contained in the resulting Mars5eMessage, and it looks like there's a property for it, but it's null.  I opened a ticket with the author to see if there's a work around.

**Comment by mikkosaarinen** [comment]
Thank you. I just installed Mars 5e as it seems like genuinely quality of life type module, but I was afraid it might cause some incompatibilities with other mods. I hope Moerill is receptable to feedback and happy to work with you. If we can help in any way - other than coding - please let us know.

**Comment by tagnullde** [comment]
While testing the Thief's Tools bug, I noticed that for an item that I created myself - the rolling within the chatcard does work:

![grafik](https://user-images.githubusercontent.com/44159008/109165897-60e1e880-777c-11eb-99da-997655a95085.png)

Maybe that could be helpfull to bypass the bug / insufficent data from mars-5e? Just a thought.

**Comment by ironmonk88** [comment]
Mars-5e updated their code and it looks like this isn't an issue any more.
Closing the ticket.
