### ISSUE TITLE
[BUG] Monk's Tokenbar has lost Request Roll and Award XP buttons after PF2 system update.

### ISSUE THREAD

**Issue by DocMysterio** [ironmonk88/monks-tokenbar#503]
**Describe the bug**
Monk's Tokenbar has lost Request Roll and Award XP buttons after PF2 system update

**To Reproduce**
Update to Foundry V12 [Stable 5 (Build 328)] and PF2 system 6.1.0

**Expected behavior**
I expect the Request Roll and Award XP buttons to appear in the Tokenbar and work

**Screenshots**
<img width="367" alt="Screenshot 2024-07-21 at 9 58 41 AM" src="https://github.com/user-attachments/assets/403bcfc4-9ec9-493a-9018-f3edf4e88489">

**Please complete as much of the following information as possible:**
 - Browser CHROME
 - Foundry Version [v12 Stable 5 (Build 328)]
 - System [ePF2 system 6.1.0]
 - Module version [12.01]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
 Yes Find the Culprit found no issues.

**Additional context**

**Comment by dslogget** [comment]
https://github.com/foundryvtt/pf2e/commit/f6767c1ccfd00be30559739e1918ec3fdcffd498

Appears to be the commit that changed the usage of skillList

**Comment by firesidewizard** [comment]
This is marked closed? Is there a solution?

**Comment by DocMysterio** [comment]
> This is marked closed? Is there a solution?
 Yes, don't update to the latest version of PF2e system yet or roll it back. 
 Otherwise wait until Monk's updates it.
