### ISSUE TITLE
[BUG] PF2E Tokenbar missing Roll/Exp Assignment/Token Info Functionality in V12.329

### ISSUE THREAD

**Issue by EWAP333** [ironmonk88/monks-tokenbar#505]
**Describe the bug**
Since updating to v12.329, Monk's tokenbar no longer includes buttons for exp assignment, buttons to request rolls from players, or trade options (I think that's what the two people with the arrows between them button was, not something I used). I'm also no longer seeing any additional information about characters beyond their token portraits and health bars. This is specifically in Pathfinder Second Edition system

**To Reproduce**
1. Load game using PF2E and monks tokenbar
2. See lack of options in tokenbar.

**Expected behavior**
I would expect to see the typical options listed as being part of the tokenbar functionality.

**Screenshots**
![image](https://github.com/user-attachments/assets/c7ab415c-4e12-4f0a-9af5-795b6673fc43)

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: 12.329
 - System: Pathfinder 2e
 - Module version: 12.1
 - Are there any errors in the console: Yes, see below:
 
 Error: Error thrown in hooked function '' for hook 'setup'. Cannot destructure property 'lore' of 'this.config.skillList' as it is undefined.
    at Hooks.onError (foundry.js:658:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:640:36)
    at Hooks.callAll (foundry.js:593:17)
    at Game.setupGame (foundry.js:9063:11)
    at async Game._initializeGameView (foundry.js:10435:5)Caused by: TypeError: Cannot destructure property 'lore' of 'this.config.skillList' as it is undefined.
    at new PF2eRolls (pf2e-rolls.js:8:17)
    at Object.fn (monks-tokenbar.js:1167:36)
    at #call (foundry.js:636:20)
    at Hooks.callAll (foundry.js:593:17)
    at Game.setupGame (foundry.js:9063:11)
    at async Game._initializeGameView (foundry.js:10435:5)
 
 
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes

**Comment by firesidewizard** [comment]
This is also effecting me.

**Comment by TheErikkuBlade** [comment]
Bumping this, I am also affected

**Comment by Howiedewit** [comment]
Same issue, Also would like to add a photo refrencing the broken request to roll feature. 
![Foundry_Virtual_Tabletop_fmbYjFnp02](https://github.com/user-attachments/assets/5a2dbe74-f3b3-43fe-ad0f-ea6a6e30cc51)

**Comment by ghostphoenix713** [comment]
Following because I'm experiencing the same issue. I went into the Configure Settings menu for the module and couldn't find a way to add the relevant stats back in, either. Screenshot below to show what I mean. The only things that show up when you even begin typing the letter a, for attribute, are those in the screenshot. Nothing for skill or perception, etc.

![foundry issue](https://github.com/user-attachments/assets/ad37f77e-7cae-47b1-be1b-d718ae63b1cd)
