### ISSUE TITLE
Any chance for the removal of natural attacks for Foundry V11?

### ISSUE THREAD

**Issue by WinterrrWarlock** [ironmonk88/monks-tokenbar#508]
**Is your feature request related to a problem? Please describe.**

Can't update to V12 of foundry, I have an incredibly automated campaign and numerous dependencies and modules haven't been updated yet.

**Describe the solution you'd like**

I'd love the feature of removing natural attacks and such for V11. I can update the code myself as long as I am told which section to either add it in or what things to change :)

**Additional context**

All of your work is stellar, if you have access to the snippet of code and are willing to update it/send the snippet to me and tell me where it goes I'll happily do the work. Your stuff is invaluable, and this fix would remedy one of the few remaining issues I have in my campaign :)

**Comment by ironmonk88** [comment]
Unfortunately I can't support previous versions.
The code would be in `lootables.js`.  Just search through the v12 version for "natural"
