### ISSUE TITLE
Performance issues on token move/possible every render call.

### ISSUE THREAD

**Issue by adriangaro** [ironmonk88/monks-tokenbar#51]
The hook `renderTokenBar` seems to cause a reflow somewhere in it, causing frames to be dropped as the browser is required to reflow the page to access a property of an element. Usually from my experience, this happens when you are trying to access the size of an element or offset of it. From what the profiler shows it seems to be caused at some point by a jquery call that might need to access such a property.

The dip in performance is very noticeable from 60 fps on a decent rig to 40 or 30 fps and the reflow usually takes 60-80 ms.

I haven't looked much at the source, but on a cursory glance, maybe after the jquery call at fault here is identified, it should either be called scarcely and only when needed and not on every render call, or be removed altogether if possible.

Love the module and would love to see this improved but as of now, I'll have to disable it since in combat-heavy fights the lag caused by it gets bothersome.

**Comment by ironmonk88** [comment]
Made some updates to the render code.
Hopefully it's a bit faster now.

**Comment by ironmonk88** [comment]
Closing the ticket as improvements have been made to the function, and no response has been made to the last question.
