### ISSUE TITLE
[BUG] Not all AC changes reflected without page reload

### ISSUE THREAD

**Issue by Weissrolf** [ironmonk88/monks-tokenbar#510]
**Describe the bug**
While AC changes based on the PF2's "Raise a shield" effect are immediately reflected in MTB other effects like PF2's "Nimble Dodge" (no effect) need a page reload (F5) to show up as changed AC in MTB.

**To Reproduce**
1. Open PF2E character sheet, Actions tab.
2. Click on 'Nimble Dodge" on a Rogue sheet.
3. Watch AC change on character sheet.
4. Watch AC *not* change in MTB.
5. Hit F5. AC now also changed on MTB.

**Expected behavior**
AC changes based on mechanics other than "effects" to be reflected in MTB without need for reload (F5).

 - Edge
 - Foundry Version V12.330
 - Pathfinder 2e v6.2.0
 - Module version v12.02
 - No console error.
 - `Find the Culprit` with just the PF2e system + libraries + MTB behaves the same.

**Additional context**
I suspect the missing "effect" to be the culprit, but don't really know.

Thanks and regards.

**Comment by ironmonk88** [comment]
Fixed in the latest version
