### ISSUE TITLE
[Request] Adjust Images on Tokenbar

### ISSUE THREAD

**Issue by Babou-31** [ironmonk88/monks-tokenbar#517]
Hello,

When we choose to display the portrait of the actors instead of the Tokens, the images are cut.

![image](https://github.com/user-attachments/assets/e34bb927-d86c-4ecf-8fac-0b2b3e185bda)

Is it possible to display the entire image? Or to make sure they are cut only at the bottom?
I tried to modify the .css but the images are cut then convert to base64 and I can't find how to change that.

Thanks for the module, it's great

**Comment by ironmonk88** [comment]
That would be an issue with the Foundry thumbnail function.
Waiting for them to fix the issue.
