### ISSUE TITLE
[Feature Request] Remove extra padding from token art in TokenBar

### ISSUE THREAD

**Issue by joeparis** [ironmonk88/monks-tokenbar#526]
**Is your feature request related to a problem? Please describe.**
The problem is that for certain artwork from the Pathfinder Tokens: Character Gallery (v1.0.3) token artwork displayed in TokenBar is inconsistently sized. 

![2024-10-03_12-04-26](https://github.com/user-attachments/assets/21015004-30a1-4ea2-a73a-434a34e166e5)

That same token artwork is sized appropriately both in the scene and in chat cards.

![image](https://github.com/user-attachments/assets/d1282923-f576-4850-b27d-68aed883c57a)

When the Character Gallery is installed it updates token artwork for some characters' tokens to be sourced from the `Data/modules/pf2e-tokens-characters/assets/tokens` directory. Kyra's token artwork has dimensions of 1024 x 1024 pixels, presumably due to the pop out caused by her head wear, and also has quite a bit of padding (I've colorized the background to make the padding more apparent).

![pc-kyra-the-cleric](https://github.com/user-attachments/assets/5e970ea4-9b1b-44cf-a552-c9cbb361867b)

That extra padding seems to be at the root of the problem.

**Describe the solution you'd like**
As it seems to be possible to remove or ignore the excess padding, as demonstrated by the token's appearance on the scene and in chat cards, I'd ask that a similar approach be taken to adjust the size of the token's art in TokenBar, making those tokens with extra padding more consistent with those without.

It was suggested in the pf2e-modules channel of the Pathfinder on Foundry Discord server that PF2e HUD had solved this problem thusly

![image](https://github.com/user-attachments/assets/b7039ee8-c3fc-4e74-bb30-208e1dd5292d)

and that a similar fix might be implemented for TokenBar.

**Additional context**
Pop outs are becoming more common. There are quite a few pieces of token art in the Character Gallery that have these same sorts of pop outs and dimensions, all of which will most likely cause this same issue.

This may be related to #261

**Comment by ironmonk88** [comment]
Added to the latest version
