### ISSUE TITLE
[BUG] Roll#evaluate Deprecation Warning

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#531]
Requesting a roll via Tokenbar and then rerolling it via right-click in PF2. Possibly related to #530.

![image](https://github.com/user-attachments/assets/6897d2cf-19ab-4d37-9d46-2bef2b9015d9)

Foundry 12.331
PF2 5.4.1
Tokenbar 12.02

**Comment by ironmonk88** [comment]
Fixed in the latest version
