### ISSUE TITLE
Sandbox Incompatibility

### ISSUE THREAD

**Issue by AetherianRPG** [ironmonk88/monks-tokenbar#54]
After updating to version 1.0.25, module stopped working with Sandbox system.

**Comment by ironmonk88** [comment]
What is it doing?  And are there any errors in the console log?

**Comment by AetherianRPG** [comment]
It is not showing the Token Bar anymore. 
![Capturar](https://user-images.githubusercontent.com/68928934/110367906-091e6980-8027-11eb-874d-7c668d8e201c.PNG)
