### ISSUE TITLE
[BUG?] Limit Movement Feature Not working for WASD?

### ISSUE THREAD

**Issue by OpticalShadows** [ironmonk88/monks-tokenbar#6]
I may have found a bug with the limit movement feature. Whenever it is set to "No Movement" or "Combat Turn" tokens could still be moved around with the WASD / Arrow Keys. I checked after an update and it looks like it sort of fixed the issue but it only works with dragging tokens. Is this intended? Would it be possible to prevent the movement via the WASD/Arrow keys as well?

**Comment by ironmonk88** [comment]
Tbh... I didn't even think about the movement keys.  Thank you for finding that.
Code has been fixed, just running it through some debugging.  Next patch should have the changes.

**Comment by ironmonk88** [comment]
1.0.6 just released.  Should have this bug taken care of.
