### ISSUE TITLE
[minor] Variables instead of values in monk's tokenbar

### ISSUE THREAD

**Issue by MarceloCortezz** [ironmonk88/monks-tokenbar#60]
Sometimes this happens when I log in or change scenes. I don't know why this happen, but I know if I add or remove someone it will correct the value.
![image](https://user-images.githubusercontent.com/79060716/111386952-c0e8f200-868b-11eb-8f7e-87065924eae6.png)

Tell me if you need more information.

**Comment by MarceloCortezz** [comment]
https://user-images.githubusercontent.com/79060716/111409019-e9d1ad00-86b4-11eb-84e0-e42ce1048739.mp4

I made a video of what I said when I add a token to the scene and corrects the values

**Comment by ironmonk88** [comment]
What value are you using for stat1?

**Comment by MarceloCortezz** [comment]
attributes.ac.value

**Comment by ironmonk88** [comment]
It looks like that's resolving as a formula '10 + @abilities.dex.mod'.
I just added the ability for TokenBar to process formulas... like 1 minute ago.
I'm not sure how it will handle the '@' sign out front though.
Let me know if it works and if it doesn't then I'll make a note to remove the '@' prior to evaluating.

**Comment by MarceloCortezz** [comment]
Apparently, when I log into the game, it still appears bugged, sometimes all of them, sometimes some of them. When I change scene it is perfectly calculated. I guess it's something related to when STARTING the client.
This is happening when logging into the game via The Forge.

I launched the VTT standalone app and it is not giving me these issues. So I could say that:
a) This is conflicting with another module (that I dont have installed in my standalone)
or
b) This is happening when logging through The Forge

**Comment by ironmonk88** [comment]
What system are you using?  I'll see if I can replicate it on my machine.

**Comment by MarceloCortezz** [comment]
DND 5e

**Comment by MarceloCortezz** [comment]
@ironmonk88 I've been testing and so far all the tokens have been receiving the correct value.

**Comment by ironmonk88** [comment]
Closing the ticket.  I think the issues have mostly been worked out of the new function.
