### ISSUE TITLE
Suggestion: Alternative request roll UI

### ISSUE THREAD

**Issue by Ikabodo** [ironmonk88/monks-tokenbar#69]
I've been thinking about the request roll feature. I use it quite a lot.

And one option could be to reduce it by one click by using radio-buttons or something similar instead of a dropdown, at least for the common rolls like skills and saves.

I think you could still make it sort of compact, and I'd prefer to just be able to
1. Click "request roll" button
2. Click the appropriate skill
3. Make sure it's the right actors
4. Request

Anyway, just a suggestion. Nice work as always monk!

**Comment by ironmonk88** [comment]
Yeah, I havn't been feeling that dropdown for awhile now.
New UI is available with the latest release.
Let me know if this works.

**Comment by GabrielDeschain** [comment]
I would like a shortcut to the request roll menu. Or a macro that opened it would do. So wecould access it without removing the mouse from the Grid. In a much more agile way.

In time, congratulations on the excellent work, the module is incredible

**Comment by ironmonk88** [comment]
Closing this as I believe all requests have been fulfilled.
