### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by rmasoni** [ironmonk88/monks-tokenbar#7]
It'd be great if I could choose which stats to display above the tokens on the bar (currently only AC and Passive Perception), and which buttons to have on the toolbar. I don't use XP, for example, so it's a button I'll never click.

**Comment by DrWiFi** [comment]
I 2nd this request

**Comment by Jyhnu** [comment]
Lovely idea. I feel like this could also expand to Initiative rolls, even if they are easy to do by default.

**Comment by Darkiller25** [comment]
I'm all in for that too :) like passive stealth (yes it's a thing I swear!)

**Comment by MelvinMcSnatch** [comment]
I like AC and Spell Save DC, followed by Death Save successes and failures. We don't use PP.

**Comment by ironmonk88** [comment]
First attribute was customizable a couple versions ago.  Second attribute is now customizable.
Working on adding Initiative to the list of options.
XP button will be removed if you check the disable experience in DnD5e.

**Comment by ironmonk88** [comment]
I believe all of these suggestions should be covered now.
