### ISSUE TITLE
Unable to move on players turn with combat movement set.

### ISSUE THREAD

**Issue by KammaKhazi** [ironmonk88/monks-tokenbar#71]
Heya, I'm using your Little Details and Scene Navigation mods as well, which are all superb thank you for your great work. I only have one issue and that's with the combat movement options. I get the your turn is next up, it's your turn notifications and the turn highlight all on the correct player. But when combat movement is set that player gets the it's not your turn and combat movement is set message and can't move. I am using other mods to be fair Midi QoL, DAE, CUB to name a few of the main ones. Any help greatly appreciated. Everything else works absolutely great.

**Comment by ironmonk88** [comment]
Hello
DnD5e? 
Did this just start happening?  I recently updated some code that affected movement so I'm concerned it might be that.
Are there any errors in the debug console?
Would you happen to have a second combat open somewhere else that may be the combat Foundry is considering the active one?

When the player attempts to move their token, there should be a log in the debug console.  Starts with "monks-tokenbar | Blocking movement" if you could paste that into the chat, that would be amazing.

Sorry, lots of questions.  But I'll see if I can get to the bottom of this.

**Comment by KammaKhazi** [comment]
Hi again, cheers for the response. Yes to running DnD5e. I have had the issues since I started using the mod about two and a half weeks ago so definitely not the latest update. It is the only combat encounter on the tracker screen.

I'm still setting up my world locally at the mo so I'm running a test player on Chrome  whilst I'm on as GM in the application.

Got this section from the debug log during a combat where it occurred. Hope it helps, cheers.

monks-little-details |  Check combat turn Vague Goblin Caldor Pathfinder true false true {_id: "PX37z4RSA2KMdE3C", flags: {…}, tokenId: "f1JJcvcnbXhC5sYw", hidden: false, token: {…}, …} {_id: "OvEyneSRUbNDOOSg", flags: {…}, tokenId: "Ybaxlwo5mv0xkv1X", hidden: false, token: {…}, …}
monks-little-details.js:9 monks-little-details |  update combat Combat {_data: {…}, data: {…}, options: {…}, apps: {…}, compendium: null, …}
monks-little-details.js:9 monks-little-details |  checking combat started Combat {_data: {…}, data: {…}, options: {…}, apps: {…}, compendium: null, …} true
monks-little-details.js:9 monks-little-details |  Check combat turn Caldor Pathfinder Gutsy Goblin true true false {_id: "OvEyneSRUbNDOOSg", flags: {…}, tokenId: "Ybaxlwo5mv0xkv1X", hidden: false, token: {…}, …} {_id: "8ZQV6h2rT8hhSEM9", flags: {…}, tokenId: "MwzRyVbntgJrohSI", hidden: false, token: {…}, …}
monks-little-details.js:9 monks-little-details |  update combat Combat {_data: {…}, data: {…}, options: {…}, apps: {…}, compendium: null, …}
monks-tokenbar.js:12 monks-tokenbar |  unsetting notified Token {_events: i, _eventsCount: 2, tempDisplayObjectParent: null, transform: t, alpha: 1, …}
2foundry.js:4503 Foundry VTT | Rendering TokenMoldOverlay
monks-tokenbar.js:12 monks-tokenbar |  unsetting notified Token {_events: i, _eventsCount: 2, tempDisplayObjectParent: null, transform: t, alpha: 1, …}

**Comment by ironmonk88** [comment]
I think all that looks okay.
I'd need the one that starts 'monks-tokenbar | Blocking movement' though to get any definitive answer.  It'll be displayed on the players side, when they try to move a token that shouldn't be moved.

**Comment by KammaKhazi** [comment]
It's wierd, that was from the players console log in the chrome browser.  Tested it a few more times, I still get the message about not being the players turn and can't move the token via keyboard or mouse. This was in the console log, but I never see the 'monks-tokenbar | Blocking movenment' message in the log at all.

"Foundry VTT | Created ChatMessage with id tmW7MSBj5SFybPdy"

**Comment by ironmonk88** [comment]
Sorry... it may have changed to "Checking movement" instead of "Blocking movement".  Some absent minded programming there.
It should be the next message displayed in the console, when you press an arrow key, while you have the token selected.

**Comment by KammaKhazi** [comment]
Haha no worries, I know that feeling. Still no joy sorry, on the players console log I see "monks-tokenbar |  movement change" when the combat starts and then when hitting the arrow key I just get repeated lines of "monks-tokenbar |  unsetting notified Token {_events: i, _eventsCount: 2, tempDisplayObjectParent: null, transform: t, alpha: 1, …}" when the dialog displays. Could that be anything? It doesn't seem to checking the movement at all for some reason, just rejecting it straight away.

**Comment by ironmonk88** [comment]
This is really weird.
blockCombat should only ever fire if the movement is in combat mode.  And once it reaches there, it should default to being pessimistic.  Tokens are by default blocked unless they can pass the test.  And if the movement is set to combat mode and the combat hasn't started then all movement is blocked.

But... the fact that it shows the 'unsetting notified' means the function was activated.  Which implies one of two things, either the movement is set to none, or the active combat hasn't been started (according to Foundry).

How comfortable are you setting a break point in javascript?  I've added extra debugging lines, but you'll have to wait until the next release of the module for you to use them.

if you break on the line that reads 
`if (curCombat && curCombat.started) {`
and confirm that Tokenbar thinks the combat has started that would clear things up really quickly.

Otherwise I also don't mind doing a Discord screen share, if you're on that platform.

**Comment by KammaKhazi** [comment]
Just had a read up on it, yeah should be fine. No probs can wait for next module update, cheers for looking into it.

**Comment by KammaKhazi** [comment]
Just tried adding that break point, very odd like you said the curcombat is undefined when it hits the break point. Took a screenshot in case there is anything there that helps.

![CurCombat](https://user-images.githubusercontent.com/81476445/113070329-3be8f700-91ba-11eb-9723-922650463343.png)

**Comment by ironmonk88** [comment]
Oh that is really weird.
But also... thank you.

Can you tell me what both game and game.combats show?
I'm guessing this is an issue with game.combats.active not being set properly... but I want to check.

**Comment by ironmonk88** [comment]
'kay latest release is out.
You'll need to enter `game.settings.set('monks-tokenbar', 'debug', true)` into the console window of the GM to get the extra debug information.
But the information will show up on the player side.
It's a bit weird.
It should spit out a bunch of stuff when the player tries to move.

If this doesn't clear things up then we might need to do a discord screen share.  Assuming you're on discord.

**Comment by KammaKhazi** [comment]
Hiya Monk, just taken a look. This is what it was spitting out as I hit the movement keys as player. Yeah I am on foundry discord if  needed cheers.

monks-tokenbar.js:12 monks-tokenbar |  movement  combat Token {_events: i, _eventsCount: 8, tempDisplayObjectParent: null, transform: t, alpha: 1, …}
monks-tokenbar.js:268 Uncaught TypeError: Cannot read property 'started' of undefined
    at blockCombat (monks-tokenbar.js:268)
    at Function.allowMovement (monks-tokenbar.js:304)
    at Token._canDrag (monks-tokenbar.js:45)
    at MouseInteractionManager.can (foundry.js:36379)
    at MouseInteractionManager._handleClickLeft (foundry.js:36583)
    at MouseInteractionManager._handleMouseDown (foundry.js:36560)
    at Token.a.emit (index.js:181)
    at r.dispatchEvent (InteractionManager.ts:1106)
    at r.processPointerDown (InteractionManager.ts:1307)
    at t.recursiveFindHit (TreeSearch.ts:173)
blockCombat @ monks-tokenbar.js:268
allowMovement @ monks-tokenbar.js:304
Token._canDrag @ monks-tokenbar.js:45
can @ foundry.js:36379
_handleClickLeft @ foundry.js:36583
_handleMouseDown @ foundry.js:36560
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252
monks-tokenbar.js:12 monks-tokenbar |  movement  combat Token {_events: i, _eventsCount: 8, tempDisplayObjectParent: null, transform: t, alpha: 1, …}
monks-tokenbar.js:268 Uncaught TypeError: Cannot read property 'started' of undefined
    at blockCombat (monks-tokenbar.js:268)
    at Function.allowMovement (monks-tokenbar.js:304)
    at Token._canDrag (monks-tokenbar.js:45)
    at MouseInteractionManager.can (foundry.js:36379)
    at MouseInteractionManager._handleClickLeft (foundry.js:36583)
    at MouseInteractionManager._handleMouseDown (foundry.js:36560)
    at Token.a.emit (index.js:181)
    at r.dispatchEvent (InteractionManager.ts:1106)
    at r.processPointerDown (InteractionManager.ts:1307)
    at t.recursiveFindHit (TreeSearch.ts:173)
blockCombat @ monks-tokenbar.js:268
allowMovement @ monks-tokenbar.js:304
Token._canDrag @ monks-tokenbar.js:45
can @ foundry.js:36379
_handleClickLeft @ foundry.js:36583
_handleMouseDown @ foundry.js:36560
a.emit @ index.js:181
r.dispatchEvent @ InteractionManager.ts:1106
r.processPointerDown @ InteractionManager.ts:1307
t.recursiveFindHit @ TreeSearch.ts:173
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.recursiveFindHit @ TreeSearch.ts:113
t.findHit @ TreeSearch.ts:200
r.processInteractive @ InteractionManager.ts:1177
r.onPointerDown @ InteractionManager.ts:1252
monks-tokenbar.js:12 monks-tokenbar |  movement  combat Token {_events: i, _eventsCount: 8, tempDisplayObjectParent: null, transform: t, alpha: 1, …}

**Comment by KammaKhazi** [comment]
It get's wierder as I'm still getting the errors above but I can now move the character without the not your turn message as the player =)

**Comment by KammaKhazi** [comment]
Hi again. Further to that, having done some more combat testing, I notice the player can now move even when it's not their turn in combat, so unfortunately not sorted itself out.

**Comment by KammaKhazi** [comment]
Hi monk, managed to sort out what was happening here after speaking to Kandaski on discord. I didn't have the scene I was testing the combat in activated so game.combats.active wasn't populated. All is working fine now cheers.

**Comment by ironmonk88** [comment]
That is awesome!  Tell Kandaki that I own them a beer.
