### ISSUE TITLE
[feature][dnd5e] inspiration handling

### ISSUE THREAD

**Issue by PaulWRoberts** [ironmonk88/monks-tokenbar#72]
I would like to request a feature be able to show on the tokenbar if the player has inspiration. Additionally I would request a feature to grant and remove inspiration.

**Comment by ironmonk88** [comment]
Added the inspiration display to the tokenbar icon.
Not going to add a a feature to grant or remove inspiration as double-clicking on the icon will give you access to the character sheet and you can make the changes there.
Should be available with the latest release, but you will have to turn it on in configuration.
