### ISSUE TITLE
Perception isn't adding the 10 any more

### ISSUE THREAD

**Issue by Maghawk** [ironmonk88/monks-tokenbar#74]
Running in Pathfinder 2e. 
Fairly certain it used to work, but now it just shows the modifier not the DC (isn't adding 10, basically). I don't know fancy code, but the default Stat 2 Resource calculation seems very simple so unsure what to change, if anything.
Easy to add the 10 in my brain, but I figure it's a symptom of something else?
![perception DC not calculating](https://user-images.githubusercontent.com/81623344/112977483-05759280-914e-11eb-83a0-2fb3841109c5.png)

**Comment by RobTheDM** [comment]
Can confirm this is the case in my PF2e game as well. Tried messing around with the formula (removed spaces, flipped it to 10+attributes.perception.value, tried attributes.perception.totalModifier) and nothing changed.

**Comment by ironmonk88** [comment]
It looks like the fix to the fixes broke something again.
The fix for the fix should be fixed next release.  :-)
And at some point I'll get this formula to work properly.

**Comment by ironmonk88** [comment]
Should be fixed now.  :-)
