### ISSUE TITLE
droping player folder tokens bug

### ISSUE THREAD

**Issue by Shenanigan83** [ironmonk88/monks-tokenbar#75]
using pathfinder 2e

When droping my player folder using furnace module, I cant move some of the tokens or I cant even delete them. When I reload app using escape key, the bugged tokens disappear completly as if they have never been dropped on the scene. The remaining tokens that worked stay present on the scene.  

This only happens when I try to drop more than 4 tokens and sometimes on a scene it occurs 100% of the time, sometimes on another scene it happens 20% of the time when I drop more than 4 tokens.

If I drop 4 tokens or less, it works as usual 100% of the time. I also disabled monk tokenbar  and when I drop my folder, it works 100% of the time on every scene.. Something goes wrong with the module..

Edit : I went a bit further. I put a single player on the scene and then I drag dropped my player folder with only 4 tokens inside and it still bugs...   Same is true  If I put a familiar token the the scene. It really has to do with the fifth tokens

**Comment by ironmonk88** [comment]
I think I know what's causing it.
I'll see if I can get a workaround for the next release.

**Comment by ironmonk88** [comment]
Next release is out, let me know if this is still an issue

**Comment by Shenanigan83** [comment]
It looks like it is fixed now. Its working properly. Thanks.

**Comment by ironmonk88** [comment]
Yayy!  Closing the ticket.  :-)
