### ISSUE TITLE
Request Death Save

### ISSUE THREAD

**Issue by DrWiFi** [ironmonk88/monks-tokenbar#8]
Could you please add an option to request a Death Save in the Request a Roll box?
Thanks

**Comment by ironmonk88** [comment]
Death Saving throw will be available in the next version.

**Comment by ironmonk88** [comment]
Death Saving throw should now be available.  If the token selected is at zero HP it will automatically default to this option.  And it will automatically set the DC to 10.  Only available in DnD5e.
