### ISSUE TITLE
Bug with CUB enhanced conditions and convert to loot

### ISSUE THREAD

**Issue by Darshyne** [ironmonk88/monks-tokenbar#82]
![error](https://user-images.githubusercontent.com/47222495/114580741-6a1d0b00-9c7f-11eb-879c-58f43988f472.JPG)
When a token have an enhanced condition (CUB module) there is an error with the convert to loot tool:
- the condition is not removed and you have to push the convert button multiple time to convert the creature to loot.

the error message :
  | removeAllConditions | @ | enhanced-conditions.js:1324
-- | -- | -- | --
  | convertToLootable | @ | lootables.js:180
  | async function (async) |   |  
  | convertToLootable | @ | lootables.js:168
  | i | @ | jquery.min.js:2
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

**Comment by ironmonk88** [comment]
I'll look into it.  It seems to suggest that the token I'm passing in isn't acceptable.

**Comment by ironmonk88** [comment]
Fixed this in the latest release.
