### ISSUE TITLE
[Feture Request] Allow to define which player info is displayed

### ISSUE THREAD

**Issue by miguel-pinto-prodmad** [ironmonk88/monks-tokenbar#86]
Currently, the token bar displays the actor AC and Passive perception.

There are useful but there may be other things that are also useful, like HP, movement, etc...

It would be great if we could choose/config which attributes to show for the players.
Ideally, it would be nice to add as many attributes as we wish BUT if for some reason it needs to be restricted, I think that at least 3 would be good enough to start with.

Thank you.

**Comment by ironmonk88** [comment]
You can already change what stats are displayed in the configuration menu.
And you can also show the resource bars that the token has.  
I feel like 4 attributes should be good enough.

**Comment by PalaNolho** [comment]
I can only see options to configure Stat1 and Stat2
Where are the other 2 you mentioned? are you considering the resources?

What if I want to see `HP`, `AC` and `Passive Perception`? how can I do that?

This is what I see on my config (module v1.0.34)
![image](https://user-images.githubusercontent.com/6009914/116051976-1a701380-a671-11eb-8f67-7089d478e8cd.png)

**Comment by ironmonk88** [comment]
Closing this old ticket as the feature has been updated and you can customize as many as you want now.
