### ISSUE TITLE
Excluding player characters from gaining XPs in the dialog still counts them as a share

### ISSUE THREAD

**Issue by adamspecial** [ironmonk88/monks-tokenbar#87]
When you exclude a character with the trashcan icon from getting XP in the award XP dialog, using any "divide XP among players" options, it still counts them as a share that gets subtracted from the total.

For example, if there are 2 players and 100 XPs to divide, but you exclude one player, the other will always get only 50 XPs.

I would love to use this module's award XP dialogs, but we always have at least one sidekick in the group, which still has to be created as a "player character" to be manageable (for a variety of reasons: resting and recovering HP with hit dice, half-spellcaster progression, etc.), but doesn't ever get any XP, nor does afftect how much XP should the actual player characters gain.

**Comment by ironmonk88** [comment]
The xp dialog has been updated since this ticket was opened.
I believe this has been fixed.
Feel free to re-open if it hasn't been fixed yet.
