### ISSUE TITLE
[Bug] PF1 rolls not respecting selected roll mode

### ISSUE THREAD

**Issue by RobTheDM** [ironmonk88/monks-tokenbar#89]
Recently the Request Roll feature has stopped respecting the roll mode selected by the GM when requesting a roll from players. It even doesn't seem to be showing the rolled result to the GM in the chat card where it should, as you can see in the image here. The roll was requested as blind GM, but the roll itself was public, and the result itself doesn't show up where it should be in the initial roll chat card. 
![rolls](https://user-images.githubusercontent.com/66711614/116947200-f85a3080-ac30-11eb-9b45-b09ff9460ffd.JPG)

**Comment by ironmonk88** [comment]
Closing this as the ticket is old and I believe the issue was fixed awhile ago.
