### ISSUE TITLE
Suggestion: Add an hp overlay on the portrait/token. 

### ISSUE THREAD

**Issue by Ikabodo** [ironmonk88/monks-tokenbar#9]
It would be really cool if you could add an overlay on the token/portrait that shows hp at a glance. For example a red overlay that gradually covers more of the portrait from the bottom up). Similar to the way tidysheet does it. This way you can really quickly see if a character is hurt, or not hurt.

You can also add a click function on the portrait to add or remove hp (but this might be redundant if you use alwayshp)

This will also work well with: #10

**Comment by ironmonk88** [comment]
Added bars to match what's on the token.  So that the user can specify what they want to see instead of limiting it to just HP.  And it'll keep the interface consistent between systems.
Should be available next version.

I'll leave the change of HP to a different module though.

**Comment by Ikabodo** [comment]
Nice work monk!
Will this respect the setting on the bars on the token?

**Comment by ironmonk88** [comment]
This should mirror what you see with the token.  Including the colours.
New version is now available with these changes.
