### ISSUE TITLE
Vertical orientation and scrolling

### ISSUE THREAD

**Issue by yorkshirelandscape** [ironmonk88/monks-tokenbar#94]
You probably don't get many people in this situation, but I'm managing a campaign with a large scale battle scene in which there are many tokens representing military units. The Token Bar would be particularly useful in this situation, except that it occupies too much space. A vertical orientation option with scrolling (rather than just running off the screen) would be very useful. 

Thanks for making this excellent module.

**Comment by ironmonk88** [comment]
Vertical orientation was added awhile ago.  Just cleaning up tickets.
