### ISSUE TITLE
On "Convert to Lootable" action we get game.users.entries.filter is not a function on Foundry 0.8.6

### ISSUE THREAD

**Issue by p4535992** [ironmonk88/monks-tokenbar#95]
**Environment Details**

Foundry VTT Version: 0.8.6

Operating System: \[Linux\]

How Are You Using Foundry: \[Linux,Native Application (Electron), Chrome\]

Which Game System: Dungeons and Dragons 5th Edition, version 1.3.3

Modules Enabled?: Yes

Module version: 1.0.37

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

![alt](https://i.imgur.com/7kY1AiY.png)

**Comment by ironmonk88** [comment]
Should be working better now.
Let me know if this is still causing issues.

**Comment by p4535992** [comment]
**Version: 1.0.39**  solved the previous issue , but if i set to true the check box  "Assign gold by CR"  i get a similar exception:
![alt](https://i.imgur.com/hIVDJHC.png)

**Comment by samgrieve** [comment]
Same issue as above. I also get an empty row at the top of the convert to lootable list after every combat

**Comment by ironmonk88** [comment]
Should be fixed int he latest version

**Comment by ironmonk88** [comment]
Closing this as it should be fixed now.
