### ISSUE TITLE
Convert Lootables has one blank row for each player character in the combat at combat end

### ISSUE THREAD

**Issue by samgrieve** [ironmonk88/monks-tokenbar#97]
![lootables](https://user-images.githubusercontent.com/22322830/120933248-1cf26e00-c6f1-11eb-81a1-2b13a329805b.PNG)

**Comment by ironmonk88** [comment]
Well... that's not right.
Are there any combatants that that might correspond to?

**Comment by samgrieve** [comment]
The number of blank rows is always equal to the number of player characters I have in the combat. Have tried combats with 1-5 PC actors and the number of rows always corresponds exactly

**Comment by samgrieve** [comment]
All sorted with 1.0.40

Thanks for all the work :)
